### ISSUE TITLE
经常报以下warning

### ISSUE THREAD

**Issue by typedef** [wechaty/wechaty#1634]
```shell
(node:1818) UnhandledPromiseRejectionWarning: Error: WXGetMsgImage , stranger,error! canot get result from websocket server
    at PadchatManager.<anonymous> (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:1335:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:1818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 86)
10:08:33 WARN PuppetPadchat messageFile(2296763595448356121)
(node:1818) UnhandledPromiseRejectionWarning: Error: WXGetMsgImage , stranger,error! canot get result from websocket server
    at PadchatManager.<anonymous> (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:1335:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:1818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 87)
10:08:34 WARN PuppetPadchat messageFile(6224845306862463221)
(node:1818) UnhandledPromiseRejectionWarning: Error: WXGetMsgImage , stranger,error! canot get result from websocket server
    at PadchatManager.<anonymous> (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:1335:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/wechatgroup/node_modules/wechaty/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:1818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 88)
```

**Comment by lijiarui** [comment]
### Need More Information

I suggest you not follow the **ISSUE Template**, this issue doesn't have enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.
