### ISSUE TITLE
(node:24909) UnhandledPromiseRejectionWarning: TypeError: message.toRecalled is not a function

### ISSUE THREAD

**Issue by Papeone** [wechaty/wechaty#1771]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

error log

(node:24909) UnhandledPromiseRejectionWarning: TypeError: message.toRecalled is not a function
    at recall (/Users/julive/WebstormProjects/juliveWechatBot/juliveBot/bot.js:190:47)
    at Wechaty.bot.on.on.on.on (/Users/julive/WebstormProjects/juliveWechatBot/juliveBot/bot.js:46:9)
    at Wechaty.on.args (/Users/julive/WebstormProjects/juliveWechatBot/juliveBot/node_modules/wechaty/dist/src/wechaty.js:383:26)
    at Wechaty.emit (events.js:182:13)
    at Wechaty.EventEmitter.emit (domain.js:442:20)
    at Wechaty.emit (/Users/julive/WebstormProjects/juliveWechatBot/juliveBot/node_modules/wechaty/dist/src/wechaty.js:179:22)
    at Wechaty.<anonymous> (/Users/julive/WebstormProjects/juliveWechatBot/juliveBot/node_modules/wechaty/dist/src/wechaty.js:477:30)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/julive/WebstormProjects/juliveWechatBot/juliveBot/node_modules/wechaty/dist/src/wechaty.js:4:58)

**Comment by windmemory** [comment]
This is not a feature request, and this feature is implemented. You need to upgrade your wechaty to the latest version, use `npm install wechaty@next` to get the latest version.
