### ISSUE TITLE
get error when login

### ISSUE THREAD

**Issue by joneqian** [wechaty/wechaty#1916]
```
12:38:39 WARN PuppetPuppeteerBridge onDialog() page.on(dialog) type:type() {
    return this._type;
  } message:为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com
(node:38) UnhandledPromiseRejectionWarning: Error: Error: type() {
    return this._type;
  }(为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com)
    at PuppetPuppeteer.puppet.on.error (/bot/node_modules/_wechaty@0.30.23@wechaty/src/wechaty.ts:616:32)
    at PuppetPuppeteer.emit (events.js:198:13)
    at PuppetPuppeteer.EventEmitter.emit (domain.js:448:20)
    at PuppetPuppeteer.emit (/bot/node_modules/_wechaty-puppet@0.18.3@wechaty-puppet/src/puppet.ts:284:18)
    at Bridge.bridge.on.e (/bot/node_modules/_wechaty@0.30.23@wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:307:43)
    at Bridge.emit (events.js:198:13)
    at Bridge.EventEmitter.emit (domain.js:448:20)
    at Bridge.<anonymous> (/bot/node_modules/_wechaty@0.30.23@wechaty/node_modules/wechaty-puppet-puppeteer/src/bridge.ts:176:10)
    at Generator.next (<anonymous>)
    at fulfilled (/bot/node_modules/_wechaty@0.30.23@wechaty/node_modules/wechaty-puppet-puppeteer/dist/src/bridge.js:23:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by huan** [comment]
Duplicated with #603
