### ISSUE TITLE
initChromeDriver() got invalid driver

### ISSUE THREAD

**Issue by AaronZhang9511** [wechaty/wechaty#192]
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 

[root@localhost wechaty]# node zlgbot.js
INFO Wechaty v0.7.2 initializing...
WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1

### Paste the full output logs here with `WECHATY_LOG=silly` set

INFO Wechaty v0.7.2 initializing...
WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
ERR Config ###########################
ERR Config unhandledRejection: Error: Server terminated early with status 127 [object Promise]
ERR Config ###########################
WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
ERR Config ###########################
ERR Config unhandledRejection: Error: Server terminated early with status 127 [object Promise]
ERR Config ###########################
WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() with retry: 3
ERR Config ###########################
ERR Config unhandledRejection: Error: Server terminated early with status 127 [object Promise]
ERR Config ###########################
WARN PuppetWebBrowserDriver valid() getSession() catch() rejected: Server terminated early with status 127
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: Server terminated early with status 127
WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver initChromeDriver() not valid after retry: 4 times: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/usr/program/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:116:35)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/program/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERR PuppetWebBrowser init() exception: initChromeDriver() got invalid driver
ERR PuppetWebBrowser quit() this.driver.quit() exception Server terminated early with status 127
ERR Config ###########################
ERR Config unhandledRejection: Error: Server terminated early with status 127 [object Promise]
ERR Config ###########################
ERR PuppetWeb initBrowser() exception: initChromeDriver() got invalid driver
ERR PuppetWeb init() exception: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (/usr/program/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:116:35)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/program/node_modules/wechaty/dist/src/puppet-web/browser-driver.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
ERR Wechaty init() exception: initChromeDriver() got invalid driver
ERR Config ###########################
ERR Config unhandledRejection: Error: initChromeDriver() got invalid driver [object Promise]
ERR Config ###########################
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)

**Comment by zixia** [comment]
It seems you are running Wechaty in a Linux Server without Xvfb(headless) setting.

Using [[Docker|Docker]] is recommended for you, or please provide more details by follow the ISSUE Template.

### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

I'll close this issue. Please re-submit a new issue to provide the information that needed.

**Comment by zixia** [comment]
@AaronZhang9511 How about your issue now, Have you resolved it?

**Comment by git4sun** [comment]
I got the same problem. How do you run wechaty on a linux with Xvfb setting? Did a little search and found [this](http://elementalselenium.com/tips/38-headless) . Is wechaty based on selenium?

**Comment by zixia** [comment]
Hope you are doing good. Will close this issue from now.

**Comment by cncoder** [comment]
Hi, Zixia.This is pretty nice projetct. But I also encountered the same problem.

### `npm run doctor, output:`

`npm run doctor

> wechaty@0.7.58 doctor E:\node\wechaty
> npm run check-node-version && ts-node bin/doctor


> wechaty@0.7.58 check-node-version E:\node\wechaty
> check-node-version --node ">= 6.9"

node: 6.10.0
npm: 3.10.10
yarn: 0.22.0

  #### Wechaty Doctor

  1. Wechaty version: #git[6926166 chore(package): update yarn to version 0.22.0 (#397)]
  2. Windows_NT x64 version 10.0.14393 memory 2423/8112 MB
  3. Docker: false
  4. Node version: v6.10.0
  5. Tcp IPC TEST: PASS`

### When I run npm start,
 
E:\node\wechaty>npm start

```
> wechaty@0.7.58 start E:\node\wechaty
> npm run demo


> wechaty@0.7.58 demo E:\node\wechaty
> ts-node example/ding-dong-bot.ts


| __        __        _           _
| \ \      / /__  ___| |__   __ _| |_ _   _
|  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
|   \ V  V /  __/ (__| | | | (_| | |_| |_| |
|    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
|                                     |___/

=============== Powered by Wechaty ===============
-------- https://github.com/zixia/wechaty --------

I'm a bot, my super power is talk in Wechat.

If you send me a 'ding', I will reply you a 'dong'!
__________________________________________________

Hope you like it, and you are very welcome to
upgrade me for more super powers!

Please wait... I'm trying to login in...


01:46:40 INFO Wechaty v#git[6926166 chore(package): update yarn to version 0.22.0 (#397)] initializing...
01:46:42 WARN BrowserDriver valid() fail: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:63053
01:46:42 WARN BrowserDriver valid() fail: two = Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:63053 ?
01:46:42 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
01:46:42 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 1
01:46:44 WARN BrowserDriver valid() fail: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:63053
01:46:44 WARN BrowserDriver valid() fail: two = Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:63053 ?
01:46:44 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
01:46:44 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 2
01:46:47 WARN BrowserDriver valid() fail: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:63053
01:46:47 WARN BrowserDriver valid() fail: two = Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:63053 ?
01:46:47 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
01:46:47 WARN PuppetWebBrowserDriver initChromeDriver() with retry: 3
01:46:49 WARN BrowserDriver valid() fail: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:63053
01:46:49 WARN BrowserDriver valid() fail: two = Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:63053 ?
01:46:49 WARN PuppetWebBrowserDriver initChromeDriver() got invalid driver
01:46:49 WARN PuppetWebBrowserDriver initChromeDriver() not valid after retry: 4 times: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (E:\node\wechaty\src\puppet-web\browser-driver.ts:138:21)
    at next (native)
    at fulfilled (E:\node\wechaty\src\puppet-web\browser-driver.ts:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
01:46:49 ERR PuppetWebBrowser init() exception: initChromeDriver() got invalid driver
01:46:52 ERR PuppetWebBrowser quit() this.driver.quit() exception ECONNREFUSED connect ECONNREFUSED 127.0.0.1:63053
01:46:52 ERR PuppetWeb initBrowser() exception: initChromeDriver() got invalid driver
01:46:52 ERR PuppetWeb init() exception: Error: initChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (E:\node\wechaty\src\puppet-web\browser-driver.ts:138:21)
    at next (native)
    at fulfilled (E:\node\wechaty\src\puppet-web\browser-driver.ts:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
01:46:52 INFO Bot error: Error: initChromeDriver() got invalid driver
(node:12456) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: can not say before login
(node:12456) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'quit' of undefined
```


* By the way, I spent a lot of energy to install the environment. I know use docker that will be very easy to use wechaty, but I still want to try to use npm command .Because I think that docker is a production tool, is not conducive to develop or debug.Thanks a lot.

**Comment by zixia** [comment]
@cncoder Thanks for using Wechaty.

Docker is not only a production tool but also is conducive to develop and debug. I encourage you to use docker instead.

If you still want to setup the whole environment, could you tell me your version of chromedriver?

**Comment by cncoder** [comment]
@zixia  
This is cmd stdout， Thanks
```
C:\Users\XXXX>chromedriver
Starting ChromeDriver ( **v2.9.248315** ) on port 9515
```

**Comment by zixia** [comment]
2.9 is too old.

You should use 2.29 now.

**Comment by cncoder** [comment]
It Works! Thank you very much.
