### ISSUE TITLE
Problems when using wechaty as token gateway server

### ISSUE THREAD

**Issue by zavierxu** [wechaty/wechaty#1988]
I'm running wechaty docker version as token gateway server on Ubuntu 18.04 (Let's say this one is the `Server`)
I'm running wechaty python version , with the last [example code](https://github.com/wechaty/python-wechaty-getting-started/blob/master/examples/ding-dong-bot.py). (Let's say this one is the `Client`)

There are 2 problems here.

1) Every time `Client` will show 2 different QR codes, both can be scanned and log wechat successfully.

2) After logged into wechaty, I tried to send "ding" to my wechat bot. `Server` shows error with 
```
messagePattern: 'Assertion failed'
```
At the same time. `Client` ran into endless loop, keeps printing 
```
2020-05-28 08:50:33 INFO wechaty.py <error_listener> receive <error> event <(<Status.INTERNAL: 13>, 'Assertion failed', None)>
```
in the console.

**Comment by zavierxu** [comment]
Here is the verbose log which may help to locate the problem.
`
08:40:11 VERB EventStreamManager grpcEmit(EVENT_TYPE_SCAN[22], {"qrcode":"http://weixin.qq.com/x/YYe...first_code","status":2})
08:40:11 VERB PuppetServiceImpl ding()
08:40:11 VERB EventStreamManager grpcEmit(EVENT_TYPE_DONG[3], {"data":"ding-dong"})
08:40:12 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"","timeout":60000})
08:40:12 VERB PadplusManager setContactAndRoomData() can not proceed due to no cache.
08:40:15 INFO IoClient [2] http://weixin.qq.com/x/IYl2i....second_code
08:40:15 VERB EventStreamManager grpcEmit(EVENT_TYPE_SCAN[22], {"qrcode":"http://weixin.qq.com/x/IYl2i....second_code","status":2})
08:40:15 VERB PuppetServiceImpl ding()
08:40:15 VERB EventStreamManager grpcEmit(EVENT_TYPE_DONG[3], {"data":"ding-dong"})
08:40:29 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"","timeout":60000})
08:40:29 VERB PadplusManager setContactAndRoomData() can not proceed due to no cache.
`

**Comment by zavierxu** [comment]
The 2nd one:
```
08:49:28 VERB Puppet messagePayload(4548687293285196463)
Error [AssertionError]: Assertion failed
    at new goog.asserts.AssertionError (/wechaty/node_modules/google-protobuf/google-protobuf.js:81:876)
    at Object.goog.asserts.doAssertFailure_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:82:257)
    at Object.goog.asserts.assert [as assert] (/wechaty/node_modules/google-protobuf/google-protobuf.js:83:83)
    at jspb.BinaryEncoder.writeUnsignedVarint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:458:77)
    at jspb.BinaryWriter.writeUnsignedVarint64_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:480:507)
    at jspb.BinaryWriter.writeUint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:485:471)
    at Function.proto.wechaty.puppet.MessagePayloadResponse.serializeBinaryToWriter (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:849:12)
    at proto.wechaty.puppet.MessagePayloadResponse.serializeBinary (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:812:47)
    at serialize_wechaty_puppet_MessagePayloadResponse (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet_grpc_pb.js:460:26)
    at sendUnaryResponse (/wechaty/node_modules/grpc/src/server.js:98:15)
    at sendUnaryData (/wechaty/node_modules/grpc/src/server.js:600:9)
    at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-hostie/src/server/puppet-implementation.ts:524:16)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/wechaty-puppet-hostie/dist/src/server/puppet-implementation.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  reportErrorToServer: true,
  messagePattern: 'Assertion failed',
  code: 13
}
```

**Comment by zavierxu** [comment]
Following steps may help you to reproduce the problem.

1. Clone the latest version of python-wechaty-getting-started
2. Run docker version wechaty as token gateway server.
3. Install requirements, set environments.
4. Run python example code
`The program shows more than one QRCode at this moment.`
5. Scan one of the codes and log into wechaty successfully.
6. Use another wechat account send a message to this one.
`The Server got Assertion failed, Client ran into endless loop`

**Comment by huan** [comment]
Thanks for the description for the reproduce steps!

May I ask you that what kind of the token are you using for the gate service? Padplus, or puppeteer?

**Comment by zavierxu** [comment]
> Thanks for the description for the reproduce steps!
> 
> 
> 
> May I ask you that what kind of the token are you using for the gate service? Padplus, or puppeteer?

I’m using padplus token.

**Comment by jcai** [comment]
@zavierxu  you can try

```
docker run -e "WECHATY_PUPPET_PADPLUS_TOKEN=puppet_padplus_xxxxxxxxxxx" 
    docker.pkg.github.com/wechaty/scala-wechaty/ding-dong-bot:0.0.16-SNAPSHOT
```

**Comment by huan** [comment]
@zavierxu Please update the Wechaty Docker Image to the latest for fix this problem with the Token Gateway.
