### ISSUE TITLE
Fail to Start for the First Time on Windows

### ISSUE THREAD

**Issue by zzc-tongji** [wechaty/wechaty#2002]
### Description

- Fail to start for the first time on Windows.
- However, it works when running again.

### Environment

- Wechaty 0.40.10
- wechaty-puppet-puppeteer (default) OR wechaty-puppet-wechat4u
- Node.js v12.16.2
- Windows 10, 1909, 18363

### Representation

- Use any wechaty project on Windows.
- If `node_modules` exists, delete it.
- Execute `npm install  && npm start`.

### Log

``` text
03:14:03 INFO PuppetManager install(wechaty-puppet-puppeteer@^0.21.2) please wait ...
npm: npm WARN 
npm: deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

npm: 
> puppeteer@2.1.1 install %PROJECT_DIR%\node_modules\wechaty\node_modules\puppeteer
> node install.js


npm: 

npm: Chromium downloaded to %PROJECT_DIR%\node_modules\wechaty\node_modules\puppeteer\.local-chromium\win64-722234

npm: npm WARN wechaty-puppet-puppeteer@0.21.2 requires a peer of wechaty-puppet@^0.21.12 but none is installed. You must install peer dependencies yourself.

npm: npm WARN rx-queue@0.8.5 requires a peer of brolog@^1.4.9 but none is installed. You must install peer dependencies yourself.

npm: 

npm: + wechaty-puppet-puppeteer@0.21.2
added 135 packages from 216 contributors and audited 11 packages in 9.499s

npm: 
2 packages are looking for funding
  run `npm fund` for details


npm: found 0 vulnerabilities


03:14:13 INFO PuppetManager install(wechaty-puppet-puppeteer@^0.21.2) done
03:14:13 INFO wechaty::error Error: Cannot find module 'wechaty-puppet-puppeteer'
Require stack:
- %PROJECT_DIR%\node_modules\wechaty\dist\src\puppet-manager.js
- %PROJECT_DIR%\node_modules\wechaty\dist\src\wechaty.js
- %PROJECT_DIR%\node_modules\wechaty\dist\src\index.js
- %PROJECT_DIR%\src\main.js
03:14:13 INFO restart 
03:14:13 INFO wechaty::stop 

(... repeat 3 times ...)

03:14:18 INFO PuppetManager install(wechaty-puppet-puppeteer@^0.21.2) please wait ...
npm: npm
npm:  WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

Error: Cannot find module 'wechaty-puppet-puppeteer'
Require stack:
- %PROJECT_DIR%\node_modules\wechaty\dist\src\puppet-manager.js 
- %PROJECT_DIR%\node_modules\wechaty\dist\src\wechaty.js        
- %PROJECT_DIR%\node_modules\wechaty\dist\src\index.js
- %PROJECT_DIR%\src\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at %PROJECT_DIR%\node_modules\wechaty\src\puppet-manager.ts:120:26 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '%PROJECT_DIR%\\wechaty\\node_modules\\wechaty\\dist\\src\\puppet-manager.js',
    '%PROJECT_DIR%\\wechaty\\node_modules\\wechaty\\dist\\src\\wechaty.js',
    '%PROJECT_DIR%\\wechaty\\node_modules\\wechaty\\dist\\src\\index.js',
    '%PROJECT_DIR%\\wechaty\\src\\main.js'
  ]
}
03:14:13 ERR Wechaty start() exception: Cannot find module 'wechaty-puppet-puppeteer'
Require stack:
- %PROJECT_DIR%\node_modules\wechaty\dist\src\puppet-manager.js
- %PROJECT_DIR%\node_modules\wechaty\dist\src\wechaty.js       
- %PROJECT_DIR%\node_modules\wechaty\dist\src\index.js
- %PROJECT_DIR%\src\main.js
03:14:13 WARN Wechaty stop() puppet.stop() exception: Cannot read property 'stop' of undefined
Error: Cannot find module 'wechaty-puppet-puppeteer'
Require stack:
- %PROJECT_DIR%\node_modules\wechaty\dist\src\puppet-manager.js 
- %PROJECT_DIR%\node_modules\wechaty\dist\src\wechaty.js        
- %PROJECT_DIR%\node_modules\wechaty\dist\src\index.js
- %PROJECT_DIR%\src\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at %PROJECT_DIR%\node_modules\wechaty\src\puppet-manager.ts:120:26 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '%PROJECT_DIR%\\wechaty\\node_modules\\wechaty\\dist\\src\\puppet-manager.js',
    '%PROJECT_DIR%\\wechaty\\node_modules\\wechaty\\dist\\src\\wechaty.js',
    '%PROJECT_DIR%\\wechaty\\node_modules\\wechaty\\dist\\src\\index.js',
    '%PROJECT_DIR%\\wechaty\\src\\main.js'
  ]
}

(... repeat several times, output to console and cannot be redirected to file ...)
```

**Comment by huan** [comment]
Have you tried that to install the `wechaty-puppet-puppeteer` by yourself before you start Wechaty?

I guess that there might be some bugs for the live install codes in the Wechaty, so do a pre-install for your puppet might help.

Please let me know whether the pre-install solves this issue, thanks.

**Comment by zzc-tongji** [comment]
I add `wechaty-puppet-puppeteer` into `package.json` and install at the very beginning.

However, it seems that it doesn't work (still needs to start twice).
