### ISSUE TITLE
padplus 异常重新登录

### ISSUE THREAD

**Issue by xiaogan18** [wechaty/wechaty#2004]
## 异常
PuppetPadplus 掉线重新登录

## logs
<pre>
17:39:36 WARN Puppet constructor() watchdog.on(reset) reason: {"data":"ea2084d9-82c9-445f-a1bc-c2ca2e90f3d2","timeout":60000}
17:39:36 INFO PuppetPadplus stop()
17:39:36 INFO PuppetPadplus logout(true, logout in wechaty)
17:39:36 INFO Contact<repe-cpp> logout
17:39:41 INFO PuppetPadplus start()
17:47:28 ERR PadplusUser can not get callback result of INIT
17:47:34 INFO Contact<repe-cpp> login
</pre>

**Comment by xiaogan18** [comment]
已经是第二次出现，并且重新上线后会获取到很久以前的微信消息，是否有什么办法过滤这些旧消息？

**Comment by huan** [comment]
The Message class has a method named `age()`, which can tell you the age of this message.

You can try to filter out the messages based on their age.

**Comment by xiaogan18** [comment]
what's the unit of `age()`,I realize this function return as a number

**Comment by huan** [comment]
Please see the related code: it's the number of seconds since the message was born.

**Comment by xiaogan18** [comment]
OK. So why this situation happened, I must keep stability of my WeChat bot, but this situation is fatal.

**Comment by xiaogan18** [comment]
Happened again today morning, logs below :
```
09:03:17 ERR GRPC_GATEWAY ApiType: SEND_MESSAGE request timeout, traceId: e182bd2f-0c5e-4ab7-babd-424d3da5a9f1
(node:27090) UnhandledPromiseRejectionWarning: Error: can not send message due to this error: Error: can not get response from grpc server
    at PadplusMessage.<anonymous> (/home/ubuntu/.repe/repe_bot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/message.js:180:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/.repe/repe_bot/node_modules/wechaty-puppet-padplus/dist/src/padplus-manager/api-request/message.js:5:58)
(node:27090) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2187)
```
If wechaty do any scheme for the service high available ? It's very important.
