### ISSUE TITLE
Wechaty Gateway Server: Assertion failed

### ISSUE THREAD

**Issue by inkpool** [wechaty/wechaty#2008]
## 1. Versions
- What is your wechaty version?
Answer: 0.4.14

- Which puppet are you using for wechaty? (padchat/puppeteer/padpro/...)
Answer: padplus_token (converted to donut token)
I got one donut token from the official merchant, but it is invalid after I switched the account. No new qrcode is forwarded, and my puppet hangs. (It might be another bug, but I am now hosting my own gateway server.)

- What is your wechaty-puppet-XXX（padchat/puppeteer/） version?
Answer: wechaty-puppet-hostie 0.2.2

- What is your node version? (run `node --version`)
Answer: I am using docker image, so...

- What os are you using
Answer: Centos7 for gateway server, MacOS for dev

## 2. Describe the bug
This bug has been reported multiple times in the issues, but I did not see any reaction from the developers. I am reporting again to draw more attention and hopefully, I could get some suggestions from the official developers.

I have tried to update all the libraries to the latest version including the gateway docker image.

## 3. To Reproduce
https://github.com/wechaty/wechaty/issues/1988#issuecomment-635915025
Exactly the same steps here.

## 4. Expected behavior
Gateway server should forward the messages to puppet. 

## 5. Actual behavior
The puppet side cannot get any message and it keeps reporting the same error as the gateway server.

## 6. Full Output Logs

VERB PuppetServiceImpl messagePayload()
00:04:58 VERB Puppet messagePayload(9144104376834225040)
Error [AssertionError]: Assertion failed
    at new goog.asserts.AssertionError (/wechaty/node_modules/google-protobuf/google-protobuf.js:81:876)
    at Object.goog.asserts.doAssertFailure_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:82:257)
    at Object.goog.asserts.assert [as assert] (/wechaty/node_modules/google-protobuf/google-protobuf.js:83:83)
    at jspb.BinaryEncoder.writeUnsignedVarint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:458:77)
    at jspb.BinaryWriter.writeUnsignedVarint64_ (/wechaty/node_modules/google-protobuf/google-protobuf.js:480:507)
    at jspb.BinaryWriter.writeUint64 (/wechaty/node_modules/google-protobuf/google-protobuf.js:485:471)
    at Function.proto.wechaty.puppet.MessagePayloadResponse.serializeBinaryToWriter (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:849:12)
    at proto.wechaty.puppet.MessagePayloadResponse.serializeBinary (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet/message_pb.js:812:47)
    at serialize_wechaty_puppet_MessagePayloadResponse (/wechaty/node_modules/@chatie/grpc/dist/generated/wechaty/puppet_grpc_pb.js:460:26)
    at sendUnaryResponse (/wechaty/node_modules/grpc/src/server.js:98:15)
    at sendUnaryData (/wechaty/node_modules/grpc/src/server.js:600:9)
    at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-hostie/src/server/puppet-implementation.ts:529:16)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/node_modules/wechaty-puppet-hostie/dist/src/server/puppet-implementation.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  reportErrorToServer: true,
  messagePattern: 'Assertion failed',
  code: 13

## 7. Additional context
I got this error every time when the gateway server receives one message.

[bug]

**Comment by jcai** [comment]
@inkpool you can try

```
docker run -e "WECHATY_PUPPET_PADPLUS_TOKEN=puppet_padplus_xxxxxxxxxxx" 
    docker.pkg.github.com/wechaty/scala-wechaty/ding-dong-bot:0.0.16-SNAPSHOT
```
