### ISSUE TITLE
企业微信发消息给普通微信号机器人无响应

### ISSUE THREAD

**Issue by Bbingbing** [wechaty/wechaty#2013]
机器人使用的协议  wechaty-puppet-padplus
普通微信号之间通讯收发消息都正常,但是用企业微信给普通微信号机器人发消息时无响应,得到timeout的结果
Error: get contact timeout
at Timeout._onTimeout (/xx/wechaty-puppet-padplus/dist/src/padplus-manager/padplus-manager.js:1014:57)
at listOnTimeout (internal/timers.js:549:17)
at processTimers (internal/timers.js:492:7)
麻烦有空回答下是不支持企业微信还是我这边的问题呢

**Comment by huan** [comment]
`wechaty-puppet-padplus` does not support to send/receive WXWork messages.

You can consider using the `donut` windows protocol instead, it can send & receive the WXWork messages.

**Comment by Bbingbing** [comment]
@huan  got it, thank you!
