### ISSUE TITLE
Cannot read property 'roomId' of undefined 偶发报错

### ISSUE THREAD

**Issue by J-Boss-Os** [wechaty/wechaty#2117]
(node:21124) UnhandledPromiseRejectionWarning: Error: 13 INTERNAL: Cannot read property 'roomId' of undefined
    at Object.exports.createStatusError (D:\czy\git_more\wechaty-bot\node_modules\grpc\src\common.js:91:15)
    at Object.onReceiveStatus (D:\czy\git_more\wechaty-bot\node_modules\grpc\src\client_interceptors.js:1209:28)
    at InterceptingListener._callNext (D:\czy\git_more\wechaty-bot\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (D:\czy\git_more\wechaty-bot\node_modules\grpc\src\client_interceptors.js:618:8)
    at callback (D:\czy\git_more\wechaty-bot\node_modules\grpc\src\client_interceptors.js:847:24)
(node:21124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

刚开始的是，可以正常调用，但是在几次自动回复后，就跑错找不到roomId,但是继续调用，又有机会能正常使用，感觉很奇怪，不知道那里有问题

**Comment by J-Boss-Os** [comment]
![image](https://user-images.githubusercontent.com/59732535/104680819-bcf03080-572b-11eb-8e11-ff9b1ee1fdbb.png)

**Comment by huan** [comment]
Which Wechaty Puppet Service are you using? 

<https://wechaty.js.org/docs/puppet-services/>
