### ISSUE TITLE
运行出错，代码如下

### ISSUE THREAD

**Issue by hugle-rep** [wechaty/wechaty#2143]
import { Wechaty } from 'wechaty'
import { ScanStatus } from 'wechaty-puppet'
import QrcodeTerminal from 'qrcode-terminal';

const token = 'puppet_donut_******'

const bot = new Wechaty({
  puppet: 'wechaty-puppet-hostie',
  puppetOptions: {
    token,
  }
});

bot
  .on('scan', (qrcode, status) => {
    if (status === ScanStatus.Waiting) {
      QrcodeTerminal.generate(qrcode, {
        small: true
      })
    }
  })
  .on('login', async user => {
    console.log(`user: ${JSON.stringify(user)}`)
  })
  .on('message', async message => {
    console.log(`message: ${JSON.stringify(message)}`)
  })
  .start()

**Comment by HG-Group** [comment]
以下是返回的错误
D:\my-padplus-bot>ts-node bot.ts
16:44:33 ERR PuppetHostie startGrpcStream() connection failed and max retries has been reached. Error:
Error: Expected argument of type wechaty.puppet.EventRequest
    at serialize_wechaty_puppet_EventRequest (D:\my-padplus-bot\node_modules\wechaty\node_modules\@chatie\grpc\dist\generated\wechaty\puppet_grpc_pb.js:294:11)
    at Object.final_requester.sendMessage (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client_interceptors.js:1037:21)
    at InterceptingCall._callNext (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client_interceptors.js:419:43)
    at InterceptingCall.sendMessage (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client_interceptors.js:464:8)
    at InterceptingCall._callNext (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client_interceptors.js:428:12)
    at InterceptingCall.sendMessage (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client_interceptors.js:464:8)
    at ServiceClient.Client.makeServerStreamRequest (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client.js:770:21)
    at ServiceClient.method_func [as event] (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client.js:1003:43)
    at PuppetHostie.startGrpcStream (D:\my-padplus-bot\node_modules\wechaty\node_modules\wechaty-puppet-hostie\src\client\puppet-hostie.ts:379:45)
    at PuppetHostie.start (D:\my-padplus-bot\node_modules\wechaty\node_modules\wechaty-puppet-hostie\src\client\puppet-hostie.ts:284:7)
    at Wechaty.start (D:\my-padplus-bot\node_modules\wechaty\src\wechaty.ts:691:7)
16:44:47 ERR PuppetHostie startGrpcStream() connection failed and max retries has been reached. Error:
Error: Expected argument of type wechaty.puppet.EventRequest
    at serialize_wechaty_puppet_EventRequest (D:\my-padplus-bot\node_modules\wechaty\node_modules\@chatie\grpc\dist\generated\wechaty\puppet_grpc_pb.js:294:11)
    at Object.final_requester.sendMessage (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client_interceptors.js:1037:21)
    at InterceptingCall._callNext (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client_interceptors.js:419:43)
    at InterceptingCall.sendMessage (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client_interceptors.js:464:8)
    at InterceptingCall._callNext (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client_interceptors.js:428:12)
    at InterceptingCall.sendMessage (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client_interceptors.js:464:8)
    at ServiceClient.Client.makeServerStreamRequest (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client.js:770:21)
    at ServiceClient.method_func [as event] (D:\my-padplus-bot\node_modules\wechaty\node_modules\grpc\src\client.js:1003:43)
    at PuppetHostie.startGrpcStream (D:\my-padplus-bot\node_modules\wechaty\node_modules\wechaty-puppet-hostie\src\client\puppet-hostie.ts:379:45)
    at PuppetHostie.start (D:\my-padplus-bot\node_modules\wechaty\node_modules\wechaty-puppet-hostie\src\client\puppet-hostie.ts:284:7)

**Comment by su-chang** [comment]
提供token 联系JuziBot哈

**Comment by HG-Group** [comment]
已经发给JuziBot了

**Comment by HG-Group** [comment]
还是不能用啊，怎么回事

**Comment by HG-Group** [comment]
大佬们，解决一下ERR PuppetHostie startGrpcStream() connection failed and max retries has been reached.吧...

**Comment by huan** [comment]
Please read <https://wechaty.js.org/2021/01/14/wechaty-puppet-service/>

`curl https://api.chatie.io/v0/hosties/${WECHATY_TOKEN}`

>  ✅ If you get an HTTP/200 response with a JSON object body that includes your ip and port, then you are all set.  
> ❌ If you get an HTTP/404 response, your Puppet Service Gateway has some issues and needs to be troubleshooting.
