### ISSUE TITLE
Failed to load gRPC binary module . When run ding-dong-bot.js with wechaty/wechaty Docker

### ISSUE THREAD

**Issue by atubo2012** [wechaty/wechaty#2145]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer: **wechaty@0.56.6**

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer:padlocal

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer:  **wechaty-puppet-padlocal version: 0.2.29**   **padlocal-ts-client version: 0.2.22**

> What is your node version? (run `node --version`)

Answer: Starting Docker Container for Wechaty v0.56.6 with **Node.js v12.20.1** ...

> What os are you using

Answer: run dockerdesktop in windows 10 professional

## 2. Describe the bug

> Give a clear and concise description of what the bug is.

启动docker运行 examples/ding-dong-bot.js时，报错提示 ERR Config uncaughtException: Error: Failed to load gRPC binary module because it was not installed for the current system

![image](https://user-images.githubusercontent.com/30145089/109406442-22cf0980-79b4-11eb-9978-1b775b4e8269.png)

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

```
d:
cd workspace/wechaty/wechaty-getting-started
set WECHATY_LOG=verbose
set WECHATY_PUPPET=wechaty-puppet-padlocal
set WECHATY_PUPPET_PADLOCAL_TOKEN=puppet_padlocal_XXXXXX
set WECHATY_PUPPET_SERVER_PORT=8788
set WECHATY_TOKEN="b7cdad14-e44c-4c75-a78a-a21c7b5c93e4"

docker run -ti --name wechaty_gateway --rm   --volume="d:/workspace/wechaty/wechaty-getting-started:/bot" 
-e WECHATY_LOG 
-e WECHATY_PUPPET 
-e WECHATY_PUPPET_PADLOCAL_TOKEN 
-e WECHATY_PUPPET_SERVER_PORT 
-e WECHATY_TOKEN 
-p %WECHATY_PUPPET_SERVER_PORT%:%WECHATY_PUPPET_SERVER_PORT% 
wechaty/wechaty examples/ding-dong-bot.js
```
## 4. Expected behavior

> Give a clear and concise description of what you expected to happen.

Nomarlly start and send  'dong' to peer when recieving msg 'ding'

## 5. Actual behavior

> If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.
![image](https://user-images.githubusercontent.com/30145089/109406493-9244f900-79b4-11eb-81b8-fc575a55674d.png)

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

-> PASTE YOUR FULL(DO NOT ONLY PROVIDE FRAGMENTS) LOG MESSAGES HERE
02:40:45 INFO Config registering process.on("unhandledRejection") for development/debug
02:40:45 VERB Config constructor()
02:40:51 ERR Config ###########################
02:40:51 ERR Config uncaughtException: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v72-linux-x64-glibc
Found: [node-v83-win32-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/bot/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node'
Require stack:
- /bot/node_modules/grpc/src/grpc_extension.js
- /bot/node_modules/grpc/src/client_interceptors.js
- /bot/node_modules/grpc/src/client.js
- /bot/node_modules/grpc/index.js
- /bot/node_modules/wechaty-puppet-service/dist/src/client/puppet-service.js
- /bot/node_modules/wechaty-puppet-service/dist/src/mod.js
- /bot/node_modules/wechaty/dist/src/io-client.js
- /bot/node_modules/wechaty/dist/src/mod.js
- /bot/examples/ding-dong-bot.ts
    at Object.<anonymous> (/bot/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/grpc/src/client_interceptors.js:144:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/grpc/src/client.js:35:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/grpc/index.js:27:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/wechaty-puppet-service/src/mod.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/wechaty/src/io-client.ts:26:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/wechaty/src/mod.ts:66:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/examples/ding-dong-bot.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/bot/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/bot/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at main (/bot/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/bot/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 uncaughtException
02:40:51 ERR Config ###########################
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v72-linux-x64-glibc
Found: [node-v83-win32-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/bot/node_modules/grpc/src/node/extension_binary/node-v72-linux-x64-glibc/grpc_node.node'
Require stack:
- /bot/node_modules/grpc/src/grpc_extension.js
- /bot/node_modules/grpc/src/client_interceptors.js
- /bot/node_modules/grpc/src/client.js
- /bot/node_modules/grpc/index.js
- /bot/node_modules/wechaty-puppet-service/dist/src/client/puppet-service.js
- /bot/node_modules/wechaty-puppet-service/dist/src/mod.js
- /bot/node_modules/wechaty/dist/src/io-client.js
- /bot/node_modules/wechaty/dist/src/mod.js
- /bot/examples/ding-dong-bot.ts
    at Object.<anonymous> (/bot/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/grpc/src/client_interceptors.js:144:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/grpc/src/client.js:35:27)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/grpc/index.js:27:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/wechaty-puppet-service/src/client/puppet-service.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/wechaty-puppet-service/src/mod.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/wechaty/src/io-client.ts:26:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/node_modules/wechaty/src/mod.ts:66:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/bot/examples/ding-dong-bot.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module.m._compile (/bot/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/bot/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at main (/bot/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/bot/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wechaty-getting-started@0.8.10 start: `ts-node examples/ding-dong-bot.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wechaty-getting-started@0.8.10 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-28T02_40_52_630Z-debug.log
```

</details>

## 7. Additional context

> Add any other context about the problem here.

**Comment by huan** [comment]
Thank you very much for reporting this issue, and it's great to have reproducible steps includes, which I believe can help your problem to be quick solved.

In the docker, we are a Linux environment. And according to the information you provided, you are using Windows.

So it is very important to realize that, you can not run Windows binaries under Linux. Unfortunately, the `grpc` module is not pure JavaScript but a C binding module, which means that it will not work in Docker if you install it under Windows.

To solve your problem, my suggestion will be to run `npx shx rm -frv node_modules` under Windows, and restart the docker again:

```sh
npx shx rm -frv node_modules

docker run -ti --name wechaty_gateway --rm   --volume="d:/workspace/wechaty/wechaty-getting-started:/bot" 
-e WECHATY_LOG 
-e WECHATY_PUPPET 
-e WECHATY_PUPPET_PADLOCAL_TOKEN 
-e WECHATY_PUPPET_SERVER_PORT 
-e WECHATY_TOKEN 
-p %WECHATY_PUPPET_SERVER_PORT%:%WECHATY_PUPPET_SERVER_PORT% 
wechaty/wechaty examples/ding-dong-bot.js
```

If it works for you, please let me know and it will great if you want to share your experiences for using Wechaty under Windows because we have very limit blogs/docs about the Windows system.

And just FYI, we have a plan to move all dependencies to pure JavaScript in the future, like https://github.com/wechaty/grpc/issues/114

**Comment by atubo2012** [comment]
it works after clean node_modules
Many thanks!

**Comment by huan** [comment]
Glad to know that it works for you after the clean up, and your are welcome!
