### ISSUE TITLE
[LongLink] socket Killed

### ISSUE THREAD

**Issue by why2lyj** [wechaty/wechaty#2157]
I'm using Python with Padlocal and based the doc https://github.com/wechaty/wechaty/discussions/1985 setup my chatbot.
but  I always got issue as followed after I logined in and chatbot will be shutdown. 

Can anyone give me  a suggestion?

```shell
02:50:21 VERB [LongLink] [e2fd82601bd246799f3494229b2eb8b1] socket recv:17f103002424f5806f21f6de1de4cfa208eb9e3543bb34fa27f282942e679c7346c7bcfcf13394c8e5
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! wechaty@0.56.6 io-client: `ts-node bin/io-client`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the wechaty@0.56.6 io-client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /bot/.npm/_logs/2021-03-19T02_50_34_188Z-debug.log
```

**Comment by why2lyj** [comment]
/bot/.npm/_logs/2021-03-19T02_50_34_188Z-debug.log

```shell
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'io-client' ]
2 info using npm@6.14.10
3 info using node@v12.20.1
4 verbose run-script [ 'preio-client', 'io-client', 'postio-client' ]
5 info lifecycle wechaty@0.56.6~preio-client: wechaty@0.56.6
6 info lifecycle wechaty@0.56.6~io-client: wechaty@0.56.6
7 verbose lifecycle wechaty@0.56.6~io-client: unsafe-perm in lifecycle true
8 verbose lifecycle wechaty@0.56.6~io-client: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/wechaty/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/wechaty/bin:/wechaty/node_modules/.bin
9 verbose lifecycle wechaty@0.56.6~io-client: CWD: /wechaty
10 silly lifecycle wechaty@0.56.6~io-client: Args: [ '-c', 'ts-node bin/io-client' ]
11 silly lifecycle wechaty@0.56.6~io-client: Returned: code: 137  signal: null
12 info lifecycle wechaty@0.56.6~io-client: Failed to exec io-client script
13 verbose stack Error: wechaty@0.56.6 io-client: `ts-node bin/io-client`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid wechaty@0.56.6
15 verbose cwd /wechaty
16 verbose Linux 3.10.0-514.26.2.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "io-client"
18 verbose node v12.20.1
19 verbose npm  v6.14.10
20 error code ELIFECYCLE
21 error errno 137
22 error wechaty@0.56.6 io-client: `ts-node bin/io-client`
22 error Exit status 137
23 error Failed at the wechaty@0.56.6 io-client script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```
