### ISSUE TITLE
ERR Room create() exception: Error: This class can not be used directory

### ISSUE THREAD

**Issue by Xu213** [wechaty/wechaty#2177]
### code:
```
export const preAnswerHook = async (message: Message, answer: AIBotRequestResponse, sentiment?: SentimentData | undefined) => {
    const hate = sentiment?.hate
    const angry = sentiment?.angry
    const score = (hate || 0) + (angry || 0)
    console.log(sentiment || '空的sentiment')
    if (score > 0.9) {
        const boss = await getContact(BossID)
        const my = await getContact(LoginID)
        const from = message?.talker()
        console.log(my)
        console.log(boss)
        console.log(from)

        const room = await Room.create([boss, from])
        await new Promise(r => setTimeout(r, 3000))
        await room.say`${boss}，你帮帮我吧，${from}和我聊天已经聊得不耐烦了`
        return false

    }
}
```
### error:
```
18:08:32 ERR Room create() exception: Error: This class can not be used directory. See: https://github.com/wechaty/wechaty/issues/2027
    at Function.get wechaty [as wechaty] (C:\Users\Xu\Desktop\bots\node_modules\_wechaty@0.60.4@wechaty\src\user\room.ts:62:43)
    at Function.create (C:\Users\Xu\Desktop\bots\node_modules\_wechaty@0.60.4@wechaty\src\user\room.ts:99:33)
    at Object.preAnswerHook (C:\Users\Xu\Desktop\bots\preAnswerHook.ts:25:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:11676) UnhandledPromiseRejectionWarning: Error: This class can not be used directory. See: https://github.com/wechaty/wechaty/issues/2027
    at Function.get wechaty [as wechaty] (C:\Users\Xu\Desktop\bots\node_modules\_wechaty@0.60.4@wechaty\src\user\room.ts:62:43)
    at Function.create (C:\Users\Xu\Desktop\bots\node_modules\_wechaty@0.60.4@wechaty\src\user\room.ts:99:33)
    at Object.preAnswerHook (C:\Users\Xu\Desktop\bots\preAnswerHook.ts:25:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11676) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11676) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Xu213** [comment]
code:
```
if (score > 0.9) {
        // const boss = await getContact(BossID)
        // const my = await getContact(LoginID)
        const boss = await bot.Contact.find({ id: BossID })
        const my =await bot.Contact.find({ id: LoginID })
        const from = await bot.Contact.find({ id: message?.talker().id })
        console.log(my)
        console.log(boss)
        console.log(from)
        try {
            const contactList = [boss, from]
            console.log('Bot', 'contactList: ', contactList.join(','))
            const room = await bot.Room.create(contactList as Contact[], 'ding')
            console.log('Bot', 'createDingRoom() new ding room created: %s', room)
            // const room = await bot.Room.create([boss||'', from||''])
            await new Promise(r => setTimeout(r, 3000))
            await room.say`${boss}，你帮帮我吧，${from}和我聊天已经聊得不耐烦了`

        } catch (e) {
            console.log(e)
        }
        return false
}
```

console:
```
Bot contactList:  Contact<AC>,Contact<AC>
18:55:33 ERR PuppetWeChatBridge roomCreate(@d69ab69f2bb4b77e65c1613263e21da9b351b29c16b77bc12653141119e5258a,@d69ab69f2bb4b77e65c1613263e21da9b351b29c16b77bc12653141119e5258a) exception: undefined
18:55:33 WARN PuppetWeChat roomCreate(@d69ab69f2bb4b77e65c1613263e21da9b351b29c16b77bc12653141119e5258a,@d69ab69f2bb4b77e65c1613263e21da9b351b29c16b77bc12653141119e5258a, ding) rejected: undefined
18:55:33 ERR Room create() exception: [object Object]
{
  BaseResponse: {},
  Topic: '',
  PYInitial: '',
  QuanPin: '',
  MemberCount: 0,
  MemberList: [],
  ChatRoomName: '',
  BlackList: ''
}
```

**Comment by smwsk** [comment]
我和你有同样的问题，请问你有没有解决了，我也是Room create() exception
