### ISSUE TITLE
Dead when calling reset()

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#2197]
## The Problem

In our `wechaty.reset()`, when there's an internal exception, the Wechaty will emit an `error` and then the reset operation will fail, which will cause the bot dead forever.

The related log:

```
09:19:42 ERR PuppetService start() rejection: ETIMEOUT
09:19:42 VERB StateSwitch <PuppetService> off(true) <- (false)
09:19:42 WARN Puppet reset() exception: Error: ETIMEOUT
09:19:42 INFO WechatyPluginContrib EventLogger error: Error
09:19:42 ERR on-error onError(Error)
Error
    at PuppetService.<anonymous> (/home/friday/git/friday/node_modules/wechaty/dist/src/wechaty.js:272:44)
    at PuppetService.emit (events.js:376:20)
    at PuppetService.emit (domain.js:470:12)
    at /home/friday/git/friday/node_modules/wechaty-puppet/dist/src/puppet.js:215:18
```

<details>

<summary>Click for full log</summary>

```
00:12:53 VERB WechatyPluginContrib messageMatcher() matchMessage(Message#Text[🗣Contact<OSS.Chat>@👥Room<ChatOps - Heartbeat W 💖>]      [太阳])
00:12:53 VERB Puppet selfId()
00:12:53 VERB Message mentionList()
00:12:53 VERB Puppet selfId()
00:12:53 VERB Message mentionList()
00:12:53 VERB WechatyPluginContrib stringMatcher() matchString([太阳])
00:12:54 VERB PuppetService startGrpcStream() eventStream.on(error) Error: 14 UNAVAILABLE: Connection dropped
00:12:54 VERB Puppet reset(startGrpcStream() eventStream.on(error) Error: 14 UNAVAILABLE: Connection dropped)
00:12:54 VERB PuppetService startGrpcStream() eventStream.on(end)
00:12:54 VERB PuppetService stop()
00:12:54 VERB StateSwitch <PuppetService> off(pending) <- (false)
00:12:54 VERB PuppetService stopGrpcStream()
00:12:55 ERR PuppetService stop() stop GRPC rejection: 14 UNAVAILABLE: No connection established
00:12:55 VERB Puppet selfId()
00:12:55 VERB StateSwitch <PuppetService> off(true) <- (pending)
00:12:55 INFO WechatyPluginContrib EventLogger logout: Contact<Friday BOT>,PuppetService stop()
00:12:55 VERB WechatyPluginContrib Heartbeat sayEmoji(logout)
00:12:55 INFO RestartReporter startFinis() bot Contact<Friday BOT> logout
00:12:55 INFO on-logout onLogout(Contact<Friday BOT>)
00:12:55 VERB ContactSelf name()
00:12:55 INFO IoClient Friday BOT logged out
00:12:55 VERB PuppetService start()
00:12:55 VERB StateSwitch <PuppetService> on(pending) <- (false)
00:12:55 VERB PuppetService startGrpcClient()
00:12:55 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:12:55 WARN No endpoint when starting grpc client, 10 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 2 }
00:12:59 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
00:12:59 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 2 }
00:13:05 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:13:05 WARN No endpoint when starting grpc client, 9 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 2 }
metrics { mo: 0, mt: 2 }
00:13:15 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:13:15 WARN No endpoint when starting grpc client, 8 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 2 }
00:13:19 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
00:13:19 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 2 }
00:13:25 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:13:25 WARN No endpoint when starting grpc client, 7 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 2 }
metrics { mo: 0, mt: 2 }
00:13:35 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:13:35 WARN No endpoint when starting grpc client, 6 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 2 }
00:13:39 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
00:13:39 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 2 }
00:13:45 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:13:45 WARN No endpoint when starting grpc client, 5 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 2 }
metrics { mo: 0, mt: 2 }
00:13:55 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:13:55 WARN No endpoint when starting grpc client, 4 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 2 }
00:13:59 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
00:13:59 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 2 }
00:14:05 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:14:05 WARN No endpoint when starting grpc client, 3 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 2 }
00:14:09 VERB status-page/updater startUpdater/setInterval mo/mt: 0/2
00:14:09 VERB Room findAll({"topic":{}})
00:14:09 VERB Puppet roomSearch({"topic":{}})
00:14:09 VERB PuppetService roomList()
00:14:09 VERB Room findAll() rejected: Cannot read property 'roomList' of undefined
TypeError: Cannot read property 'roomList' of undefined
    at PuppetService.roomList (/home/friday/git/friday/node_modules/wechaty-puppet-service/dist/src/client/puppet-service.js:702:73)
    at PuppetService.roomSearch (/home/friday/git/friday/node_modules/wechaty-puppet/dist/src/puppet.js:671:42)
    at Function.findAll (/home/friday/git/friday/node_modules/wechaty/dist/src/user/room.js:117:58)
    at Object.countRoomMembers (/home/friday/git/friday/dist/src/status-page/count-room-members.js:11:45)
    at Timeout._onTimeout (/home/friday/git/friday/dist/src/status-page/updater.js:43:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
00:14:09 ERR Config ###########################
00:14:09 ERR Config unhandledRejection: Error: friday.Room return 0 members
    at Object.countRoomMembers (/home/friday/git/friday/dist/src/status-page/count-room-members.js:18:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Timeout._onTimeout (/home/friday/git/friday/dist/src/status-page/updater.js:43:31) [object Promise]
00:14:09 ERR Config ###########################
00:14:09 ERR Config process.on(unhandledRejection) promise.catch(friday.Room return 0 members)
Config Error: friday.Room return 0 members
    at Object.countRoomMembers (/home/friday/git/friday/dist/src/status-page/count-room-members.js:18:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Timeout._onTimeout (/home/friday/git/friday/dist/src/status-page/updater.js:43:31)
(node:139144) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 257)
metrics { mo: 0, mt: 0 }
00:14:15 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:14:15 WARN No endpoint when starting grpc client, 2 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 0 }
00:14:19 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
00:14:19 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 0 }
00:14:25 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:14:25 WARN No endpoint when starting grpc client, 1 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
00:14:35 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:14:35 WARN PuppetService start() failed to start grpc client, resetting self...
00:14:35 VERB Puppet reset(failed to connect grpc client)
00:14:35 VERB PuppetService stop()
00:14:35 VERB StateSwitch <PuppetService> off(pending) <- (false)
00:14:35 WARN PuppetService stop() this.grpcClient not exist
00:14:35 VERB StateSwitch <PuppetService> off(true) <- (pending)
00:14:35 VERB PuppetService start()
00:14:35 VERB StateSwitch <PuppetService> on(pending) <- (false)
00:14:35 VERB PuppetService startGrpcClient()
00:14:35 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:14:35 WARN No endpoint when starting grpc client, 10 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 0 }
00:14:39 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
00:14:39 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 0 }
00:14:45 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:14:45 WARN No endpoint when starting grpc client, 9 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
00:14:55 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:14:55 WARN No endpoint when starting grpc client, 8 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 0 }
00:14:59 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
00:14:59 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 0 }
00:15:05 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:15:05 WARN No endpoint when starting grpc client, 7 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
00:15:15 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:15:15 WARN No endpoint when starting grpc client, 6 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 0 }
00:15:19 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
00:15:19 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 0 }
00:15:25 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:15:25 WARN No endpoint when starting grpc client, 5 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
00:15:35 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
00:15:35 WARN No endpoint when starting grpc client, 4 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 0 }
00:15:39 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
00:15:39 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 0 }
00:15:45 VERB PuppetService discoverServiceIp(puppet_donut_XXX)

...

09:19:17 WARN No endpoint when starting grpc client, 3 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
09:19:24 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
09:19:24 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
09:19:27 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
09:19:27 WARN No endpoint when starting grpc client, 2 retry left. Reconnecting in 10 seconds...
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
09:19:37 VERB PuppetService discoverServiceIp(puppet_donut_XXX)
metrics { mo: 0, mt: 0 }
09:19:42 ERR PuppetService start() rejection: ETIMEOUT
09:19:42 VERB StateSwitch <PuppetService> off(true) <- (false)
09:19:42 WARN Puppet reset() exception: Error: ETIMEOUT
09:19:42 INFO WechatyPluginContrib EventLogger error: Error
09:19:42 ERR on-error onError(Error)
Error
    at PuppetService.<anonymous> (/home/friday/git/friday/node_modules/wechaty/dist/src/wechaty.js:272:44)
    at PuppetService.emit (events.js:376:20)
    at PuppetService.emit (domain.js:470:12)
    at /home/friday/git/friday/node_modules/wechaty-puppet/dist/src/puppet.js:215:18
Error
    at PuppetService.<anonymous> (/home/friday/git/friday/node_modules/wechaty/dist/src/wechaty.js:272:44)
    at PuppetService.emit (events.js:376:20)
    at PuppetService.emit (domain.js:470:12)
    at /home/friday/git/friday/node_modules/wechaty-puppet/dist/src/puppet.js:215:18
metrics { mo: 0, mt: 0 }
09:19:44 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
09:19:44 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
09:20:04 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
09:20:04 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
09:20:24 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]"}"})
09:20:24 INFO WechatyPluginContrib EventLogger heartbeat: [object Object]
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
metrics { mo: 0, mt: 0 }
```

</details>

## Solution

We should retry in the `reset()` method when there's any fail/exceptions internally.

**Comment by huan** [comment]
Workarounded.

There might be a race condition when resetting twice between our setTimeout.

To be fixed.

**Comment by j710328466** [comment]
@huan 
when i use wechaty-puppet-service, sometimes will happened, not everytime, here is the error log:

```js
00:25:10 ERR PuppetService start() rejection: ETIMEOUT

Error: ETIMEOUT
    at Timeout._onTimeout (/Users/admin/Documents/workspace/self/wechaty-demo/node_modules/_wechaty-puppet-service@0.23.4@wechaty-puppet-service/src/client/puppet-service.ts:187:24)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
Error: ETIMEOUT
    at Timeout._onTimeout (/Users/admin/Documents/workspace/self/wechaty-demo/node_modules/_wechaty-puppet-service@0.23.4@wechaty-puppet-service/src/client/puppet-service.ts:187:24)
```

**Comment by su-chang** [comment]
This error `ETIMEOUT` can not been caught in `discoverServiceIp()` method.

Maybe we should use `promise.catch()` for this error.

```ts
private async discoverServiceIp (
  token: string,
): Promise<{ ip?: string, port?: number }> {
  log.verbose('PuppetService', 'discoverServiceIp(%s)', token)

  const chatieEndpoint = GET_WECHATY_SERVICE_DISCOVERY_ENDPOINT()

  return Promise.race<
    Promise<{
      ip: string,
      port: number
    }>
  >([
    this.getServiceIp(chatieEndpoint, token),
    // eslint-disable-next-line promise/param-names
    new Promise((_, reject) => setTimeout(
      () => reject(new Error(`ETIMEOUT, can not get service ip and port for this ${token}`)),
      /**
       * Huan(202106): Better deal with the timeout error
       *  Related to https://github.com/wechaty/wechaty/issues/2197
       */
      5 * 1000,
    )),
  ]).catch(e => {
    log.warn(`discoverServiceIp() failed to get any ip info from all service endpoints.\n${e.stack}`)
    return {}
  })
}
```

**Comment by huan** [comment]
I'm refactoring the related code and I believe the ETIMEOUT error should be throw out and it should be catch outside of the wechaty.

Please try the next version of wechaty and read the related code, then I'd like to have more discussion based on that.

**Comment by hcfw007** [comment]
I tried to catch this error outside wechaty, but failed. Maybe it's my lack of understanding of throwing an error inside Promise.
Please try this:
```
function foo() {
  try {
    new Promise((_, reject) => {
      setTimeout(() => {
        reject(new Error('w/e'))
      }, 5000)
    })
  } catch (e) {
    console.log(e.message)
  }
}

try {
  foo()
} catch (e) {
  console.log(e.message)
}
```
The error cannot be caught by either of the catch. It can only be caught by Promise.catch.

**Comment by hcfw007** [comment]
According to my search, try/catch cannot deal with async codes. So a reacted Promise can only be handled by Promse.catch. (unless it's an awaited Promise)

**Comment by huan** [comment]
I believe all you need is to change `function foo()` to `async function foo()`
