### ISSUE TITLE
WARN PuppetWebBridge init() inject FINAL fail

### ISSUE THREAD

**Issue by programath** [wechaty/wechaty#22]
I met a problem when running the demo ding-dong bot on my mac.
Here is the console log

 ✘ programath@wentuopudeMaxBook-Air ⮀ ~/wechaty ⮀ ⭠ master ● ⮀ node example/ding-dong-bot.js

| __        __        _           _
| \ \      / /__  ___| |__   __ _| |_ _   _
|  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
|   \ V  V /  __/ (__| | | | (_| | |_| |_| |
|    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
|                                     |___/

=============== Powered by Wechaty ===============
-------- https://github.com/zixia/wechaty --------

I'm a bot, my super power is talk in Wechat.

If you send me a 'ding', I will reply you a 'dong'!
__________________________________________________

Hope you like it, and you are very welcome to
upgrade me for more super powers!

Please wait... I'm trying to login in...

info Wechaty v0.3.9 initializing...
undefined
WARN PuppetWebBridge init() inject FINAL fail: execute proxyWechaty(init) error: 503, init() without a ready angular env
ERR! PuppetWeb initBridge() exception: execute proxyWechaty(init) error: 503, init() without a ready angular env
ERR! PuppetWeb init exception: execute proxyWechaty(init) error: 503, init() without a ready angular env
ERR! Wechaty init() exception: execute proxyWechaty(init) error: 503, init() without a ready angular env
ERR! Bot Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
ERR! Bot     at Bridge.<anonymous> (/Users/programath/wechaty/src/puppet-web/bridge.js:84:15)
ERR! Bot     at next (native)
ERR! Bot     at onFulfilled (/Users/programath/wechaty/node_modules/co/index.js:65:19)
ERR! Bot     at ManagedPromise.invokeCallback_ (/Users/programath/wechaty/node_modules/selenium-webdriver/lib/promise.js:1315:14)
ERR! Bot     at TaskQueue.execute_ (/Users/programath/wechaty/node_modules/selenium-webdriver/lib/promise.js:2736:14)
ERR! Bot     at TaskQueue.executeNext_ (/Users/programath/wechaty/node_modules/selenium-webdriver/lib/promise.js:2719:21)
ERR! Bot     at asyncRun (/Users/programath/wechaty/node_modules/selenium-webdriver/lib/promise.js:2595:27)
ERR! Bot     at /Users/programath/wechaty/node_modules/selenium-webdriver/lib/promise.js:639:7
ERR! Bot     at process._tickCallback (internal/process/next_tick.js:103:7)
ERR! Bot  init() fail: %s Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
ERR! Bot     at Bridge.<anonymous> (/Users/programath/wechaty/src/puppet-web/bridge.js:84:15)
ERR! Bot     at next (native)
ERR! Bot     at onFulfilled (/Users/programath/wechaty/node_modules/co/index.js:65:19)
ERR! Bot     at ManagedPromise.invokeCallback_ (/Users/programath/wechaty/node_modules/selenium-webdriver/lib/promise.js:1315:14)
ERR! Bot     at TaskQueue.execute_ (/Users/programath/wechaty/node_modules/selenium-webdriver/lib/promise.js:2736:14)
ERR! Bot     at TaskQueue.executeNext_ (/Users/programath/wechaty/node_modules/selenium-webdriver/lib/promise.js:2719:21)
ERR! Bot     at asyncRun (/Users/programath/wechaty/node_modules/selenium-webdriver/lib/promise.js:2595:27)
ERR! Bot     at /Users/programath/wechaty/node_modules/selenium-webdriver/lib/promise.js:639:7
ERR! Bot     at process._tickCallback (internal/process/next_tick.js:103:7)

The version of node is v6.4.0 and npm is 3.10.3
Can you tell me what's going wrong?

**Comment by JasLin** [comment]
it looks like you are using the old source. see #21 .

**Comment by zixia** [comment]
@programath did you make wechaty work with `WECHATYA_HEAD=chrome` ? if you have any problem, please feel free to let me know if I could help.

**Comment by zixia** [comment]
hope you had already made it working as well.

**Comment by programath** [comment]
thx. I have just tried the latest version and it now works well.

**Comment by zixia** [comment]
haha, great. 

you are lucky, because I can't run it last weekend. shame. :P
