### ISSUE TITLE
wechaty logon problem after 7.15 certificate expire problem

### ISSUE THREAD

**Issue by dogwangz** [wechaty/wechaty#2208]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer:

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer:

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: we are using donut

> What is your node version? (run `node --version`)

Answer: v10.15.0

> What os are you using

Answer: CentOS

## 2. Describe the bug

> Give a clear and concise description of what the bug is.
After 7.15 certificate expire issue is fixed, we are facing a new problem. Wechaty throw  errors like belowed

11|app     | 2021-07-15 18:23:33.896: 18:23:33 WARN discoverHostieIp() failed to get any ip info from all hostie endpoints.
11|app     | Error: PuppetHostie discoverHostieIp() endpoint<https://chatieio.herokuapp.com/v0/hosties/puppet_donut_181e4c8f436a8250> rejection: Error: read ECONNRESET
11|app     |     at ClientRequest.<anonymous> (/home/ftpd/wechat-bot-linux/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:62:24)
11|app     |     at ClientRequest.emit (events.js:182:13)
11|app     |     at ClientRequest.EventEmitter.emit (domain.js:441:20)
11|app     |     at TLSSocket.socketErrorListener (_http_client.js:392:9)
11|app     |     at TLSSocket.emit (events.js:182:13)
11|app     |     at TLSSocket.EventEmitter.emit (domain.js:441:20)
11|app     |     at emitErrorNT (internal/streams/destroy.js:82:8)
11|app     |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
11|app     |     at process._tickCallback (internal/process/next_tick.js:63:19) 
11|app     | 2021-07-15 18:23:33.898: 18:23:33 WARN No endpoint when starting grpc client, 10 retry left. Reconnecting in 10 seconds... 
11|app     | 2021-07-15 18:23:34.117: SyntaxError: Unexpected token < in JSON at position 0
11|app     |     at JSON.parse (<anonymous>)
11|app     |     at IncomingMessage.<anonymous> (/home/ftpd/wechat-bot-linux/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:59:34)
11|app     |     at IncomingMessage.emit (events.js:187:15)
11|app     |     at IncomingMessage.EventEmitter.emit (domain.js:441:20)
11|app     |     at endReadableNT (_stream_readable.js:1094:12)
11|app     |     at process._tickCallback (internal/process/next_tick.js:63:19)
11|app     | 2021-07-15 18:23:34.161: SyntaxError: Unexpected token < in JSON at position 0
11|app     |     at JSON.parse (<anonymous>)
11|app     |     at IncomingMessage.<anonymous> (/home/ftpd/wechat-bot-linux/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:59:34)
11|app     |     at IncomingMessage.emit (events.js:187:15)
11|app     |     at IncomingMessage.EventEmitter.emit (domain.js:441:20)
11|app     |     at endReadableNT (_stream_readable.js:1094:12)
11|app     |     at process._tickCallback (internal/process/next_tick.js:63:19)
 

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

Since we did not make any changes today, and there are someone else in the we group also reporting this issue, we believe this is not only me who facing such problem. 

While this issue seems we cannot get correct puppet-hostie, so that JSON pares error comes....

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

1. run '...'
2. ...
3. ...

## 4. Expected behavior

> Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

> If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)
11|app     | 2021-07-15 18:23:33.896: 18:23:33 WARN discoverHostieIp() failed to get any ip info from all hostie endpoints.
11|app     | Error: PuppetHostie discoverHostieIp() endpoint<https://chatieio.herokuapp.com/v0/hosties/puppet_donut_181e4c8f436a8250> rejection: Error: read ECONNRESET
11|app     |     at ClientRequest.<anonymous> (/home/ftpd/wechat-bot-linux/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:62:24)
11|app     |     at ClientRequest.emit (events.js:182:13)
11|app     |     at ClientRequest.EventEmitter.emit (domain.js:441:20)
11|app     |     at TLSSocket.socketErrorListener (_http_client.js:392:9)
11|app     |     at TLSSocket.emit (events.js:182:13)
11|app     |     at TLSSocket.EventEmitter.emit (domain.js:441:20)
11|app     |     at emitErrorNT (internal/streams/destroy.js:82:8)
11|app     |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
11|app     |     at process._tickCallback (internal/process/next_tick.js:63:19) 
11|app     | 2021-07-15 18:23:33.898: 18:23:33 WARN No endpoint when starting grpc client, 10 retry left. Reconnecting in 10 seconds... 
11|app     | 2021-07-15 18:23:34.117: SyntaxError: Unexpected token < in JSON at position 0
11|app     |     at JSON.parse (<anonymous>)
11|app     |     at IncomingMessage.<anonymous> (/home/ftpd/wechat-bot-linux/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:59:34)
11|app     |     at IncomingMessage.emit (events.js:187:15)
11|app     |     at IncomingMessage.EventEmitter.emit (domain.js:441:20)
11|app     |     at endReadableNT (_stream_readable.js:1094:12)
11|app     |     at process._tickCallback (internal/process/next_tick.js:63:19)
11|app     | 2021-07-15 18:23:34.161: SyntaxError: Unexpected token < in JSON at position 0
11|app     |     at JSON.parse (<anonymous>)
11|app     |     at IncomingMessage.<anonymous> (/home/ftpd/wechat-bot-linux/node_modules/wechaty-puppet-hostie/dist/src/client/puppet-hostie.js:59:34)
11|app     |     at IncomingMessage.emit (events.js:187:15)
11|app     |     at IncomingMessage.EventEmitter.emit (domain.js:441:20)
11|app     |     at endReadableNT (_stream_readable.js:1094:12)
11|app     |     at process._tickCallback (internal/process/next_tick.js:63:19)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

-> PASTE YOUR FULL(DO NOT ONLY PROVIDE FRAGMENTS) LOG MESSAGES HERE

```

</details>

## 7. Additional context

> Add any other context about the problem here.

**Comment by dogwangz** [comment]
删除node_modules和package-lock.json文件
升级wechaty@0.62.3
重新安装其余依赖

启动wechaty时，puppet字段修改为：'wechaty-puppet-service'
