### ISSUE TITLE
When Docker runs the wechaty bot, chrome is not found

### ISSUE THREAD

**Issue by VFiee** [wechaty/wechaty#2240]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer:v0.68.1

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer:puppeteer(default actually)

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer:v0.24.6

> What is your node version? (run `node --version`)

Answer:v14.17.5

> What os are you using

Answer: macOs BigSur

## 2. Describe the bug

> Give a clear and concise description of what the bug is.

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

1. docker run -ti --rm --volume=$(pwd):/bot wechaty/wechaty src/index.ts
2. An error occurred

## 4. Expected behavior

> There are no errors and the program runs normally

## 5. Actual behavior

>![image](https://user-images.githubusercontent.com/42051272/131239196-ce3d7a6d-8973-4011-9db8-093bf77986e4.png)

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
docker run -ti --rm --volume=$(pwd):/bot wechaty/wechaty src/index.ts
 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.chatie.io
  ____                            _   _             
 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _ 
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/ 
  ____ _           _   ____        _       
 / ___| |__   __ _| |_| __ )  ___ | |_ ___ 
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
 \____|_| |_|\__,_|\__|____/ \___/ \__|___/
                                           
WECHATY Environment Variables: 1
WECHATY_DOCKER=1

Starting Docker Container for Wechaty v0.68.1 with Node.js v14.17.5 ...
Working directory: /bot
Please make sure you had installed all the NPM modules which is depended on your bot script.
Executing ts-node --type-check src/index.ts
05:05:07 ERR PuppetWeChatBridge start() exception: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005).
05:05:07 INFO WechatyPluginContrib EventLogger error: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005).
发生错误,请及时处理: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005).
    at PuppetWeChat.<anonymous> (/bot/node_modules/wechaty/src/wechaty.ts:443:32)
    at PuppetWeChat.emit (events.js:400:28)
    at PuppetWeChat.emit (domain.js:470:12)
    at Bridge.<anonymous> (/bot/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:314:52)
    at Bridge.emit (events.js:400:28)
    at Bridge.emit (domain.js:470:12)
    at Bridge.start (/bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:122:12)
    at async PuppetWeChat.initBridge (/bot/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:323:7)
    at async PuppetWeChat.start (/bot/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:165:21)
    at async Wechaty.start (/bot/node_modules/wechaty/src/wechaty.ts:729:7)
    at async run (/bot/src/index.ts:37:2)
05:05:07 ERR PuppetWeChat initBridge() exception: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005).
05:05:07 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
05:05:07 INFO WechatyPluginContrib EventLogger error: Error
发生错误,请及时处理: Error: 
    at PuppetWeChat.<anonymous> (/bot/node_modules/wechaty/src/wechaty.ts:443:32)
    at PuppetWeChat.emit (events.js:400:28)
    at PuppetWeChat.emit (domain.js:470:12)
    at PuppetWeChat.initBridge (/bot/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:329:12)
    at async PuppetWeChat.start (/bot/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:165:21)
    at async Wechaty.start (/bot/node_modules/wechaty/src/wechaty.ts:729:7)
    at async run (/bot/src/index.ts:37:2)
05:05:07 ERR PuppetWeChat start() exception: Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (848005).
05:05:07 INFO WechatyPluginContrib EventLogger error: Error
发生错误,请及时处理: Error: 
    at PuppetWeChat.<anonymous> (/bot/node_modules/wechaty/src/wechaty.ts:443:32)
    at PuppetWeChat.emit (events.js:400:28)
    at PuppetWeChat.emit (domain.js:470:12)
    at PuppetWeChat.start (/bot/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:202:12)
    at async Wechaty.start (/bot/node_modules/wechaty/src/wechaty.ts:729:7)
    at async run (/bot/src/index.ts:37:2)
05:05:07 ERR PuppetWeChat this.bridge.quit() exception: no page
Error: no page
    at Bridge.stop (/bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:388:13)
    at PuppetWeChat.stop (/bot/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:231:25)
    at PuppetWeChat.start (/bot/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:203:18)
    at async Wechaty.start (/bot/node_modules/wechaty/src/wechaty.ts:729:7)
    at async run (/bot/src/index.ts:37:2)
05:05:07 ERR Wechaty start() exception: no page
05:05:07 INFO WechatyPluginContrib EventLogger error: Error: no page
发生错误,请及时处理: Error: no page
    at Bridge.stop (/bot/node_modules/wechaty-puppet-wechat/src/bridge.ts:388:13)
    at PuppetWeChat.stop (/bot/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:231:25)
    at PuppetWeChat.start (/bot/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:203:18)
    at async Wechaty.start (/bot/node_modules/wechaty/src/wechaty.ts:729:7)
    at async run (/bot/src/index.ts:37:2)
05:05:07 WARN PuppetWeChat stop() is called on a OFF puppet. await ready(off) and return.

 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.chatie.io
  _____      _ _      ___   
 | ____|_  _(_) |_   / _ \  
 |  _| \ \/ / | __| | | | | 
 | |___ >  <| | |_  | |_| | 
 |_____/_/\_\_|\__|  \___/  
</summary>
</details>

## 7. Additional context

> Add any other context about the problem here.

**Comment by huan** [comment]
Please try the older version like v0.62. The currently latest version is in Beta stage and we are focusing on moving forward to ESM & Debian **bullseye**

**Comment by VFiee** [comment]
> Please try the older version like v0.62. The currently latest version is in Beta stage and we are focusing on moving forward to ESM & Debian **bullseye**

ok, I'll try later!
