### ISSUE TITLE
Page crashed error after a reply

### ISSUE THREAD

**Issue by Zhenyi-Wang** [wechaty/wechaty#2244]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer:0.69.35

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: wechaty-puppet-wechat

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: 0.28.4

> What is your node version? (run `node --version`)

Answer: 14.17.5

> What os are you using

Answer: Windows 10

## 2. Describe the bug

> Give a clear and concise description of what the bug is.

I initialized the project according to this instruction https://wechaty.js.org/2021/04/13/wechaty-uos-web/

It worked

Then I added a onMessage handler:
`function onMessage(message) {
	console.log(`Message: ${message}`)
}`

It also worked

But after I added one more line:
`message.say('hi')`

The program crashes every time after replying the text, with UnhandledPromiseRejectionWarning: Error: Page crashed!

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

1. create a new folder wct `mkdir wct`
2. enter the folder `cd wct`
3. init the project `npm init`
4. run `npm install qrcode-terminal --save`
5. run `npm install wechaty`
6. run `npm install wechaty-puppet-wechat --save`
7. run `set WECHATY_PUPPET=wechaty-puppet-wechat` (I'm on windows 10)
8. create index.js with following codes 
```
const { Wechaty } = require('wechaty');

const name = 'wechat-puppet-wechat';
let bot = '';
bot = new Wechaty({
  name, // generate xxxx.memory-card.json and save login data for the next login
});

//  二维码生成
function onScan(qrcode, status) {
  require('qrcode-terminal').generate(qrcode); // 在console端显示二维码
  const qrcodeImageUrl = [
    'https://wechaty.js.org/qrcode/',
    encodeURIComponent(qrcode),
  ].join('');
  console.log(qrcodeImageUrl);
}

// 登录
async function onLogin(user) {
  console.log(`贴心小助理${user}登录了`);
}

//登出
function onLogout(user) {
  console.log(`小助手${user} 已经登出`);
}

function onMessage(message) {
	console.log(`Message: ${message}`)
	message.say('hi')
}

bot.on('scan', onScan);
bot.on('login', onLogin);
bot.on('logout', onLogout);
bot.on('message', onMessage);
bot
  .start()
  .then(() => console.log('开始登陆微信'))
  .catch((e) => console.error(e));
```

9. run `node index.js`
10. scan qrcode
11. send any text to bot
12. crash after auto reply..

## 4. Expected behavior

Function without crashing
> Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

Crashed with error
> If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

-> PASTE YOUR FULL(DO NOT ONLY PROVIDE FRAGMENTS) LOG MESSAGES HERE
15:12:40 SILL Puppet Config: WECHATY_LOG set level to silly
15:12:40 INFO Config registering process.on("unhandledRejection") for development/debug
15:12:40 VERB Config constructor()
15:12:40 VERB Wechaty init() getRavenDsn() return undefined, skipped.
15:12:40 VERB wechaty-puppet-service monkeyPatchMetadataFromHttp2Headers()
15:12:40 VERB ResolverWechaty setup()
15:12:40 VERB Wechaty constructor()
15:12:40 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
15:12:40 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
15:12:40 VERB Wechaty on(scan, listener) registering... listenerCount: 0
15:12:40 VERB Wechaty on(login, listener) registering... listenerCount: 0
15:12:40 VERB Wechaty on(logout, listener) registering... listenerCount: 0
15:12:40 VERB Wechaty on(message, listener) registering... listenerCount: 0
15:12:40 VERB Wechaty <wechaty-puppet-wechat>(wechat-puppet-wechat) start() v0.69.35 is starting...
15:12:40 VERB Wechaty id: ckt5g8a510000skticv32cmu9
15:12:40 SILL StateSwitch <Wechaty> on() is false
15:12:40 SILL StateSwitch <WechatyReady> off() is true
15:12:40 VERB StateSwitch <WechatyReady> off(true) <- (true)
15:12:40 SILL StateSwitch <Wechaty> on() is false
15:12:40 VERB StateSwitch <Wechaty> on(pending) <- (false)
15:12:40 VERB MemoryCard constructor("wechat-puppet-wechat")
15:12:40 VERB MemoryCard getStorage() for storage type: N/A
15:12:40 VERB getStorage name: wechat-puppet-wechat, options: {"type":"file"}
15:12:40 VERB StorageFile constructor(wechat-puppet-wechat, ...)
15:12:40 VERB StorageBackend constructor(wechat-puppet-wechat, { type: file })
15:12:40 VERB MemoryCard load() from storage: StorageFile<D:\WorkSpaces\njs\wechaty\wechat-puppet-wechat.memory-card.json>
15:12:40 VERB StorageFile load() from D:\WorkSpaces\njs\wechaty\wechat-puppet-wechat.memory-card.json
15:12:40 VERB Wechaty initPuppet()
15:12:40 VERB MemoryCard multiplex(puppet)
15:12:40 VERB MemoryCard static multiplex(MemoryCard<wechat-puppet-wechat>, puppet)
15:12:40 VERB MemoryCard constructor({"name":"wechat-puppet-wechat","multiplex":{"name":"puppet","parent":{"options":{"name":"wechat-puppet-wechat"},"name":"wechat-puppet-wechat","payload":{"\rpuppet\nPUPPET_WECHAT":[{"name":"wxloadtime","value":"1630739472_expired","domain":".wx2.qq.com","path":"/","expires":1630782673,"size":28,"httpOnly":false,"secure":true,"session":false,"sameParty":false},{"name":"last_wxuin","value":"317656214","domain":"wx2.qq.com","path":"/","expires":1630912273,"size":19,"httpOnly":false,"secure":false,"session":false,"sameParty":false},{"name":"login_frequency","value":"1","domain":"wx2.qq.com","path":"/","expires":1630912273,"size":16,"httpOnly":false,"secure":false,"session":false,"sameParty":false},{"name":"webwx_data_ticket","value":"gSfnerQURj5lXs6SNZUHwosm","domain":".qq.com","path":"/","expires":1630782673,"size":41,"httpOnly":false,"secure":true,"session":false,"sameParty":false},{"name":"wxsid","value":"5kWMcgiRj7H3mMYD","domain":".wx2.qq.com","path":"/","expires":1630782673,"size":21,"httpOnly":false,"secure":true,"session":false,"sameParty":false},{"name":"MM_WX_SOUND_STATE","value":"1","domain":"wx2.qq.com","path":"/","expires":-1,"size":18,"httpOnly":false,"secure":false,"session":true,"sameParty":false},{"name":"wxuin","value":"317656214","domain":".wx2.qq.com","path":"/","expires":1630998673,"size":14,"httpOnly":false,"secure":true,"session":false,"sameParty":false},{"name":"webwx_auth_ticket","value":"CIsBEKufic0LGoABlqOXoFJJwILH6romFrP6sCeH1flbyqwvzdyWlSiB0oHmnt3sbUQymwpGhNAZoNuzW4hRN20KFeUpFirqtVQJAdq17QaUwv3UaixE3PL1G6tot77bNd7fkNgdYYrynowmPKRKzaIlVDqWbp59GjCQiNs7R5OvWSXVe9zA7R7DB20=","domain":".wx2.qq.com","path":"/","expires":1946099472,"size":205,"httpOnly":false,"secure":true,"session":false,"sameParty":false},{"name":"mm_lang","value":"en_US","domain":".wx2.qq.com","path":"/","expires":1630782672,"size":12,"httpOnly":false,"secure":true,"session":false,"sameParty":false},{"name":"webwxuvid","value":"af84dd3fbadc9d80307a5791ea29221064b1407160382c881fd4f460d8033870116f48c254d0622967899f652d211aa9","domain":".wx2.qq.com","path":"/","expires":1946098032,"size":105,"httpOnly":false,"secure":true,"session":false,"sameParty":false},{"name":"MM_WX_NOTIFY_STATE","value":"1","domain":"wx2.qq.com","path":"/","expires":-1,"size":19,"httpOnly":false,"secure":false,"session":true,"sameParty":false},{"name":"wxpluginkey","value":"1630735208","domain":".wx2.qq.com","path":"/","expires":1630782673,"size":21,"httpOnly":false,"secure":true,"session":false,"sameParty":false}]},"multiplexNameList":[],"storage":{"name":"wechat-puppet-wechat","options":{"type":"file"},"absFileName":"D:\\WorkSpaces\\njs\\wechaty\\wechat-puppet-wechat.memory-card.json"}}}})
15:12:40 VERB PuppetManager resolve({puppet: wechaty-puppet-wechat, puppetOptions: undefined})
15:12:40 VERB PuppetManager resolveName(wechaty-puppet-wechat)
15:12:40 VERB Puppet constructor({}) #0
15:12:40 VERB StateSwitch constructor(PuppetWeChat, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
15:12:40 VERB MemoryCard constructor(undefined)
15:12:40 VERB MemoryCard getStorage() for storage type: N/A
15:12:40 VERB MemoryCard load() from storage: N/A
15:12:40 VERB MemoryCard load() no storage
15:12:40 VERB Puppet constructor() watchdog timeout set to 60 seconds
15:12:40 VERB PuppetWeChatBridge constructor()
15:12:40 VERB StateSwitch constructor(name=PuppetWeChatBridge)
15:12:40 VERB PuppetWeChat initWatchdogForScan()
15:12:40 VERB Puppet setMemory()
15:12:40 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetWeChat>(wechat-puppet-wechat))
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) (listenerCount:0) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(login) (listenerCount:1) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(logout) (listenerCount:1) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(message) (listenerCount:0) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) (listenerCount:0) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) (listenerCount:0) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) (listenerCount:0) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) (listenerCount:0) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(scan) (listenerCount:1) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(dirty) (listenerCount:0) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(dong) (listenerCount:0) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(error) (listenerCount:0) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(heartbeat) (listenerCount:0) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(ready) (listenerCount:0) registering...
15:12:40 VERB Wechaty initPuppetEventBridge() puppet.on(reset) (listenerCount:0) registering...
15:12:40 VERB Wechaty wechatifyUserModules(Puppet#0<PuppetWeChat>(wechat-puppet-wechat))
15:12:40 VERB PuppetWeChat start() with wechat-puppet-wechat
15:12:40 SILL StateSwitch <PuppetWeChat> on() is false
15:12:40 SILL StateSwitch <PuppetWeChat> on() is false
15:12:40 VERB StateSwitch <PuppetWeChat> on(pending) <- (false)
15:12:40 VERB PuppetWeChat initBridge()
15:12:40 SILL StateSwitch <PuppetWeChat> off() is false
15:12:40 VERB PuppetWeChatBridge start()
15:12:40 SILL StateSwitch <PuppetWeChatBridge> on() is false
15:12:40 VERB StateSwitch <PuppetWeChatBridge> on(pending) <- (false)
15:12:40 VERB PuppetWeChatBridge initBrowser()
15:12:40 VERB PuppetWeChatBridge initBrowser() with options={"args":["--audio-output-channels=0","--disable-default-apps","--disable-translate","--disable-gpu","--disable-setuid-sandbox","--disable-sync","--hide-scrollbars","--mute-audio","--no-sandbox"],"headless":true}
15:12:41 VERB PuppetWeChatBridge initBrowser() version: HeadlessChrome/90.0.4403.0
15:12:41 VERB PuppetWeChatBridge start() initBrowser() done
15:12:41 VERB PuppetWeChatBridge initPage()
15:12:41 VERB MemoryCard <puppet> get(PUPPET_WECHAT)
15:12:41 VERB PuppetWeChatBridge cookieDomain([object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object])
15:12:41 SILL PuppetWeChatBridge cookieDomain() got https://wx2.qq.com
15:12:41 VERB PuppetWeChatBridge initPage() before page.goto(url)
15:12:42 VERB PuppetWeChatBridge initPage() after page.goto(url)
15:12:42 SILL PuppetWeChatBridge initPage() page.setCookie() 12 cookies set back
15:12:42 VERB PuppetWeChatBridge onLoad() page.url=https://wx2.qq.com/?target=t
15:12:42 SILL StateSwitch <PuppetWeChatBridge> off() is false
15:12:42 VERB PuppetWeChatBridge readyAngular()
15:12:42 VERB PuppetWeChatBridge inject()
15:12:42 SILL PuppetWeChatBridge inject() eval(Wechaty) return code[200] message[WechatyBro Inject Done]
15:12:42 SILL PuppetWeChatBridge proxyWechaty(init)
15:12:42 SILL PuppetWeChatEvent onLog(login(page refresh))
15:12:42 VERB PuppetWeChatEvent onLogin(page refresh, 30)
15:12:42 VERB PuppetWeChatBridge getUserName()
15:12:42 SILL PuppetWeChatBridge proxyWechaty(getUserName)
15:12:42 SILL PuppetWeChatEvent onLog(init() scanCode: null)
15:12:42 SILL PuppetWeChatEvent onLog(inited!. ;-D)
15:12:42 SILL PuppetWeChatBridge inject() Wechaty.init() return code[200] message[WechatyBro Init Succ]
15:12:42 VERB PuppetWeChatBridge ding(ding() OK!)
15:12:42 SILL PuppetWeChatBridge proxyWechaty(ding, ding() OK!)
15:12:42 VERB PuppetWeChatEvent onLogin() browser not fully loaded(ttl=30), retry later
15:12:42 SILL PuppetWeChatBridge evaluate()
15:12:42 SILL PuppetWeChatEvent onLog(recv ding)
15:12:42 SILL PuppetWeChatBridge inject() ding success
15:12:42 VERB PuppetWeChatBridge clickSwitchAccount()
15:12:42 SILL PuppetWeChatEvent onLogin() innerHTML:
    <canvas style="position:absolute;top:0;left:0;bottom:0;right:0;z-index:-1;width:100%;height:100%;" id="heroCanvas"></canvas>

    <!--[if lt IE 8]>
    <p class="browsehappy">
      你正在使用一个<strong>过时</strong>的浏览器。请<a class="link" href="http://browsehappy.com" target="_blank">升级 你的浏览器</a>以查看微信网页版。</p>
    </p>
    <![endif]-->

    <!--BEGIN login-->
    <!-- ngIf: false -->
    <!--END login-->
    <!--BEGIN main-->
    <div class="main">
        <div class="main_inner" ng-right-click="showC
15:12:42 SILL PuppetWeChatBridge clickSwitchAccount() button not found
15:12:42 SILL StateSwitch <PuppetWeChatBridge> on() is pending
15:12:42 VERB StateSwitch <PuppetWeChatBridge> on(true) <- (pending)
15:12:42 VERB PuppetWeChatBridge start() initPage() done
15:12:42 VERB PuppetWeChat initBridge() done
15:12:42 SILL StateSwitch <PuppetWeChat> on() is pending
15:12:42 VERB StateSwitch <PuppetWeChat> on(true) <- (pending)
15:12:42 VERB PuppetWeChat start() done
15:12:42 VERB Wechaty on(heartbeat, listener) registering... listenerCount: 0
15:12:42 SILL StateSwitch <Wechaty> on() is pending
15:12:42 VERB StateSwitch <Wechaty> on(true) <- (pending)
开始登陆微信
15:12:43 VERB PuppetWeChatEvent onLogin(page refresh, 29)
15:12:43 VERB PuppetWeChatBridge getUserName()
15:12:43 SILL PuppetWeChatBridge proxyWechaty(getUserName)
15:12:43 SILL PuppetWeChatEvent onLog(checkScan() - already login, no more check, and return(only))
15:12:43 SILL PuppetWeChatEvent bridge.getUserName: @4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77
15:12:43 SILL PuppetWeChatEvent onLogin() user @4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77 logined
15:12:43 VERB MemoryCard <puppet> set(PUPPET_WECHAT, [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object])
15:12:43 VERB MemoryCard <wechat-puppet-wechat> save() to StorageFile<D:\WorkSpaces\njs\wechaty\wechat-puppet-wechat.memory-card.json>
15:12:43 VERB StorageFile save() to D:\WorkSpaces\njs\wechaty\wechat-puppet-wechat.memory-card.json
15:12:43 VERB PuppetWeChat waitStable()
15:12:43 VERB Puppet login(@4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77)
15:12:43 VERB Contact load(@4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77) init pool
15:12:43 SILL Contact constructor(@4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77)
15:12:43 SILL Contact ready() @ Puppet#0<PuppetWeChat>(wechat-puppet-wechat) with id="@4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77"
15:12:43 SILL Puppet contactPayload(@4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77) cache MISS
15:12:43 SILL PuppetWeChat contactRawPayload(@4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77) @ Puppet#0<PuppetWeChat>(wechat-puppet-wechat)
15:12:43 SILL PuppetWeChatBridge getContact(@4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77) retry attempt 1
15:12:43 SILL PuppetWeChatBridge proxyWechaty(getContact, @4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77)
15:12:43 SILL PuppetWeChat contactParseRawPayload(Object.keys(payload).length=21)
15:12:43 SILL Puppet contactPayload(@4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77) cache SET
贴心小助理Contact<小王同学>登录了
15:12:44 SILL PuppetWeChatBridge proxyWechaty(contactList)
15:12:44 SILL PuppetWeChat readyStable() while() curNum=3, maxNum=3, unchangedNum=0
15:12:45 SILL PuppetWeChatBridge proxyWechaty(contactList)
15:12:45 SILL PuppetWeChat readyStable() while() curNum=3, maxNum=3, unchangedNum=1
15:12:46 SILL PuppetWeChatBridge proxyWechaty(contactList)
15:12:46 SILL PuppetWeChat readyStable() while() curNum=3, maxNum=3, unchangedNum=2
15:12:47 SILL PuppetWeChatBridge proxyWechaty(contactList)
15:12:47 SILL PuppetWeChat readyStable() while() curNum=3, maxNum=3, unchangedNum=3
15:12:47 VERB PuppetWeChat readyStable() emit(ready)
15:12:47 SILL Wechaty initPuppetEventBridge() puppet.on(ready)
15:12:47 SILL StateSwitch <WechatyReady> on() is false
15:12:47 VERB StateSwitch <WechatyReady> on(true) <- (false)
15:12:53 VERB Message static load(1560940061730277755)
15:12:53 VERB Message constructor(1560940061730277755) for class WechatifiedMessage
15:12:53 VERB Message ready()
15:12:53 VERB Puppet messagePayload(1560940061730277755)
15:12:53 SILL Puppet messagePayloadCache(1560940061730277755) cache MISS
15:12:53 SILL PuppetWeChatBridge getMessage(1560940061730277755) retry attempt 1
15:12:53 SILL PuppetWeChatBridge proxyWechaty(getMessage, 1560940061730277755)
15:12:54 VERB PuppetWeChat messageRawPayloadParser([object Object]) @ Puppet#0<PuppetWeChat>(wechat-puppet-wechat)
15:12:54 SILL Puppet messagePayload(1560940061730277755) cache SET
15:12:54 VERB Contact load(@a20259a44b886322318705474ed83bb6612cca272bcdfd698acbf9ba249b48f1) init pool
15:12:54 SILL Contact constructor(@a20259a44b886322318705474ed83bb6612cca272bcdfd698acbf9ba249b48f1)
15:12:54 SILL Contact ready() @ Puppet#0<PuppetWeChat>(wechat-puppet-wechat) with id="@a20259a44b886322318705474ed83bb6612cca272bcdfd698acbf9ba249b48f1"
15:12:54 SILL Puppet contactPayload(@a20259a44b886322318705474ed83bb6612cca272bcdfd698acbf9ba249b48f1) cache MISS
15:12:54 SILL PuppetWeChat contactRawPayload(@a20259a44b886322318705474ed83bb6612cca272bcdfd698acbf9ba249b48f1) @ Puppet#0<PuppetWeChat>(wechat-puppet-wechat)
15:12:54 SILL PuppetWeChatBridge getContact(@a20259a44b886322318705474ed83bb6612cca272bcdfd698acbf9ba249b48f1) retry attempt 1
15:12:54 SILL PuppetWeChatBridge proxyWechaty(getContact, @a20259a44b886322318705474ed83bb6612cca272bcdfd698acbf9ba249b48f1)
15:12:54 SILL PuppetWeChat contactParseRawPayload(Object.keys(payload).length=37)
15:12:54 SILL Puppet contactPayload(@a20259a44b886322318705474ed83bb6612cca272bcdfd698acbf9ba249b48f1) cache SET
15:12:54 SILL Contact constructor(@4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77)
15:12:54 SILL Contact ready() @ Puppet#0<PuppetWeChat>(wechat-puppet-wechat) with id="@4be37cf02f2942b5796ee545da565f839d072f145599384d6e0717178e05ed77"
15:12:54 VERB Puppet selfId()
Message: Message#Text[🗣Contact<James 王禛义>]   hello
15:12:54 VERB Message say(hi)
15:12:54 VERB Puppet selfId()
15:12:54 VERB Puppet selfId()
15:12:54 VERB Message mentionList()
15:12:54 VERB Puppet selfId()
15:12:54 VERB PuppetWeChat messageSendText(@a20259a44b886322318705474ed83bb6612cca272bcdfd698acbf9ba249b48f1, hi)
15:12:54 VERB PuppetWeChatBridge send(@a20259a44b886322318705474ed83bb6612cca272bcdfd698acbf9ba249b48f1, hi)
15:12:54 SILL PuppetWeChatBridge proxyWechaty(send, @a20259a44b886322318705474ed83bb6612cca272bcdfd698acbf9ba249b48f1, hi)
15:12:54 VERB Message static load(16307395740430507)
15:12:54 VERB Message constructor(16307395740430507) for class WechatifiedMessage
15:12:54 VERB Message ready()
15:12:54 VERB Puppet messagePayload(16307395740430507)
15:12:54 SILL Puppet messagePayloadCache(16307395740430507) cache MISS
15:12:54 SILL PuppetWeChatBridge getMessage(16307395740430507) retry attempt 1
15:12:54 SILL PuppetWeChatBridge proxyWechaty(getMessage, 16307395740430507)
15:12:54 ERR Config ###########################
15:12:54 ERR Config unhandledRejection: Error: Page crashed!
    at PuppetWeChat.<anonymous> (D:\WorkSpaces\njs\wechaty\node_modules\wechaty\dist\cjs\src\wechaty.js:271:44)
    at PuppetWeChat.emit (events.js:400:28)
    at PuppetWeChat.emit (domain.js:470:12)
    at Bridge.<anonymous> (D:\WorkSpaces\njs\wechaty\node_modules\wechaty-puppet-wechat\dist\src\puppet-wechat.js:203:45)
    at Bridge.emit (events.js:400:28)
    at Bridge.emit (domain.js:470:12)
    at D:\WorkSpaces\njs\wechaty\node_modules\wechaty-puppet-wechat\dist\src\bridge.js:169:36
    at D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at Page.emit (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at Page._onTargetCrashed (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:268:14)
    at D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:154:57
    at D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onMessage (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:225:18)
    at Connection._onMessage (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:101:25)
    at WebSocket.<anonymous> (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\node\NodeWebSocketTransport.js:13:32)
    at WebSocket.onMessage (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.emit (domain.js:470:12)
    at Receiver.receiverOnMessage (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\websocket.js:978:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.emit (domain.js:470:12)
    at Receiver.dataMessage (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\receiver.js:517:14)
    at Receiver.getData (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\receiver.js:435:17)
    at Receiver.startLoop (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\websocket.js:1072:35)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) [object Promise]
15:12:54 ERR Config ###########################
15:12:54 ERR Config process.on(unhandledRejection) promise.catch(Page crashed!)
Config Error: Page crashed!
    at PuppetWeChat.<anonymous> (D:\WorkSpaces\njs\wechaty\node_modules\wechaty\dist\cjs\src\wechaty.js:271:44)
    at PuppetWeChat.emit (events.js:400:28)
    at PuppetWeChat.emit (domain.js:470:12)
    at Bridge.<anonymous> (D:\WorkSpaces\njs\wechaty\node_modules\wechaty-puppet-wechat\dist\src\puppet-wechat.js:203:45)
    at Bridge.emit (events.js:400:28)
    at Bridge.emit (domain.js:470:12)
    at D:\WorkSpaces\njs\wechaty\node_modules\wechaty-puppet-wechat\dist\src\bridge.js:169:36
    at D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at Page.emit (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at Page._onTargetCrashed (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:268:14)
    at D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:154:57
    at D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at CDPSession.emit (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at CDPSession._onMessage (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:225:18)
    at Connection._onMessage (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:101:25)
    at WebSocket.<anonymous> (D:\WorkSpaces\njs\wechaty\node_modules\puppeteer\lib\cjs\puppeteer\node\NodeWebSocketTransport.js:13:32)
    at WebSocket.onMessage (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.emit (domain.js:470:12)
    at Receiver.receiverOnMessage (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\websocket.js:978:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.emit (domain.js:470:12)
    at Receiver.dataMessage (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\receiver.js:517:14)
    at Receiver.getData (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\receiver.js:435:17)
    at Receiver.startLoop (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at Socket.socketOnData (D:\WorkSpaces\njs\wechaty\node_modules\ws\lib\websocket.js:1072:35)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:3620) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
```

</details>

## 7. Additional context

> Add any other context about the problem here.

**Comment by Zhenyi-Wang** [comment]
改用官方模板 https://github.com/wechaty/wechaty-getting-started
貌似正常了🤠
