### ISSUE TITLE
Error: payload.fromId is null?

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#2252]
```
10:42:45 VERB Puppet dirtyPayloadContact(9223372041407373043@im.chatroom)
10:42:46 VERB Puppet dirtyPayload(RoomMember<4>, 9223372041407373043@im.chatroom)
10:42:46 VERB Puppet dirtyPayloadRoomMember(9223372041407373043@im.chatroom)
10:42:46 VERB Puppet selfId()
10:42:46 ERR Config ###########################
10:42:46 ERR Config uncaughtException: Error: payload.fromId is null?
at WechatifiedMessage.talker (/app/node_modules/wechaty/dist/src/user/message.js:182:19)
at WechatifiedMessage.self (/app/node_modules/wechaty/dist/src/user/message.js:519:29)
at /app/node_modules/wechaty-ducks-contrib/dist/src/contrib/counter/epics.js:46:237
at /app/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
at OperatorSubscriber.Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
at /app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:27:28
at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
at OperatorSubscriber.Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
at /app/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:24
at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
at OperatorSubscriber.Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
at /app/node_modules/rxjs/dist/cjs/internal/observable/from.js:124:28
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5) uncaughtException
10:42:46 ERR Config ###########################
finis Caught exception: Error: payload.fromId is null?
at WechatifiedMessage.talker (/app/node_modules/wechaty/dist/src/user/message.js:182:19)
at WechatifiedMessage.self (/app/node_modules/wechaty/dist/src/user/message.js:519:29)
at /app/node_modules/wechaty-ducks-contrib/dist/src/contrib/counter/epics.js:46:237
at /app/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
at OperatorSubscriber.Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
at /app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:27:28
at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
at OperatorSubscriber.Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
at /app/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:24
at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
at OperatorSubscriber.Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
at /app/node_modules/rxjs/dist/cjs/internal/observable/from.js:124:28
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5) Exception origin: uncaughtException
10:42:46 INFO RestartReporter finis(99, uncaughtException)
10:42:46 VERB HAWechaty logonoff()
10:42:46 INFO RestartReporter finis() announce exiting
10:42:46 INFO Chatops roomMessage(18995691396@chatroom, Der! I'm going to exit now, see you, bye!
OSSChat v0.9.38)
10:42:46 VERB HAWechaty logonoff()
10:42:46 VERB HAWechaty roomLoad(18995691396@chatroom)
10:42:46 VERB Room ready()
Error: payload.fromId is null?
at WechatifiedMessage.talker (/app/node_modules/wechaty/dist/src/user/message.js:182:19)
at WechatifiedMessage.self (/app/node_modules/wechaty/dist/src/user/message.js:519:29)
at /app/node_modules/wechaty-ducks-contrib/dist/src/contrib/counter/epics.js:46:237
at /app/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
at OperatorSubscriber.Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
at /app/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:27:28
at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
at OperatorSubscriber.Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
at /app/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:24
at OperatorSubscriber._this._next (/app/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
at OperatorSubscriber.Subscriber.next (/app/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
at /app/node_modules/rxjs/dist/cjs/internal/observable/from.js:124:28
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
finis: exit code: 1
10:42:46 WARN RestartReporter finis(1, exit) called again when quiting... enforce QUIT
]: Process exited with status 255
]: State changed from up to crashed
```

**Comment by huan** [comment]
If no `talker`, then `message.self()` should return `false` instead of `throws`
