### ISSUE TITLE
扫码登录之后系统抛出GRPCError,程序结束

### ISSUE THREAD

**Issue by koreQAQ** [wechaty/wechaty#2256]
## 扫码登录之后，系统抛出GRPCError 程序结束

使用一个微信扫码，提示`异地设备登录提示`，点击登录。系统抛出GRPCError
下面是程序日志：

```sh
https://wechaty.js.org/qrcode/http://weixin.qq.com/x/g7dSJBuXpAAFqWfq0hKW
2021-09-18 23:46:34,681 - Wechaty - ERROR - internal error <>
Traceback (most recent call last):
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/./src/wechat-bot.py", line 191, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/./src/wechat-bot.py", line 188, in main
    await bot.start()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/wechaty/wechaty.py", line 424, in start
    await self.puppet.start()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/wechaty_puppet_service/puppet.py", line 931, in start
    await self._listen_for_event()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/wechaty_puppet_service/puppet.py", line 993, in _listen_for_event
    async for response in self.puppet_stub.event():
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/wechaty_grpc/wechaty/__init__.py", line 59, in event
    async for response in self._unary_stream(
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/betterproto/__init__.py", line 1148, in _unary_stream
    yield message
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/grpclib/client.py", line 563, in __aexit__
    raise exc_val
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/grpclib/client.py", line 553, in __aexit__
    await self._maybe_finish()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/grpclib/client.py", line 523, in _maybe_finish
    await self.recv_trailing_metadata()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/grpclib/client.py", line 484, in recv_trailing_metadata
    self._raise_for_grpc_status(status, message, details)
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/grpclib/client.py", line 345, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'Session Timeout', None)
(venv) (base) 

```

## 其他信息
使用的账户L很长时间没有使用了，第一次登录成功之后，没有被自动登出。但退出再进行wechaty登录提示被限制了。后来使用自己的微信号给L账户解除限制，并使用L账户尝试再次登录

## 系统与版本信息
1. MacOS
2. Python3.9
3. wechaty0.8.24

## 自检

尝试切换另一个账户进行登录,还是抛出GRPCError，错误信息也是Session Timeout

```sh
Traceback (most recent call last):
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/./src/wechat-bot.py", line 191, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/./src/wechat-bot.py", line 188, in main
    await bot.start()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/wechaty/wechaty.py", line 424, in start
    await self.puppet.start()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/wechaty_puppet_service/puppet.py", line 931, in start
    await self._listen_for_event()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/wechaty_puppet_service/puppet.py", line 993, in _listen_for_event
    async for response in self.puppet_stub.event():
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/wechaty_grpc/wechaty/__init__.py", line 59, in event
    async for response in self._unary_stream(
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/betterproto/__init__.py", line 1148, in _unary_stream
    yield message
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/grpclib/client.py", line 563, in __aexit__
    raise exc_val
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/grpclib/client.py", line 553, in __aexit__
    await self._maybe_finish()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/grpclib/client.py", line 523, in _maybe_finish
    await self.recv_trailing_metadata()
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/grpclib/client.py", line 484, in recv_trailing_metadata
    self._raise_for_grpc_status(status, message, details)
  File "/Users/lishubin/CertificateDAO/certificate-dao-bot/venv/lib/python3.9/site-packages/grpclib/client.py", line 345, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.INTERNAL: 13>, 'Session Timeout', None)

```

## 询问的问题
1. 是否是账户限制问题？
2. 能否修改session 超时时间来避免自动退出？
3. 其他可行的解决方案

**Comment by koreQAQ** [comment]
再一次尝试，不抛出GRPCError，但账户在登录之后立刻退出：

```sh
2021-09-18 23:59:02,420 - Wechaty - ERROR - internal error <>
2021-09-18 23:59:08,930 - wechaty.plugin - INFO - init the plugins ...
2021-09-18 23:59:08,930 - Wechaty - INFO - receive <login> event <EventLoginPayload(contact_id='wxid_muousr7pdxbj12')>
2021-09-18 23:59:08,933 - Wechaty - INFO - receive <ready> event <EventReadyPayload(data='ready')>
2021-09-18 23:59:08,987 - Contact - INFO - load contact <Contact <wxid_muousr7pdxbj12> <L>>
User Contact <wxid_muousr7pdxbj12> <L> logged in

2021-09-18 23:59:11,082 - Wechaty - INFO - receive <logout> event <EventLogoutPayload(contact_id='wxid_muousr7pdxbj12', data='{"code":4,"msg":"Session Timeout"}')>
User <Contact <wxid_muousr7pdxbj12> <L>> logout
(venv) (base) 

```
