### ISSUE TITLE
Error: 13 INTERNAL: ERR_SEND_MSG send message failed

### ISSUE THREAD

**Issue by lx1990** [wechaty/wechaty#2257]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer: 0.62.3

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: vxwork

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer:

> What is your node version? (run `node --version`)

Answer: v12.2.0

> What os are you using

Answer: macos/linux

## 2. Describe the bug

Since yesterday, we can't send messages but we can still receive messages

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

1. run '...'
2. ...
3. ...

## 4. Expected behavior

> Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

> If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

11:59:35 VERB Puppet roomQueryFilterFactory({"topic":"Qrcode"})
11:59:35 SILL Puppet roomSearch() roomIdList filtered. result length=1
11:59:35 SILL Room constructor(R:4083045474)
11:59:35 VERB Room ready()
11:59:35 VERB Puppet roomPayload(R:4083045474)
11:59:35 VERB PuppetService roomMemberList(R:4083045474)
11:59:35 SILL Contact constructor(1688850953854378)
11:59:35 SILL Contact constructor(1688851970201947)
11:59:35 SILL Contact constructor(1688851987902084)
11:59:35 SILL Contact ready() @ Puppet#0<PuppetService>() with id="1688850801820758"
11:59:35 SILL Contact ready() isReady() true
11:59:35 SILL Contact ready() @ Puppet#0<PuppetService>() with id="1688850953854378"
11:59:35 SILL Contact ready() @ Puppet#0<PuppetService>() with id="1688851970201947"
11:59:35 SILL Contact ready() @ Puppet#0<PuppetService>() with id="1688851978014167"
11:59:35 SILL Contact ready() isReady() true
11:59:35 SILL Contact ready() @ Puppet#0<PuppetService>() with id="1688851984997390"
11:59:35 SILL Contact ready() isReady() true
11:59:35 SILL Contact ready() @ Puppet#0<PuppetService>() with id="1688851987902084"
11:59:35 SILL Puppet roomValidate(R:4083045474) base class just return `true`
11:59:35 VERB Room find() confirm room[#0] with id=0 is valid result, return it.
11:59:35 VERB Room say(test, )
11:59:35 VERB PuppetService messageSend(R:4083045474, test)
11:59:37 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_READY(23), payload:"{"data":"ready"}"})
11:59:37 SILL Wechaty memoryCheck() free: 357 MB, require: 4 MB
11:59:37 SILL Wechaty initPuppetEventBridge() puppet.on(ready)
11:59:37 SILL StateSwitch <WechatyReady> on() is true
11:59:37 VERB StateSwitch <WechatyReady> on(true) <- (true)
Error: 13 INTERNAL: ERR_SEND_MSG send message failed, conversationId: R:4083045474
    at Object.callErrorFromStatus (/Users/leo/Ricepo/wxwork/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/Users/leo/Ricepo/wxwork/node_modules/@grpc/grpc-js/src/client.ts:338:36)
    at Object.onReceiveStatus (/Users/leo/Ricepo/wxwork/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    at Object.onReceiveStatus (/Users/leo/Ricepo/wxwork/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /Users/leo/Ricepo/wxwork/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
    at processTicksAndRejections (internal/process/task_queues.js:82:9) {
  code: 13,
  details: 'ERR_SEND_MSG send message failed, conversationId: R:4083045474',
  metadata: Metadata { internalRepr: Map {}, options: {} }
}
time : 2021-09-19 11:59:28 , send failed
to : ["Qrcode"]
message : "test"
wechaty send error ====>  Error: 13 INTERNAL: ERR_SEND_MSG send message failed, conversationId: R:4083045474
Error: 13 INTERNAL: ERR_SEND_MSG send message failed, conversationId: R:4083045474
    at Object.callErrorFromStatus (/Users/leo/Ricepo/wxwork/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/Users/leo/Ricepo/wxwork/node_modules/@grpc/grpc-js/src/client.ts:338:36)
    at Object.onReceiveStatus (/Users/leo/Ricepo/wxwork/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    at Object.onReceiveStatus (/Users/leo/Ricepo/wxwork/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /Users/leo/Ricepo/wxwork/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
    at processTicksAndRejections (internal/process/task_queues.js:82:9) {
  code: 13,
  details: 'ERR_SEND_MSG send message failed, conversationId: R:4083045474',
  metadata: Metadata { internalRepr: Map {}, options: {} }
}

```

</details>

## 7. Additional context

> Add any other context about the problem here.

**Comment by lx1990** [comment]
I have also tried the latest wechaty,  same error
