### ISSUE TITLE
token: puppet_paimon   and   puppet: 'wechaty-puppet-service'  Failed to link     If you are Chinese, please speak Chinese, thank you!

### ISSUE THREAD

**Issue by 15335179243** [wechaty/wechaty#2261]
![090906958447d3ced8b4b8fffe71d21](https://user-images.githubusercontent.com/50068045/134347912-1f79929c-a8e2-4b30-bb7a-2fd76ea0924a.png)
6 ERR PuppetService start() rejection: 14 UNAVAILABLE: No connection established
Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /wechaty/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
20:58:28 ERR PuppetService start() this.grpc.stop() rejection: 14 UNAVAILABLE: No connection established
Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /wechaty/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /wechaty/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
20:58:28 ERR Wechaty start() exception: 14 UNAVAILABLE: No connection established
20:58:28 WARN PuppetService start() found this.grpc is already existed. dropped.

**Comment by huan** [comment]
Please disable TLS of you are using the latest version of Wechaty.

See:

- https://github.com/wechaty/wechaty-puppet-service/issues/160

**Comment by 15335179243** [comment]
> 如果您使用的是最新版本的微信，请禁用 TLS。
> 
> 看：
> 
> * [为微信生态系统的所有Puppet服务客户端启用TLS  wechaty-puppet-service#160](https://github.com/wechaty/wechaty-puppet-service/issues/160)

I set TLS to cancel but still can not


WECHATY Environment Variables: 3
WECHATY_DOCKER=1
WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER=false
WECHATY_LOG=

Starting Docker Container for Wechaty v0.0.0(unknown) with Node.js v16.8.0 ...
Working directory: /bot
Please make sure you had installed all the NPM modules which is depended on your bot script.
Executing node a.js
21:57:31 ERR PuppetService start() rejection: 14 UNAVAILABLE: No connection established
Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /wechaty/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by huan** [comment]
> WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER=false

The above setting is not right.

Set it to `true` to disable the TLS.

**Comment by 15335179243** [comment]
> > WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER=false
> 
> 上面的设置不对。
> 
> 将其设置`true`为禁用 TLS。

Yes, I tried again with the Settings set to True while waiting for your reply,It's always blocked
![image](https://user-images.githubusercontent.com/50068045/134358726-c3ff9bb0-2daf-4c7c-b674-b886dfc052dc.png)

**Comment by huan** [comment]
If you set it to `true` then the TLS will be disabled, it can be conformed by the log output:

> Init() TLS disabled.

So if you still can not connect to the puppet service, you need to check your puppet service token.

Can you try to run the following command and let me know what is the output? (Paste text please)

```sh
npm install -g wechaty-token
```

Then 

```sh
wechaty-token discover pippet_paimon_TOKEN
```

Note: replace the above token to yours.

**Comment by 15335179243** [comment]
> If you set it to `true` then the TLS will be disabled, it can be conformed by the log output:
> 
> > Init() TLS disabled.
> 
> So if you still can not connect to the puppet service, you need to check your puppet service token.
> 
> Can you try to run the following command and let me know what is the output? (Paste text please)
> 
> ```shell
> npm install -g wechaty-token
> ```
> 
> Then
> 
> ```shell
> wechaty-token discover pippet_paimon_TOKEN
> ```
> 
> Note: replace the above token to yours.
token没有问题
![image](https://user-images.githubusercontent.com/50068045/134482587-c5192f75-42d7-4e51-b3f8-a44e0c49b854.png)

**Comment by 15335179243** [comment]
> If you set it to `true` then the TLS will be disabled, it can be conformed by the log output:
> 
> > Init() TLS disabled.
> 
> So if you still can not connect to the puppet service, you need to check your puppet service token.
> 
> Can you try to run the following command and let me know what is the output? (Paste text please)
> 
> ```shell
> npm install -g wechaty-token
> ```
> 
> Then
> 
> ```shell
> wechaty-token discover pippet_paimon_TOKEN
> ```
> 
> Note: replace the above token to yours.



There is no problem with tokens


![image](https://user-images.githubusercontent.com/50068045/134482918-d6fa4823-22ce-487f-b760-4563abc7cc4a.png)

**Comment by huan** [comment]
If your token service is OK, could you please try the `wechaty@0.62` to see if it can fix your problem?

If not, then there might be related to some unknown problems, I'd like to suggest that you should contact the support from your puppet service provider.

**Comment by 15335179243** [comment]
thank you

**Comment by huan** [comment]
You are welcome
