### ISSUE TITLE
Unable to install wechaty-puppet-xxx automatically

### ISSUE THREAD

**Issue by lprintf** [wechaty/wechaty#2264]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer: wechaty@0.68.1

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: wechaty-puppet-wechat

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: default (auto install)

> What is your node version? (run `node --version`)

Answer: node v16.8.0

> What os are you using

Answer: ubuntu 20.04 - docker

## 2. Describe the bug

> Give a clear and concise description of what the bug is.

1. Unable to install wechaty-puppet-xxx automatically
2. Download wechaty-puppet-xxx repeatedly 

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

1. run 'npm install' in a project that depends wechaty
2. run the project with WECHATY_PUPPET=wechaty-puppet-wechat, such as `npm run dev:service`
3. wechaty-puppet-wechat cannot be installed automatically, and a redundant file named '=0.28' will be generated

## 4. Expected behavior

> Give a clear and concise description of what you expected to happen.

1. Install wechaty-puppet-xxx automatically
2. Download wechaty-puppet-xxx only once

## 5. Actual behavior

> If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

-> PASTE YOUR FULL(DO NOT ONLY PROVIDE FRAGMENTS) LOG MESSAGES HERE

-> first run
npm ERR! code 1
npm ERR! path /workspace/node_modules/wechaty/node_modules/git-scripts
npm ERR! command failed
npm ERR! command sh -c node bin/install
npm ERR! TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /workspace/node_modules/wechaty/node_modules/git-scripts/bin/install
npm ERR!     at new NodeError (node:internal/errors:371:5)
npm ERR!     at defaultGetFormat (node:internal/modules/esm/get_format:71:15)
npm ERR!     at defer (/workspace/node_modules/wechaty/node_modules/ts-node/src/esm.ts:82:7)
npm ERR!     at /workspace/node_modules/wechaty/node_modules/ts-node/src/esm.ts:104:24
npm ERR!     at Generator.next (<anonymous>)
npm ERR!     at /workspace/node_modules/wechaty/node_modules/ts-node/dist/esm.js:8:71
npm ERR!     at new Promise (<anonymous>)
npm ERR!     at __awaiter (/workspace/node_modules/wechaty/node_modules/ts-node/dist/esm.js:4:12)
npm ERR!     at getFormat (/workspace/node_modules/wechaty/node_modules/ts-node/dist/esm.js:55:16)
npm ERR!     at Loader.getFormat (node:internal/modules/esm/loader:105:42) {
npm ERR!   code: 'ERR_UNKNOWN_FILE_EXTENSION'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-09-25T09_38_47_712Z-debug.log

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm install wechaty-puppet-wechat@>=0.28  --no-save'
}
09:38:47 ERR Wechaty start() exception: Command failed: npm install wechaty-puppet-wechat@>=0.28  --no-save
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated eslint-plugin-standard@5.0.0: standard 16.0.0 and eslint-config-standard 16.0.0 no longer require the eslint-plugin-standard package. You can remove it from your dependencies with 'npm rm eslint-plugin-standard'. More info here: https://github.com/standard/standard/issues/1316
npm WARN deprecated tslint-config-standard@9.0.0: TSLint is deprecated, please move to ESLint: https://github.com/blakeembrey/tslint-config-standard/issues/61
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.
npm ERR! code 1
npm ERR! path /workspace/node_modules/wechaty/node_modules/git-scripts
npm ERR! command failed
npm ERR! command sh -c node bin/install
npm ERR! TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /workspace/node_modules/wechaty/node_modules/git-scripts/bin/install
npm ERR!     at new NodeError (node:internal/errors:371:5)
npm ERR!     at defaultGetFormat (node:internal/modules/esm/get_format:71:15)
npm ERR!     at defer (/workspace/node_modules/wechaty/node_modules/ts-node/src/esm.ts:82:7)
npm ERR!     at /workspace/node_modules/wechaty/node_modules/ts-node/src/esm.ts:104:24
npm ERR!     at Generator.next (<anonymous>)
npm ERR!     at /workspace/node_modules/wechaty/node_modules/ts-node/dist/esm.js:8:71
npm ERR!     at new Promise (<anonymous>)
npm ERR!     at __awaiter (/workspace/node_modules/wechaty/node_modules/ts-node/dist/esm.js:4:12)
npm ERR!     at getFormat (/workspace/node_modules/wechaty/node_modules/ts-node/dist/esm.js:55:16)
npm ERR!     at Loader.getFormat (node:internal/modules/esm/loader:105:42) {
npm ERR!   code: 'ERR_UNKNOWN_FILE_EXTENSION'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-09-25T09_38_47_712Z-debug.log

-> second running after the manual installation. Even I have install wechaty-puppet-wechat successfully, It will install again, the conmand seem to have problems `npm install wechaty-puppet-wechat@>=0.28  --no-save`.
09:46:13 VERB PuppetManager resolveName(wechaty-puppet-wechat)
09:46:13 VERB PuppetManager checkModule(wechaty-puppet-wechat)
09:46:13 SILL PuppetManager checkModule(wechaty-puppet-wechat) not installed.
09:46:13 INFO PuppetManager install(wechaty-puppet-wechat@>=0.28) please wait ...
```

</details>

## 7. Additional context

> Add any other context about the problem here.

```
node ➜ /workspace/node_modules/wechaty (dependabot/npm_and_yarn/read-pkg-up-8.0.0 ✗) $ ls
'=0.28'   LICENSE        README.md
 bin      node_modules   src
 dist     package.json   tsconfig.json
node ➜ /workspace/node_modules/wechaty (dependabot/npm_and_yarn/read-pkg-up-8.0.0 ✗) $ cat '=0.28' 
(no output)

after the manual installation, it work:
node ➜ /workspace/node_modules/wechaty (dependabot/npm_and_yarn/read-pkg-up-8.0.0 ✗) $ ls node_modules/wechaty-
wechaty-grpc/           wechaty-puppet-service/
wechaty-puppet/         wechaty-puppet-wechat/
wechaty-puppet-mock/    wechaty-token/
node ➜ /workspace/node_modules/wechaty (dependabot/npm_and_yarn/read-pkg-up-8.0.0 ✗) $ npm install wechaty-puppet-wechat --no-save
```

**Comment by huan** [comment]
Yes, we remove this feature after we moved to ESM.

So we will need to install all puppet manually after v0.69

**Comment by lprintf** [comment]
OK, I got it. Thanks for your answer!

**Comment by huan** [comment]
BTW If you need to support all puppets in your system, for example, a Dockerfile, you can use the following command:

https://github.com/wechaty/wechaty/blob/b367f17958de4374f64f29504d6e022d3a210b02/Dockerfile#L74
