### ISSUE TITLE
同时发送多条视频引起的奔溃问题

### ISSUE THREAD

**Issue by 15335179243** [wechaty/wechaty#2296]
error: Error: aborted
    at connResetException (node:internal/errors:691:14)
    at Socket.socketCloseListener (node:_http_client:407:19)
    at Socket.emit (node:events:402:35)
    at Socket.emit (node:domain:475:12)
    at TCP.<anonymous> (node:net:687:12) {
  code: 'ECONNRESET'
}
finis Caught exception: Error: aborted
    at connResetException (node:internal/errors:691:14)
    at Socket.socketCloseListener (node:_http_client:407:19)
    at Socket.emit (node:events:402:35)
    at Socket.emit (node:domain:475:12)
    at TCP.<anonymous> (node:net:687:12) {
  code: 'ECONNRESET'
} Exception origin: uncaughtException
16:03:34 ERR Importand data saved at this step. 
16:03:34 ERR Wechaty exit 99 because of uncaughtException/Error: aborted 

发送了四条视频，其中三条没有超过20m，一条为28m，三条成功了，一条失败

**Comment by 15335179243** [comment]
我想知道同时发送多条视频是同步还是异步，异步的话怎么样能够就行同步发送

**Comment by 15335179243** [comment]
18:12:06 ERR PuppetWeChat uploadMedia(): upload fail
18:12:06 ERR PuppetWeChat sendMedia() exception: PuppetWeChat.uploadMedia(): upload fail
finis Caught exception: Error: PuppetWeChat.uploadMedia(): upload fail
    at PuppetWeChat.uploadMedia (/wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/puppet-wechat.js:1223:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWeChat.messageSendFile (/wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/puppet-wechat.js:1233:29)
    at async WechatifiedRoom.say (/wechaty/dist/cjs/src/user/room.js:411:21) Exception origin: unhandledRejection
18:12:06 ERR Importand data saved at this step. 
18:12:06 ERR Wechaty exit 99 because of uncaughtException/Error: PuppetWeChat.uploadMedia(): upload fail 
finis: exit code: 1
18:12:06 ERR Importand data saved at this step. 
18:12:06 ERR Wechaty exit 1 because of exit/undefined
