### ISSUE TITLE
start wechaty gateway error

### ISSUE THREAD

**Issue by Jesn** [wechaty/wechaty#2321]
docker compose
```
version: '3'
services:
  wechaty-https:
    image: wechaty/wechaty:latest
    container_name: wechaty-https
    restart: always
    ports:
      - 9001:9001
    environment:
      - TZ=Asia/Shanghai
      - WECHATY_LOG=verbose
      - WECHATY_PUPPET=wechaty-puppet-service
      - WECHATY_PUPPET_SERVICE_TOKEN=XXXX
      - WECHATY_PUPPET_SERVER_PORT=9001
      - WECHATY_TOKEN=XXX
      - WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true
```

Error Info:
```
11:31:53 ERR IoClient start() exception: Wechaty Puppet Service requires a SNI as prefix of the token from version 0.30 and later.
You can add the "insecure_" prefix to your token
like: "insecure_XXXX"
and try again.
```

**Comment by huan** [comment]
What is said in the error message is very clear: your DIY token needs a prefix which is required in the Wechaty v1.x system.

The best way is to use `wechaty-token` utility to generate one for you:

```sh
$ npm install -g wechaty-token
$ wechaty-token generate --type insecure
insecure_1fab726b-e3d3-40ce-8b7b-d3bd8c9fd280
```

**Comment by huan** [comment]
BTW: if you need a token gateway for PadLocal/SimplePad, then you need to use the v0.x wechaty docker image like `wechaty/wechaty:0.68` instead of `latest`.

Because we are still waiting for the PadLocal/SimplePad to be adapted to Wechaty v1.x API.

**Comment by Jesn** [comment]
wechaty-token  command error
```
OS: ubuntu

root@nas:/# npm  --version
6.14.4

root@nas:/# node -v
v10.19.0


root@nas:/# wechaty-token generate --type insecure
/usr/local/lib/node_modules/wechaty-token/dist/esm/bin/cli.js:14
import { binary, run, subcommands, } from 'cmd-ts';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
root@nas:/#
```


but it's good  in docker wechaty gateway

**Comment by huan** [comment]
Node.js v16+ is required.
