### ISSUE TITLE
using M1 Pro mac  for Wechaty v0.75.27  (ERR PuppetPuppeteerBridge start() exception: Error: Protocol error (Target.createTarget): Target closed.)

### ISSUE THREAD

**Issue by caihongyu2022** [wechaty/wechaty#2327]
when using M1 pro architecture,  it is wrong, below is log
base:  docker + nodjs+typeScript +web Protocol
architecture:M1 Pro 
system: monterey
nodejs: Node.js v16.11.1 ...

which WECHATY verson is for M1Pro
````
WECHATY Environment Variables: 2
WECHATY_PUPPET=wechaty-puppet-puppeteer
WECHATY_DOCKER=1

Starting Docker Container for Wechaty v0.75.27 with Node.js v16.11.1 ...
Working directory: /bot
Executing node --loader=ts-node/esm src/typescript.ts
05:25:02 ERR PuppetPuppeteerBridge start() exception: Error: Protocol error (Target.createTarget): Target closed.
Bot error: Error: Protocol error (Target.createTarget): Target closed.
    at PuppetPuppeteer.<anonymous> (file:///wechaty/src/wechaty.ts:442:32)
    at PuppetPuppeteer.emit (node:events:390:28)
    at PuppetPuppeteer.emit (node:domain:475:12)
    at Bridge.<anonymous> (/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:313:52)
    at Bridge.emit (node:events:390:28)
    at Bridge.emit (node:domain:475:12)
    at Bridge.start (/wechaty/node_modules/wechaty-puppet-puppeteer/src/bridge.ts:121:12)
    at async PuppetPuppeteer.initBridge (/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:322:7)
    at async PuppetPuppeteer.start (/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:164:21)
    at async Wechaty.tryStart (file:///wechaty/src/wechaty.ts:767:5)
    at async Wechaty.start (file:///wechaty/src/wechaty.ts:730:7)
05:25:02 ERR PuppetPuppeteer initBridge() exception: Protocol error (Target.createTarget): Target closed.
05:25:02 ERR PuppetPuppeteer initBridge() this.bridge.stop() rejection: Error: no page
Bot error: Error
    at PuppetPuppeteer.<anonymous> (file:///wechaty/src/wechaty.ts:442:32)
    at PuppetPuppeteer.emit (node:events:390:28)
    at PuppetPuppeteer.emit (node:domain:475:12)
    at PuppetPuppeteer.initBridge (/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:328:12)
    at async PuppetPuppeteer.start (/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:164:21)
    at async Wechaty.tryStart (file:///wechaty/src/wechaty.ts:767:5)
    at async Wechaty.start (file:///wechaty/src/wechaty.ts:730:7)
05:25:02 ERR PuppetPuppeteer start() exception: Error: Protocol error (Target.createTarget): Target closed.
Bot error: Error
    at PuppetPuppeteer.<anonymous> (file:///wechaty/src/wechaty.ts:442:32)
    at PuppetPuppeteer.emit (node:events:390:28)
    at PuppetPuppeteer.emit (node:domain:475:12)
    at PuppetPuppeteer.start (/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:201:12)
    at async Wechaty.tryStart (file:///wechaty/src/wechaty.ts:767:5)
    at async Wechaty.start (file:///wechaty/src/wechaty.ts:730:7)
05:25:02 ERR PuppetPuppeteer this.bridge.quit() exception: no page
Error: no page
    at Bridge.stop (/wechaty/node_modules/wechaty-puppet-puppeteer/src/bridge.ts:336:13)
    at PuppetPuppeteer.stop (/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:230:25)
    at PuppetPuppeteer.start (/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:202:18)
    at async Wechaty.tryStart (file:///wechaty/src/wechaty.ts:767:5)
    at async Wechaty.start (file:///wechaty/src/wechaty.ts:730:7)
05:25:02 ERR Wechaty start() rejection: no page
05:25:02 WARN Wechaty stop() found that is starting, waiting stable ...
05:25:07 WARN Wechaty stop() found that is starting, waiting stable ... 5 seconds timeout
05:25:07 WARN PuppetPuppeteer stop() is called on a OFF puppet. await ready(off) and return.
Bot error: Error: no page
    at Bridge.stop (/wechaty/node_modules/wechaty-puppet-puppeteer/src/bridge.ts:336:13)
    at PuppetPuppeteer.stop (/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:230:25)
    at PuppetPuppeteer.start (/wechaty/node_modules/wechaty-puppet-puppeteer/src/puppet-puppeteer.ts:202:18)
    at async Wechaty.tryStart (file:///wechaty/src/wechaty.ts:767:5)
    at async Wechaty.start (file:///wechaty/src/wechaty.ts:730:7)

 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.chatie.io
  _____      _ _      ___   
 | ____|_  _(_) |_   / _ \  
 |  _| \ \/ / | __| | | | | 
 | |___ >  <| | |_  | |_| | 

```

**Comment by huan** [comment]
Thanks for reporting!

I got time to reproduce this problem on my M1 mac, and here's how to run Wechaty successfully on M1 mac:

## ding-dong-bot.ts

```ts
import {
  WechatyBuilder,
  ScanStatus,
}                     from 'wechaty'

const options = {
  name : 'ding-dong-bot',
  puppet: 'wechaty-puppet-wechat',
  puppetOptions: {
    endpoint: '/usr/bin/chromium',
  },
}

const bot = WechatyBuilder.build(options)

bot.on('scan', onScan)
await bot.start()

function onScan (qrcode: string, status: ScanStatus) {
  console.info('onScan: %s(%s) - %s', ScanStatus[status], status, qrcode)
}
```

## Docker run

```sh
$ docker pull wechaty/wechaty:next
next: Pulling from wechaty/wechaty
Digest: sha256:943ac6ada9817082e0c17a7ebc0c86f1526a2321e7515e2702767a0d53a8d2df
Status: Image is up to date for wechaty/wechaty:next
docker.io/wechaty/wechaty:next

$ docker run -ti --rm wechaty/wechaty:next shell

# Entered the docker container

$ uname -m
aarch64

$ node --no-warnings --loader ts-node/esm ding-dong-bot.ts
onScan: Waiting(2) - https://login.weixin.qq.com/l/wfiSXDgR8w==
```

**Comment by caihongyu2022** [comment]
@huan thanks  your response~ but where is the Documents about the new API for "WechatyBuilder" ,and how to coding the api under the below.. 
it is the way for imported before,but what's way to importing the  Contact,Room and Message now.....
````
import {
  Contact,
  Room,
  Message,
 // Wechaty,
 WechatyBuilder,
 ScanStatus,
  //FileBox,
}           from 'wechaty'
````

**Comment by caihongyu2022** [comment]
@huan  it  is running  with your demo on M1Pro,thanks very much. It bothered me for many days..ORZ
but now , have some new issue..
1.**const talker = msg.talker(); return "WechatifiedContactSelfImpl"** 
````
async function onMessage (msg: Message) {
const talker = msg.talker()
}
````
2.
```
[4] https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FQeyCm0_SGg%3D%3D
Scan QR Code above to log in: 
꧁༺ཌ༈一念·神魔༈ད༻꧂ login
02:22:25 WARN PuppetWeChat roomRawPayload() currLength(0) <= prevLength(485) ???
02:22:26 WARN PuppetWeChat roomRawPayload() currLength(0) <= prevLength(485) ???
02:22:27 WARN PuppetWeChat roomRawPayload() currLength(0) <= prevLength(485) ???
roomName:王者北京同城表现
02:22:28 WARN PuppetWeChat roomRawPayload() currLength(0) <= prevLength(485) ???
02:22:29 WARN PuppetWeChat roomRawPayload() currLength(0) <= prevLength(485) ???
roomName:王者北京同城表现
02:22:30 WARN PuppetWeChat roomRawPayload() currLength(0) <= prevLength(485) ???
02:22:31 ERR PuppetWeChat roomRawPayload(@@b3f1d85944f3aa3cf4c3b2c2cb6a45e5596dc813955116d61ba97a5460cd6872) exception: no payload
Bot error: GError: no payload
    at PuppetWeChat.roomRawPayload (file:///wechaty/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:731:13)
    at async PuppetWeChat.roomPayload (file:///wechaty/node_modules/wechaty-puppet/src/mixins/room-mixin.ts:241:26)
    at async WechatifiedUserClass.ready (file:///wechaty/src/user-modules/room.ts:320:21)
    at async Function.find (file:///wechaty/src/user-modules/room.ts:205:9)
    at async WechatifiedUserClass.ready (file:///wechaty/src/user-modules/message.ts:787:7)
    at async Promise.all (index 0)
    at async Function.findAll (file:///wechaty/src/user-modules/message.ts:137:7)
    at async Function.find (file:///wechaty/src/user-modules/message.ts:110:25)
    at async PuppetWeChat.<anonymous> (file:///wechaty/src/wechaty-mixins/puppet-mixin.ts:270:29) {
  code: 2,
  details: 'Error: no payload\n' +
    '    at PuppetWeChat.roomRawPayload (file:///wechaty/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:731:13)\n' +
    '    at async PuppetWeChat.roomPayload (file:///wechaty/node_modules/wechaty-puppet/src/mixins/room-mixin.ts:241:26)\n' +
    '    at async WechatifiedUserClass.ready (file:///wechaty/src/user-modules/room.ts:320:21)\n' +
    '    at async Function.find (file:///wechaty/src/user-modules/room.ts:205:9)\n' +
    '    at async WechatifiedUserClass.ready (file:///wechaty/src/user-modules/message.ts:787:7)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Function.findAll (file:///wechaty/src/user-modules/message.ts:137:7)\n' +
    '    at async Function.find (file:///wechaty/src/user-modules/message.ts:110:25)\n' +
    '    at async PuppetWeChat.<anonymous> (file:///wechaty/src/wechaty-mixins/puppet-mixin.ts:270:29)'
}

```

**Comment by huan** [comment]
Great to know that you can run the Wechaty Docker image on your M1 mac!

For your new problem, could you please file a new issue for tracking because it's not related to mac M1 I believe?

And please feel free to close this issue if you have no more questions about the docker image for mac M1 anymore.

**Comment by caihongyu2022** [comment]
@huan Yes, I will open an new issue , this  can be closed on mac M1Pro
