### ISSUE TITLE
No connection established

### ISSUE THREAD

**Issue by zhihuifanqiechaodan** [wechaty/wechaty#2334]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer: ^1.10.4

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: wechaty-puppet-service

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: ~1.11.2

> What is your node version? (run `node --version`)

Answer: v16.13.0

> What os are you using

Answer: macOS

## 2. Describe the bug

>  下载最新版本wechayt, 运行一个简单的demo，抛出错误

## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

1. npm install wechaty
2. WECHATY_LOG=silly node main.js
```sh
import { WechatyBuilder } from 'wechaty'

WechatyBuilder.build({
    name: 'ding-dong-bot',
    puppet: 'wechaty-puppet-service',
    puppetOptions: {
        token: 'xxxxxxxxxxx',
    }
})  // get a Wechaty instance
    .on('scan', (qrcode, status) => console.log(`Scan QR Code to login: ${status}\nhttps://wechaty.js.org/qrcode/${encodeURIComponent(qrcode)}`))
    .on('login', user => console.log(`User ${user} logged in`))
    .on('message', message => console.log(`Message: ${message}`))
    .start()
    .catch(reason => {
        console.log(reason);
    })
```

## 4. Expected behavior

> Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

> 

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

-> 11:33:12 SILL Puppet Config: WECHATY_LOG set level to silly
11:33:12 INFO Config registering process.on("unhandledRejection") for development/debug
11:33:12 VERB Config constructor()
11:33:12 VERB PoolifyMixin poolifyMixin(EventEmitter)
11:33:12 VERB WechatifyMixin wechatifyMixin(AbstractPoolifyMixin)
11:33:12 VERB ValidationMixin validationMixin(ContactMixin)
11:33:12 VERB ValidationMixin validationMixin(ContactImplBase)
11:33:12 VERB PoolifyMixin poolifyMixin(ContactImpl)
11:33:12 VERB ValidationMixin validationMixin(ContactSelfMixin)
11:33:12 VERB WechatifyMixin wechatifyMixin(EmptyBase)
11:33:12 VERB ValidationMixin validationMixin(FavoriteMixin)
11:33:12 VERB WechatifyMixin wechatifyMixin(EventEmitter)
11:33:12 VERB ValidationMixin validationMixin(FriendshipMixin)
11:33:12 VERB WechatifyMixin wechatifyMixin(EmptyBase)
11:33:12 VERB ValidationMixin validationMixin(ImageMixin)
11:33:12 VERB WechatifyMixin wechatifyMixin(EmptyBase)
11:33:12 VERB ValidationMixin validationMixin(LocationMixin)
11:33:12 VERB WechatifyMixin wechatifyMixin(EmptyBase)
11:33:12 VERB ValidationMixin validationMixin(UrlLinkMixin)
11:33:12 VERB WechatifyMixin wechatifyMixin(EmptyBase)
11:33:12 VERB ValidationMixin validationMixin(MiniProgramMixin)
11:33:12 VERB WechatifyMixin wechatifyMixin(EventEmitter)
11:33:12 VERB ValidationMixin validationMixin(MessageMixin)
11:33:12 VERB ValidationMixin validationMixin(MessageImplBase)
11:33:12 VERB WechatifyMixin wechatifyMixin(EmptyBase)
11:33:12 VERB ValidationMixin validationMixin(MomentMixin)
11:33:12 VERB WechatifyMixin wechatifyMixin(EmptyBase)
11:33:12 VERB ValidationMixin validationMixin(MoneyMixin)
11:33:12 VERB PoolifyMixin poolifyMixin(EventEmitter)
11:33:12 VERB WechatifyMixin wechatifyMixin(AbstractPoolifyMixin)
11:33:12 VERB ValidationMixin validationMixin(RoomMixin)
11:33:12 VERB WechatifyMixin wechatifyMixin(EmptyBase)
11:33:12 VERB ValidationMixin validationMixin(RoomInvitationMixin)
11:33:12 VERB WechatifyMixin wechatifyMixin(EmptyBase)
11:33:12 VERB PoolifyMixin poolifyMixin(AbstractWechatifyMixin)
11:33:12 VERB ValidationMixin validationMixin(TagMixin)
11:33:12 VERB WechatifyMixin wechatifyMixin(EmptyBase)
11:33:12 VERB ValidationMixin validationMixin(DelayMixin)
11:33:12 VERB WechatyGErrorMixin gErrorMixin(WechatySkeleton)
11:33:12 VERB WechatifyUserModuleMixin wechatifyUserModuleMixin(GErrorMixin)
11:33:12 VERB WechatyPluginMixin pluginMixin(WechatifyUserModuleMixin)
11:33:12 VERB WechatyPuppetMixin puppetMixin(PluginMixin)
11:33:12 VERB WechatyLoginMixin loginMixin(PuppetMixin)
11:33:12 VERB WechatyMiscMixin miscMixin(LoginMixin)
11:33:12 VERB WechatyIoMixin ioMixin(MiscMixin)
11:33:12 VERB ValidationMixin validationMixin(WechatyBase)
11:33:12 VERB ValidationMixin validationMixin(WechatyImplBase)
11:33:12 VERB wechaty-puppet-service monkeyPatchMetadataFromHttp2Headers()
11:33:13 VERB WechatyBuilder singleton()
11:33:13 VERB WechatyBuilder newInstance()
11:33:13 VERB WechatyIoMixin constructor()
11:33:13 VERB WechatyLoginMixin constructor()
11:33:13 VERB WechatyPuppetMixin construct()
11:33:13 VERB WechatifyUserModuleMixin constructor()
11:33:13 VERB WechatySkeleton constructor()
11:33:13 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
11:33:13 VERB ServiceCtl<Wechaty> constructor()
11:33:13 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
11:33:13 VERB StateSwitch constructor(WechatyReset, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
11:33:13 VERB Wechaty constructor()
11:33:13 VERB WechatySkeleton on(scan, listener) registering... listenerCount: 0
11:33:13 VERB WechatySkeleton on(login, listener) registering... listenerCount: 0
11:33:13 VERB WechatySkeleton on(message, listener) registering... listenerCount: 0
11:33:13 VERB ServiceCtl<Wechaty> start()
11:33:13 SILL StateSwitch <Wechaty> active() is false
11:33:13 SILL StateSwitch <Wechaty> inactive() is true
11:33:13 SILL StateSwitch <Wechaty> active() is false
11:33:13 VERB StateSwitch <Wechaty> active(pending) <- (false)
11:33:13 VERB ServiceCtl<Wechaty> start() super.start() ...
11:33:13 VERB WechatyIoMixin start()
11:33:13 VERB WechatyLoginMixin start()
11:33:13 VERB WechatyPuppetMixin start()
11:33:13 VERB WechatyPuppetMixin start() super.start() ...
11:33:13 VERB WechatyPluginMixin start()
11:33:13 VERB WechatifyUserModuleMixin start()
11:33:13 VERB WechatySkeleton start()
11:33:13 VERB Wechaty init() Raven disabled (import("raven") failed)
11:33:13 VERB WechatifyUserModuleMixin _wechatifyUserModules()
11:33:13 VERB WechatifyUserModuleMixin _wechatifyUserModules() initializing Wechaty User Module (WUM) ...
11:33:13 VERB WechatifyMixin wechatifyUserModule(ContactImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(ContactImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyMixin wechatifyUserModule(ContactSelfImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(ContactSelfImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyMixin wechatifyUserModule(DelayImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(DelayImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyMixin wechatifyUserModule(FriendshipImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(FriendshipImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyMixin wechatifyUserModule(ImageImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(ImageImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyMixin wechatifyUserModule(LocationImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(LocationImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyMixin wechatifyUserModule(MessageImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(MessageImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyMixin wechatifyUserModule(MiniProgramImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(MiniProgramImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyMixin wechatifyUserModule(RoomImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(RoomImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyMixin wechatifyUserModule(RoomInvitationImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(RoomInvitationImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyMixin wechatifyUserModule(TagImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(TagImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyMixin wechatifyUserModule(UrlLinkImpl)
11:33:13 VERB WechatifyMixin wechatifyUserModule(UrlLinkImpl)(Wechaty#9e81c6ba-3f47-437e-a70b-b21877744ec7<wechaty-puppet-service>(ding-dong-bot))
11:33:13 VERB WechatifyUserModuleMixin _wechatifyUserModules() initializing Wechaty User Module (WUM) ... done
11:33:13 VERB WechatyPluginMixin start() installing plugins(global/0, instance/0) ...
11:33:13 VERB WechatyPluginMixin start() installing plugins(global/0, instance/0) ... done
11:33:13 VERB WechatyPuppetMixin start() super.start() ... done
11:33:13 SILL StateSwitch <WechatyReady> active() is false
11:33:13 VERB WechatyPuppetMixin start() initializing puppet instance ...
11:33:13 VERB WechatyPuppetMixin __initPuppetInstance() wechaty-puppet-service
11:33:13 VERB WechatyPuppetMixin __initPuppetInstance() instanciating puppet instance ...
11:33:13 VERB PuppetManager resolve({puppet: wechaty-puppet-service, puppetOptions: {"token":"puppet_wxwork_14703019ecdd09ce"}})
11:33:13 VERB PuppetManager resolve() resolving name "wechaty-puppet-service" ...
11:33:13 VERB PuppetManager resolveName(wechaty-puppet-service)
11:33:13 VERB PuppetManager resolveName(wechaty-puppet-service): ESM resolved
11:33:13 VERB PuppetManager resolve() resolving name "wechaty-puppet-service" ... done
11:33:13 VERB PuppetManager resolve() instanciating puppet ...
11:33:13 VERB PuppetSkeleton constructor({"token":"puppet_wxwork_14703019ecdd09ce"})
11:33:13 VERB PuppetMemoryMixin constructor()
11:33:13 VERB PuppetLoginMixin constructor()
11:33:13 VERB PuppetCacheMixin constructor()
11:33:13 VERB PuppetCacheAgent constructor()
11:33:13 VERB PuppetContactMixin constructor()
11:33:13 VERB PuppetRoomMemberMixin constructor()
11:33:13 VERB PuppetRoomMixin constructor()
11:33:13 VERB PuppetFriendshipMixin constructor()
11:33:13 VERB PuppetTagMixin constructor()
11:33:13 VERB PuppetRoomInvitationMixin constructor()
11:33:13 VERB PuppetMessageMixin constructor()
11:33:13 VERB PuppetMiscMixin constructor()
11:33:13 VERB ServiceCtl<PuppetServiceMixin> constructor()
11:33:13 VERB StateSwitch constructor(PuppetServiceMixin, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
11:33:13 VERB StateSwitch constructor(PuppetServiceMixinReset, "{"log":{"enableTimestamp":true,"logLevel":5,"prefixFilter":{}}}")
11:33:13 VERB PuppetServiceMixin constructor() #0
11:33:13 VERB PuppetWatchdogAgent constructor(820d63be-926f-4f4a-908a-1e267c0b70c9)
11:33:13 VERB PuppetWatchdogAgent constructor() timeout 60 seconds
11:33:13 VERB Puppet constructor({"token":"puppet_wxwork_14703019ecdd09ce"})
11:33:13 VERB PayloadStore constructor({"token":"puppet_wxwork_14703019ecdd09ce"})
11:33:13 SILL PayloadStore constructor() storeDir: "/Users/cctvabu/.wechaty/wechaty-puppet-service/puppet_wxwork_14703019ecdd09ce/v1.10"
11:33:13 VERB PuppetService hookPayloadStore()
11:33:13 VERB PuppetManager resolve() instanciating puppet ... done
11:33:13 VERB WechatyPuppetMixin __initPuppetInstance() instanciating puppet instance ... done
11:33:13 VERB WechatyPuppetMixin __initPuppetInstance() setting memory ...
11:33:13 VERB PuppetMemoryMixin setMemory(ding-dong-bot)
11:33:13 VERB WechatyPuppetMixin __initPuppetInstance() setting memory ... done
11:33:13 VERB WechatyPuppetMixin __initPuppetInstance() setting up events ...
11:33:13 VERB WechatyPuppetMixin __setupPuppetEvents(Puppet<PuppetService>(ding-dong-bot))
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(friendship) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(login) (listenerCount:1) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(logout) (listenerCount:1) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(message) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-invite) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-join) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-leave) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(room-topic) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(scan) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(dirty) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(dong) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(error) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(heartbeat) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(ready) (listenerCount:0) registering...
11:33:13 VERB PuppetMixin __setupPuppetEvents() puppet.on(reset) (listenerCount:0) registering...
11:33:13 VERB WechatyPuppetMixin __setupPuppetEvents() ... done
11:33:13 VERB WechatyPuppetMixin __initPuppetInstance() setting up events ... done
11:33:13 VERB WechatyPuppetMixin __initPuppetInstance() emitting "puppet" event ...
11:33:13 VERB WechatyPuppetMixin __initPuppetInstance() emitting "puppet" event ... done
11:33:13 VERB WechatyPuppetMixin start() initializing puppet instance ... done
11:33:13 VERB WechatyPuppetMixin start() starting puppet ...
11:33:13 VERB PuppetServiceMixin start()
11:33:13 VERB ServiceCtl<PuppetServiceMixin> start()
11:33:13 SILL StateSwitch <PuppetServiceMixin> active() is false
11:33:13 SILL StateSwitch <PuppetServiceMixin> inactive() is true
11:33:13 SILL StateSwitch <PuppetServiceMixin> active() is false
11:33:13 VERB StateSwitch <PuppetServiceMixin> active(pending) <- (false)
11:33:13 VERB ServiceCtl<PuppetServiceMixin> start() super.start() ...
11:33:13 VERB PuppetCacheMixin start()
11:33:13 VERB PuppetLoginMixin start()
11:33:13 VERB PuppetMemoryMixin start()
11:33:13 VERB PuppetSkeleton start()
11:33:13 VERB PuppetCacheAgent start()
11:33:13 VERB PuppetCacheAgent clear()
11:33:13 VERB PuppetCacheMixin start() "dirty" event listener added
11:33:13 VERB ServiceCtl<PuppetServiceMixin> start() super.start() ... done
11:33:13 VERB ServiceCtl<PuppetServiceMixin> start() this.onStart() ...
11:33:13 VERB PuppetService onStart()
11:33:13 VERB PuppetService start() instanciating GrpcManager ...
11:33:13 VERB GrpcManager constructor({"token":"puppet_wxwork_14703019ecdd09ce"})
11:33:13 VERB GrpcManager constructor() tlsRootCert(hash): "88ab8b62777f0fb1179ec567c5019c31d646428cc0a3fdb007fcffa1e9fac5a8"
11:33:13 VERB GrpcManager constructor() token: "puppet_wxwork_14703019ecdd09ce"
11:33:13 VERB GrpcManager constructor() endpoint: "wechaty://api.chatie.io/puppet_wxwork_14703019ecdd09ce"
11:33:13 VERB GrpcManager constructor() disableTls: "false"
11:33:13 VERB GrpcManager constructor() serverName(SNI): "puppet_wxwork"
11:33:13 VERB PuppetService start() instanciating GrpcManager ... done
11:33:13 VERB PuppetService start() setting up bridge grpc event stream ...
11:33:13 VERB PuppetService bridgeGrpcEventStream(client)
11:33:13 VERB PuppetService start() setting up bridge grpc event stream ... done
11:33:13 VERB PuppetService start() starting grpc manager...
11:33:13 VERB GrpcManager start()
11:33:13 VERB GrpcManager start() initializing client ...
11:33:13 VERB GrpcManager initClient()
11:33:13 VERB GrpcManager initClient() TLS: enabled
11:33:13 VERB GrpcManager initClient() ... done
11:33:13 VERB GrpcManager start() initializing client ... done
11:33:13 VERB GrpcManager start() starting stream ...
11:33:13 VERB GrpcManager startStream()
11:33:13 VERB GrpcManager startStream() grpc -> event() ...
11:33:13 VERB GrpcManager startStream() grpc -> event() ... done
11:33:13 VERB GrpcManager startStream() grpc -> event peeking data or timeout ...
11:33:14 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... timeout
11:33:14 VERB GrpcManager startStream() grpc -> event peeking data or timeout ... data peeked
11:33:14 VERB GrpcManager startStream() initializing event stream ...
11:33:14 VERB GrpcManager startStream() initializing event stream ... done
11:33:14 VERB GrpcManager startStream() ... done
11:33:14 VERB GrpcManager start() starting stream ... done
11:33:14 VERB GrpcManager start() calling grpc server: start() ...
GError: from(`object`): {"gerror":"{\"code\":14,\"details\":\"No connection established\",\"message\":\"14 UNAVAILABLE: No connection established\",\"name\":\"Error\",\"stack\":\"Error: 14 UNAVAILABLE: No connection established\\n    at Object.callErrorFromStatus (/Users/cctvabu/Desktop/wechaty/node_modules/_@grpc_grpc-js@1.4.5@@grpc/grpc-js/build/src/call.js:31:26)\\n    at Object.onReceiveStatus (/Users/cctvabu/Desktop/wechaty/node_modules/_@grpc_grpc-js@1.4.5@@grpc/grpc-js/build/src/client.js:180:52)\\n    at Object.onReceiveStatus (/Users/cctvabu/Desktop/wechaty/node_modules/_@grpc_grpc-js@1.4.5@@grpc/grpc-js/build/src/client-interceptors.js:365:141)\\n    at Object.onReceiveStatus (/Users/cctvabu/Desktop/wechaty/node_modules/_@grpc_grpc-js@1.4.5@@grpc/grpc-js/build/src/client-interceptors.js:328:181)\\n    at /Users/cctvabu/Desktop/wechaty/node_modules/_@grpc_grpc-js@1.4.5@@grpc/grpc-js/build/src/call-stream.js:182:78\\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)\"}"}
    at Function.from (file:///Users/cctvabu/Desktop/wechaty/node_modules/_gerror@1.0.16@gerror/dist/esm/src/gerror/gerror.js:96:19)
    at PuppetService.<anonymous> (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty@1.10.4@wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:147:55)
    at PuppetService.emit (node:events:390:28)
    at PuppetService.emit (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty-puppet@1.10.2@wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:101:22)
    at PuppetService.start (file:///Users/cctvabu/Desktop/wechaty/node_modules/_state-switch@1.6.2@state-switch/dist/esm/src/service-ctl/service-ctl.js:70:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetService.start (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty-puppet@1.10.2@wechaty-puppet/dist/esm/src/mixins/service-mixin.js:18:13)
    at async WechatyImpl.start (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty@1.10.4@wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:48:21)
    at async WechatyImpl.start (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty@1.10.4@wechaty/dist/esm/src/wechaty-mixins/login-mixin.js:85:13)
    at async WechatyImpl.start (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty@1.10.4@wechaty/dist/esm/src/wechaty-mixins/io-mixin.js:18:13) {
  code: 2,
  details: 'GError: from(`object`): {"gerror":"{\\"code\\":14,\\"details\\":\\"No connection established\\",\\"message\\":\\"14 UNAVAILABLE: No connection established\\",\\"name\\":\\"Error\\",\\"stack\\":\\"Error: 14 UNAVAILABLE: No connection established\\\\n    at Object.callErrorFromStatus (/Users/cctvabu/Desktop/wechaty/node_modules/_@grpc_grpc-js@1.4.5@@grpc/grpc-js/build/src/call.js:31:26)\\\\n    at Object.onReceiveStatus (/Users/cctvabu/Desktop/wechaty/node_modules/_@grpc_grpc-js@1.4.5@@grpc/grpc-js/build/src/client.js:180:52)\\\\n    at Object.onReceiveStatus (/Users/cctvabu/Desktop/wechaty/node_modules/_@grpc_grpc-js@1.4.5@@grpc/grpc-js/build/src/client-interceptors.js:365:141)\\\\n    at Object.onReceiveStatus (/Users/cctvabu/Desktop/wechaty/node_modules/_@grpc_grpc-js@1.4.5@@grpc/grpc-js/build/src/client-interceptors.js:328:181)\\\\n    at /Users/cctvabu/Desktop/wechaty/node_modules/_@grpc_grpc-js@1.4.5@@grpc/grpc-js/build/src/call-stream.js:182:78\\\\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)\\"}"}\n' +
    '    at Function.from (file:///Users/cctvabu/Desktop/wechaty/node_modules/_gerror@1.0.16@gerror/dist/esm/src/gerror/gerror.js:96:19)\n' +
    '    at PuppetService.<anonymous> (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty@1.10.4@wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:147:55)\n' +
    '    at PuppetService.emit (node:events:390:28)\n' +
    '    at PuppetService.emit (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty-puppet@1.10.2@wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:101:22)\n' +
    '    at PuppetService.start (file:///Users/cctvabu/Desktop/wechaty/node_modules/_state-switch@1.6.2@state-switch/dist/esm/src/service-ctl/service-ctl.js:70:22)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async PuppetService.start (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty-puppet@1.10.2@wechaty-puppet/dist/esm/src/mixins/service-mixin.js:18:13)\n' +
    '    at async WechatyImpl.start (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty@1.10.4@wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:48:21)\n' +
    '    at async WechatyImpl.start (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty@1.10.4@wechaty/dist/esm/src/wechaty-mixins/login-mixin.js:85:13)\n' +
    '    at async WechatyImpl.start (file:///Users/cctvabu/Desktop/wechaty/node_modules/_wechaty@1.10.4@wechaty/dist/esm/src/wechaty-mixins/io-mixin.js:18:13)'
}

```

</details>

## 7. Additional context

> Add any other context about the problem here.

**Comment by huan** [comment]
Have you tried the latest version of the getting started repo? Please try to reproduce with the latest version of it and let me the result

**Comment by zhihuifanqiechaodan** [comment]
> Have you tried the latest version of the getting started repo? Please try to reproduce with the latest version of it and let me the result

`WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true`

https://github.com/wechaty/puppet-service/issues/160

Thank you. I think I found the answer

**Comment by huan** [comment]
Great to know that you solved the problem.

Our new version of Wechaty v1.x requires TLS encryption by default, and our ecosystem need to be upgraded in the following months.

**Comment by Coderrrrrrrrrrr** [comment]
> 

大佬，我复制了你的这一行代码，并通过export WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true执行后，原本报错No Connection的情况能够显示二维码了 我扫码登录 但是很快被官方强制下线 并处以限制扫码登录其他设备的警告 请问这个问题如何解决？是我哪里设置错了吗？

![image](https://user-images.githubusercontent.com/81694993/148421835-14360d92-7c3e-45bb-b1f0-a61b582f2fb6.png)

**Comment by huan** [comment]
What puppet service token are you using?

Most time you should contact your puppet service provider support, you can submit an issue at https://github.com/wechaty/puppet-supports

**Comment by zhihuifanqiechaodan** [comment]
> > 
> 
> 大佬，我复制了你的这一行代码，并通过export WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true执行后，原本报错No Connection的情况能够显示二维码了 我扫码登录 但是很快被官方强制下线 并处以限制扫码登录其他设备的警告 请问这个问题如何解决？是我哪里设置错了吗？
> 
> ![image](https://user-images.githubusercontent.com/81694993/148421835-14360d92-7c3e-45bb-b1f0-a61b582f2fb6.png)

web免费协议又被关掉了。

**Comment by yetianyue** [comment]
> > Have you tried the latest version of the getting started repo? Please try to reproduce with the latest version of it and let me the result
> 
> `WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true`
> 
> [wechaty/puppet-service#160](https://github.com/wechaty/puppet-service/issues/160)
> 
> Thank you. I think I found the answer

> 谢谢大佬，也解决了我的问题
