### ISSUE TITLE
v0.68 wechaty  Error: Cannot find module 'gerror'

### ISSUE THREAD

**Issue by caihongyu2022** [wechaty/wechaty#2336]
my local npm and node version, i don't understand where is the problem...
```
n@naverdeMacBook-Pro-6 ~ % node -v
v16.13.1
n@naverdeMacBook-Pro-6 ~ % npm -v
8.1.2
```
error:
````
wanted: {"node":">=16","npm":">=7"} (current: {"node":"14.18.1","npm":"6.14.15"})
01:42:01 INFO PuppetManager install(wechaty-puppet-wechat@>=0.28) done
Error: Cannot find module 'gerror'
````
logs
````
Starting Docker Container for Wechaty v0.68.6 with Node.js v14.18.1 ...
Working directory: /bot
Executing ts-node --type-check src/typescript.ts
01:40:33 INFO PuppetManager install(wechaty-puppet-wechat@>=0.28) please wait ...
npm: 

npm: npm 
npm: WARN notsup Unsupported engine for wechaty-puppet-wechat@1.10.5: wanted: {"node":">=16","npm":">=7"} (current: {"node":"14.18.1","npm":"6.14.15"})
npm WARN notsup Not compatible with your version of node/npm: wechaty-puppet-wechat@1.10.5

npm: npm WARN notsup
npm:  Unsupported engine for state-switch@1.6.3: wanted: {"node":">=16","npm":">=7"} (current: {"node":"14.18.1","npm":"6.14.15"})
npm WARN notsup Not compatible with your version of node/npm: state-switch@1.6.3

npm: npm WARN
npm:  @typescript-eslint/eslint-plugin@4.33.0 requires a peer of @typescript-eslint/parser@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm: npm WARN
npm:  tslint-eslint-rules@5.4.0 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm: npm WARN tslint-eslint-rules@5.4.0 requires a peer of typescript@^2.2.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.

npm: npm WARN
npm:  wechaty-puppet-wechat@1.10.5 requires a peer of wechaty-puppet@^1.10.1 but none is installed. You must install peer dependencies yourself.

npm: npm WARN state-switch@1.6.3 requires a peer of gerror@^1.0.16 but none is installed. You must install peer dependencies yourself.

npm: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):

npm: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm: 

01:42:01 INFO PuppetManager install(wechaty-puppet-wechat@>=0.28) done
Error: Cannot find module 'gerror'
Require stack:
- /wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/puppet-wechat.js
- /wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/mod.js
- /wechaty/dist/src/puppet-manager.js
- /wechaty/dist/src/wechaty.js
- /wechaty/dist/src/mod.js
- /bot/src/typescript.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/wechaty/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:37:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-wechat/src/mod.ts:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at /wechaty/src/puppet-manager.ts:136:26
    at async Function.resolveName (/wechaty/src/puppet-manager.ts:136:26)
    at async Function.resolve (/wechaty/src/puppet-manager.ts:88:24)
    at async Wechaty.initPuppet (/wechaty/src/wechaty.ts:400:28)
    at async Wechaty.start (/wechaty/src/wechaty.ts:728:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/puppet-wechat.js',
    '/wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/mod.js',
    '/wechaty/dist/src/puppet-manager.js',
    '/wechaty/dist/src/wechaty.js',
    '/wechaty/dist/src/mod.js',
    '/bot/src/typescript.ts'
  ]
}
01:42:01 ERR Wechaty start() exception: Cannot find module 'gerror'
Require stack:
- /wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/puppet-wechat.js
- /wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/mod.js
- /wechaty/dist/src/puppet-manager.js
- /wechaty/dist/src/wechaty.js
- /wechaty/dist/src/mod.js
- /bot/src/typescript.ts
Bot error: Error: Cannot find module 'gerror'
Require stack:
- /wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/puppet-wechat.js
- /wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/mod.js
- /wechaty/dist/src/puppet-manager.js
- /wechaty/dist/src/wechaty.js
- /wechaty/dist/src/mod.js
- /bot/src/typescript.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/wechaty/node_modules/@cspotcode/source-map-support/source-map-support.js:679:30)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:37:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/wechaty/node_modules/wechaty-puppet-wechat/src/mod.ts:19:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at /wechaty/src/puppet-manager.ts:136:26
    at async Function.resolveName (/wechaty/src/puppet-manager.ts:136:26)
    at async Function.resolve (/wechaty/src/puppet-manager.ts:88:24)
    at async Wechaty.initPuppet (/wechaty/src/wechaty.ts:400:28)
    at async Wechaty.start (/wechaty/src/wechaty.ts:728:7) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/puppet-wechat.js',
    '/wechaty/node_modules/wechaty-puppet-wechat/dist/cjs/src/mod.js',
    '/wechaty/dist/src/puppet-manager.js',
    '/wechaty/dist/src/wechaty.js',
    '/wechaty/dist/src/mod.js',
    '/bot/src/typescript.ts'
  ]
}
01:42:01 WARN Wechaty stop() puppet.stop() exception: Cannot read property 'stop' of undefined

 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.chatie.io
  _____      _ _      ___   
 | ____|_  _(_) |_   / _ \  
 |  _| \ \/ / | __| | | | | 
 | |___ >  <| | |_  | |_| | 
 |_____/_/\_\_|\__|  \___/  

`````

**Comment by huan** [comment]
Replied at https://github.com/wechaty/wechaty/issues/2333#issuecomment-1001342535

**Comment by shangdev** [comment]
@huan 

遇到同样的问题。

首先，我将 wechaty-puppet-wechat 版本定为 0.27.0,：
```
"dependencies": {
    "isomorphic-fetch": "^3.0.0",
    "wechaty": "^0.68.1",
    "wechaty-puppet-wechat": "0.27.0"
  }
```

然后 npm start ，没有 geterror 错误出现。

但是下一次再 npm start 时，geterror 出现了，是因为第一次 npm start 时0.27.0自动升级到了 0.28.0：
```
09:17:11 INFO PuppetManager install(wechaty-puppet-wechat@>=0.28) done
```

此时，查看版本信息：npm list --depth=0 时显示：
```
+-- wechaty@0.68.1
`-- wechaty-puppet-wechat@0.27.0
```

但是，再次 npm install 后，提示：`removed 153 packages and audited 424 packages in 4.508s`

还是因为 wechaty-puppet-wechat 自动升级到了 0.28.0.

**Comment by huan** [comment]
@shangdev Thanks for the reporting.

Can you solve this problem by install the `gerror` module? It's just a tiny helper module:

```sh
npm install gerror
```

**Comment by shangdev** [comment]
@huan 

安装 gerror 库后问题解决。

**Comment by huan** [comment]
Glad to know that this helps.

This workaround should be safe and can be recommended to solve this issue.
