### ISSUE TITLE
正常使用的程序，今天微信扫码不能登录了

### ISSUE THREAD

**Issue by 156874** [wechaty/wechaty#2338]
🚨 The issue tracker is not for questions 🚨
报错如下，请问是我哪里配置错了么？
https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FQbIALbyCtw%3D%3D
17:35:23 WARN PuppetWeChatBridge onDialog() page.on(dialog) type:type() {
        return this._type;
    } message:登录失败。
(node:16196) UnhandledPromiseRejectionWarning: Error: type() {
        return this._type;
    }(登录失败。)
    at PuppetWeChat.<anonymous> (D:\webchatBot\wechatBot\node_modules\wechaty\dist\src\wechaty.js:273:44)
    at PuppetWeChat.emit (events.js:315:20)
    at PuppetWeChat.EventEmitter.emit (domain.js:485:12)
    at Bridge.<anonymous> (D:\webchatBot\wechatBot\node_modules\wechaty-puppet-wechat\dist\src\puppet-wechat.js:203:45)
    at Bridge.emit (events.js:315:20)
    at Bridge.EventEmitter.emit (domain.js:485:12)
    at Bridge.onDialog (D:\webchatBot\wechatBot\node_modules\wechaty-puppet-wechat\dist\src\bridge.js:129:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by xuexiaoao** [comment]
+1

**Comment by AsakuraFuuko** [comment]
+1

**Comment by xlgzsgf** [comment]
+1

**Comment by SuMaiKaDe** [comment]
微信把uos封了

**Comment by Arrake-One** [comment]
+1

**Comment by huan** [comment]
Merge to:

- https://github.com/wechaty/puppet-wechat/issues/192

**Comment by secreter** [comment]
+1
