### ISSUE TITLE
How to send a message with location information

### ISSUE THREAD

**Issue by fabian4** [wechaty/wechaty#2353]
I may try this way but it doesn't work
~~~ts
const contact = await bot.Contact.find({ id: 'xxxxxxxxx' })
const location = {
  accuracy  : 11,
  address   : '北京市北京市海淀区45 Chengfu Rd',
  latitude  : 39.995120999999997,
  longitude : 116.334154,
  name      : '东升乡人民政府(海淀区成府路45号)',
}
await contact.say(location)
~~~

It shows in the console that
~~~bash
15:23:36 VERB Contact say([object Object])
15:44:22 ERR Config ###########################
15:44:22 ERR Config Wechaty uncaughtException: Error: unsupported arg: [object Object]
    at file:///D:/juzi/puppet-walnut/node_modules/wechaty/src/sayable/deliver-sayable.ts:91:11
    at WechatifiedUserClass.say (file:///D:/juzi/puppet-walnut/node_modules/wechaty/src/user-modules/contact.ts:328:87)
    at file:///D:/juzi/puppet-walnut/examples/chatbot.ts:23:15 unhandledRejection
15:44:22 ERR Config ###########################
~~~

I thought it may not fit the right type to pass the condition
~~~ts
//...

  } else if (LocationImpl.validInstance(sayable)) {

//...

  } else {
    throw new Error('unsupported arg: ' + sayable)
  }
~~~

**Comment by huan** [comment]
I think the latest version of the Wechaty & Puppet (version 1.15 or above) should have no problem with the related code.

Please let me know if you have this issue with the newest version.
