### ISSUE TITLE
wechaty@1.x message.toUrlLink() Error: UrlLinkImpl: Wechaty User Class (WUC) can not be instantiated directly!

### ISSUE THREAD

**Issue by zhihuifanqiechaodan** [wechaty/wechaty#2358]
> Important：Please file the issue follow the template, or we won't be able to help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

    ```sh
    rm -rf package-lock.json
    rm -rf node_modules
    npm install
    ```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

> What is your wechaty version?

Answer: v1.10.4

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer:  service

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: wechaty-puppet-service

> What is your node version? (run `node --version`)

Answer:  v16.13.0

> What os are you using

Answer: macOS monterey v12.1

## 2. Describe the bug

>  message.toUrlLink() Error: UrlLinkImpl: Wechaty User Class (WUC) can not be instantiated directly!
## 3. To Reproduce

> This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)**

bot.on('message', async message => {
        console.log(await message.toUrlLink());
})

## 4. Expected behavior

> Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

> If applicable, add screenshots to help explain your problem. But the log message must be in plain text instead of screenshot.

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

-> Make sure to copy/paste the full (instead of only fragments) log message in text format (instead of image/screenshot) at here


15:38:39 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload(len:43)})
15:38:39 SILL PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT(1), payload:"{"data":"[object Object]","timeout":120000}"})
15:38:51 VERB PuppetService onGrpcStreamEvent({type:EVENT_TYPE_MESSAGE(2), payload(len:23)})
15:38:51 SILL PuppetService onGrpcStreamEvent({type:EVENT_TYPE_MESSAGE(2), payload:"{"messageId":"1051892"}"})
15:38:51 VERB Message find({"id":"1051892"})
15:38:51 VERB Message findAll({"id":"1051892"})
15:38:51 VERB PuppetMessageMixin messageSearch({"id":"1051892"})
15:38:51 VERB PuppetMessageMixin messagePayload(1051892)
15:38:51 SILL PuppetMessageMixin messagePayloadCache(1051892) cache MISS
15:38:51 VERB PuppetService messageRawPayload(1051892)
15:38:51 SILL PuppetMessageMixin messagePayload(1051892) cache SET
15:38:51 VERB Message static load(1051892)
15:38:51 VERB Message constructor(1051892) for class WechatifiedMessageImpl
15:38:51 VERB Message ready()
15:38:51 VERB PuppetMessageMixin messagePayload(1051892)
15:38:51 SILL Room find({"id":"R:10696050959023730"})
15:38:51 SILL Room ready()
15:38:51 SILL Contact find({"id":"7881302689943729"})
15:38:51 SILL Contact ready() @ Puppet<PuppetService>(wechaty-puppet-wechat) with id="7881302689943729"
15:38:51 SILL Contact ready() isReady() true
15:38:51 VERB Message toUrlLink()
15:38:51 VERB PuppetService messageUrl(1051892)
15:38:52 ERR Config ###########################
15:38:52 ERR Config Wechaty unhandledRejection: Error: UrlLinkImpl: Wechaty User Class (WUC) can not be instantiated directly!
See: https://github.com/wechaty/wechaty/issues/1217
    at throwWechatifyError (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-mixins/wechatify.js:18:11)
    at new AbstractWechatifyMixin (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-mixins/wechatify.js:32:17)
    at new UrlLinkMixin (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-modules/url-link.js:88:9)
    at new ValidationUserClass (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-mixins/validation.js:18:5)
    at new UrlLinkImpl (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-modules/url-link.js:110:1)
    at WechatifiedUserClass.toUrlLink (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-modules/message.js:817:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WechatyImpl.<anonymous> (file:///Users/cctvabu/robots/wechaty-puppet-wechat/src/main.js:39:21) [object Promise]
15:38:52 ERR Config ###########################
15:38:52 ERR Config process.on(unhandledRejection) promise.catch(UrlLinkImpl: Wechaty User Class (WUC) can not be instantiated directly!
See: https://github.com/wechaty/wechaty/issues/1217)
Config Error: UrlLinkImpl: Wechaty User Class (WUC) can not be instantiated directly!
See: https://github.com/wechaty/wechaty/issues/1217
    at throwWechatifyError (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-mixins/wechatify.js:18:11)
    at new AbstractWechatifyMixin (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-mixins/wechatify.js:32:17)
    at new UrlLinkMixin (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-modules/url-link.js:88:9)
    at new ValidationUserClass (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-mixins/validation.js:18:5)
    at new UrlLinkImpl (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-modules/url-link.js:110:1)
    at WechatifiedUserClass.toUrlLink (file:///Users/cctvabu/robots/wechaty-puppet-wechat/node_modules/wechaty/dist/esm/src/user-modules/message.js:817:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WechatyImpl.<anonymous> (file:///Users/cctvabu/robots/wechaty-puppet-wechat/src/main.js:39:21)
(node:9728) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)

```

</details>

## 7. Additional context

> Add any other context about the problem here.

**Comment by huan** [comment]
Good catch, and thank you very much for providing the detailed information which is a great help for fixing it!

Should be fixed with `wechaty@1.13.4` or above versions.
