### ISSUE TITLE
TemplateStringArray Error

### ISSUE THREAD

**Issue by yzh1255245824** [wechaty/wechaty#2370]
I'm sorry to disturb you late at night.

When I try to send a message in a room and mention all members like this:
```javascript
const contactList = await room.memberAll();
await room.say(str, contactList);
```

The console outputs the following logs:
```shell
3|chatbot  | Error: mentionList must be contact when not using TemplateStringArray function call.
3|chatbot  |     at WechatifiedRoom.say (/home/wechat-bot-padlocal/node_modules/wechaty/dist/src/user/room.js:389:27)
3|chatbot  |     at Job.job (/home/wechat-bot-padlocal/listeners/on-login.js:42:20)
3|chatbot  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

What is the `TemplateStringArray`? Am I using the API the wrong way?

Look forward to your reply!

**Comment by huan** [comment]
According to the [API docs](https://wechaty.js.org/docs/api/room#roomsaytext-or-contact-or-file-or-urllink-or-miniprogram-mentionlist--promise-void), you need to change:

```diff
- await room.say(str, contactList);
+ await room.say(str, ...contactList);
```

The `TemplateStringArray` is for the below usage:

```ts
await room.say(`Hello ${contact} World`)
```

Which will mention the `contact` and shows text `Hello @contact World`.

**Comment by huan** [comment]
> I see! Thank you very much for your reply. I know the Chinese of TemplateStringArray, but I can't relate to this word, hahaha.

I don't think the `TemplateStringsArray` is meaningful in Chinese at all.

It's a keyword from ECMAScript specification, you can learn it from:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
