### ISSUE TITLE
run example http://pad-local.com/#/learn failed.

### ISSUE THREAD

**Issue by RustChater** [wechaty/wechaty#2391]
When I run example http://pad-local.com/#/learn step-by-step, got error at last step "npm run demo"

Env:
```
wechaty-puppet-padlocal-demo: 0.1.2
wechaty: 0.60.12
wechaty-puppet-padlocal: 0.4.2
node: v17.8.0
npm: 8.5.5
OS: macOS BigSur 11.6 intel
```

Error:
```
➜  wechaty-puppet-padlocal-demo git:(master) ✗ sudo npm run demo

> wechaty-puppet-padlocal-demo@0.1.2 demo
> ./node_modules/.bin/ts-node main.ts


/Users/xxx/tmp/wechaty2/wechaty-puppet-padlocal-demo/node_modules/ts-node/src/index.ts:513
return new TSError(diagnosticText, diagnosticCodes)
^
TSError: ⨯ Unable to compile TypeScript:
main.ts:13:5 - error TS2322: Type 'PuppetPadlocal' is not assignable to type '"wechaty-puppet-hostie" | "wechaty-puppet-puppeteer" | "wechaty-puppet-service" | "wechaty-puppet-mock" | "wechaty-puppet-wechat" | "wechaty-puppet-wechat4u" | "wechaty-puppet-padlocal" | ... 6 more ... | Puppet'.
Type 'PuppetPadlocal' is missing the following properties from type 'Puppet': cacheContactPayload, cacheFriendshipPayload, cacheMessagePayload, cacheRoomPayload, and 17 more.

13     puppet,
~~~~~~

node_modules/wechaty/dist/src/wechaty.d.ts:13:5
13     puppet?: PuppetModuleName | Puppet;
~~~~~~
The expected type comes from property 'puppet' which is declared here on type 'WechatyOptions'

    at createTSError (/Users/xxx/tmp/wechaty2/wechaty-puppet-padlocal-demo/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/xxx/tmp/wechaty2/wechaty-puppet-padlocal-demo/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/xxx/tmp/wechaty2/wechaty-puppet-padlocal-demo/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/xxx/tmp/wechaty2/wechaty-puppet-padlocal-demo/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/xxx/tmp/wechaty2/wechaty-puppet-padlocal-demo/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/xxx/tmp/wechaty2/wechaty-puppet-padlocal-demo/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
```

**Comment by huan** [comment]
Currently, we are working on upgrading the Puppet Padlocal to the latest version v1.x, you can learn the progress from this PR:

- https://github.com/wechaty/puppet-padlocal/pull/125

After it has been upgraded, we recommended using the Wechaty community officially getting started repo at https://github.com/wechaty/getting-started and it should be able to work out-of-the-box, which is very convenient to the newcomers.

For now, as a workaround, I'm using a Wechaty Token Gateway with Puppet Padlocal so that we can use the new Wechaty v1.x with the old Puppet Padlocal, and it works great with our community bot [Friday BOT](https://github.com/wechaty/friday).

You can learn how the Friday BOT creates its Wechaty Token Gateway from [this script](https://github.com/wechaty/friday/blob/main/scripts/token-gateway.sh). And after running this script, you can use the new Wechaty Puppet Service Token (which is compatible with Wechaty v1.x) and use it with the latest Wechaty v1.x code.

Please read those codes and I hope you can make it work soon. If you run into any hard-to-solve issue, unfortunately, please feel free to create a reproducible repo and I can take a look at it for you.

Good luck!
