### ISSUE TITLE
1.19.10版本下无法按照教程发送小程序

### ISSUE THREAD

**Issue by zest2020** [wechaty/wechaty#2426]
```
"wechaty": "^1.19.10",
"wechaty-puppet": "^1.19.6",
"wechaty-puppet-padlocal": "^1.11.18",
```
相关版本如上，按照教程代码测试发送小程序无法成功

### 测试代码
```
const { MiniProgram } = require('wechaty');
const miniProgramPayload = new MiniProgram ({
                appid : 'wxd4185d00bf7e08ac',
                title : '寄快递，用顺丰',
                pagePath : 'pages/tabBar/index/index.html',
                description : '顺丰速运+',
                thumbUrl : '3057020100044b3049020100020479e2427002032f54cf02049ab2066f020462c154b7042437336232373863362d303165342d343061322d616333322d3963633135383030333164380204011400030201000405004c56fb00',
                thumbKey : 'ba7e3539e0a8ccb6008e385fcffa089f',
              })
await message.say(miniProgramPayload)
```

### 错误提示
```
TypeError: MiniProgram is not a constructor
    at WechatyImpl.pluginTest (/Users/lovehxy/Documents/iCollections/工作/project/wechat/wechat_bot_hnuahe/wechat_bot_ts/plugin/test/test.ts:26:40)
    at WechatyImpl.emit (node:events:539:35)
    at WechatyImpl.emit (node:domain:475:12)
    at WechatyImpl.emit (/Users/loh/Documents/iCollections/工作/project/wechat/wechat_bot/wechat_bot_ts/node_modules/_wechaty@1.20.2@wechaty/src/wechaty-mixins/gerror-mixin.ts:44:22)
    at PuppetPadlocal.<anonymous> (/Users/loh/Documents/iCollections/工作/project/wechat/wechat_bot/wechat_bot_ts/node_modules/_wechaty@1.20.2@wechaty/src/wechaty-mixins/puppet-mixin.ts:281:22)
```

**Comment by zhaoeryu** [comment]
同问，官方文档中没有找到相关介绍
