### ISSUE TITLE
api通过群名称获取群实体，报超时错误

### ISSUE THREAD

**Issue by shenjichenai** [wechaty/wechaty#2433]
`var bot = new Wechaty({
  puppet: "wechaty-puppet-service",
  puppetOptions: {
    token,
  },
});
let current = new RegExp(roomName);
  const currentRoom = await bot.Room.find({ topic: current });
`
执行await bot.Room.find 回报超时错误。
我有三个群，一样的代码，有两个群能用，有一个群执行到这段代码就会报超时错误。
**下面是我的错误日志**：
Error: 2 UNKNOWN: Error: ERR_REQUEST_TIMEOUT ApiType: NEW_SEND_TEXT_MSG, requestId: 85c39f84-70fc-403c-8dd7-e5fb75857ee8, counter: 2
    at Timeout._onTimeout (C:\juzi\node_modules\@juzibot\wechaty-puppet-wxwork\dist\src\work\request\base-request.js:168:28)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
    at Object.callErrorFromStatus (/service-manage/robot_order/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/service-manage/robot_order/node_modules/@grpc/grpc-js/build/src/client.js:189:52)
    at Object.onReceiveStatus (/service-manage/robot_order/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)
    at Object.onReceiveStatus (/service-manage/robot_order/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /service-manage/robot_order/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 2,
  details: 'Error: ERR_REQUEST_TIMEOUT ApiType: NEW_SEND_TEXT_MSG, requestId: 85c39f84-70fc-403c-8dd7-e5fb75857ee8, counter: 2\n' +
    '    at Timeout._onTimeout (C:\\juzi\\node_modules\\@juzibot\\wechaty-puppet-wxwork\\dist\\src\\work\\request\\base-request.js:168:28)\n' +
    '    at listOnTimeout (node:internal/timers:557:17)\n' +
    '    at processTimers (node:internal/timers:500:7)',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}

**Comment by shenjichenai** [comment]
这个问题还是偶发的，有时候重启很多次都不能解决，然后过一段时间又好了。这个功能感觉很不稳定啊

**Comment by Yongest** [comment]
GError: execute proxyWechaty(init) error: 503, init() without a ready angular env 请问这个是什么原因
