### ISSUE TITLE
Wechaty PadLocal couldn't send messages, logout,... after logged in 2-3 days

### ISSUE THREAD

**Issue by Hamlet626** [wechaty/wechaty#2442]
## 1. Versions

I am using padlocal token with dependencies
"wechaty": "^1.19.10",
"wechaty-puppet-padlocal": "^1.20.1",
"wechaty-puppet": "^1.19.6",
node v18.1.0 ,
on Linux/UNIX.

## 2. Describe the bug

So after scanning QRcode logged in for 2-3 days, operations like sending messages in room, logging out gets error below; findAll() rooms doesn't fetch newest room list.

Sending messages, logout error:
ERR Config Wechaty unhandledRejection: VError: [tid:43769095] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:43769095] wechat request io error
![51662485796_ pic_hd](https://user-images.githubusercontent.com/26908521/188707301-993806f4-2497-4605-9cf7-c1ba7f4da4ce.jpg)

on pad-local.com it shows logged off as below, while on WeChat it shows logged in on another device and bot.isLoggedIn is still true.
<img width="98" alt="Screen Shot 2022-09-06 at 1 39 55 PM" src="https://user-images.githubusercontent.com/26908521/188734183-cf2180ed-2791-429f-99ae-a57944cadae0.png">

## 3. To Reproduce

1. go to https://github.com/Hamlet626/wechaty-server, download code
2. follow README.md in https://github.com/Hamlet626/wechaty-server. 
3. login by scanning QRcode and wait for 2-3 days, then sending messages, logout, ... wouldn't work.
    console will show "wechat request io error" mentioned above

## 4. Expected behavior
sending messages, logout,... functions should work as usual.

## 5. Actual behavior

every functions works as usual on first 2-3 days,
while after that room.say(),bot.logout(),... doesn't work and will show error

## 6. Full Output Logs

ERROR TEXT:
16:57:12 ERR Config ###########################
16:57:12 ERR Config process.on(unhandledRejection) promise.catch([tid:43769095] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:4
3769095] wechat request io error)
Config SubRequestCancelError [VError]: [tid:43769095] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:43769095] wechat request io
 error
    at Request._failAllPendingRequest (/app/node_modules/padlocal-client-ts/dist/Request.js:265:19)
    at ClientDuplexStreamImpl.<anonymous> (/app/node_modules/padlocal-client-ts/dist/Request.js:56:18)
    at ClientDuplexStreamImpl.emit (node:events:394:28)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:413:28)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  jse_shortmsg: '[tid:43769095] request has been cancelled for reason: SERVER_ERROR',
  jse_cause: Error: 2 UNKNOWN: [tid:43769095] wechat request io error
      at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
      at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:413:49)
      at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
      at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
      at processTicksAndRejections (node:internal/process/task_queues:78:11)
  for call at
      at ServiceClientImpl.makeBidiStreamRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:398:30)
      at ServiceClientImpl.action (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
      at new Request (/app/node_modules/padlocal-client-ts/dist/Request.js:41:51)
      at PadLocalClient.createRequest (/app/node_modules/padlocal-client-ts/dist/PadLocalClient.js:93:21)
      at PadLocalClient.<anonymous> (/app/node_modules/padlocal-client-ts/dist/PadLocalClient.js:125:25)
      at Generator.next (<anonymous>)
      at /app/node_modules/padlocal-client-ts/dist/PadLocalClient.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (/app/node_modules/padlocal-client-ts/dist/PadLocalClient.js:4:12)
      at PadLocalClient.request (/app/node_modules/padlocal-client-ts/dist/PadLocalClient.js:124:16) {
    code: 2,
    details: '[tid:43769095] wechat request io error',
    metadata: Metadata { internalRepr: [Map], options: {} }
  },
  jse_info: {},
  reason: 1
}

## 7. Additional context

related https://github.com/wechaty/puppet-padlocal/issues/195

I was deploying a server with Wechaty as a functionality on AWS. I used API for Wechaty operation, but some API(such as say in room, logout)doesn't work after logged in 2-3 days, some(such as findAll rooms) just doesn't fetch up-to-date data.

**Comment by Hamlet626** [comment]
有大佬知道这种情况是已经掉线了吗，还是什么原因吗？
微信上显示其他设备还在登陆，bot.isLoggedIn也是true，然后pad-local.com那个网站token那是未登陆。一些主动操作的方程比如room.say(),bot.logout() 都会出那个io error，然后room.findAll()这些好像一直是之前的list没变。
如果掉线的话是因为手机那边微信掉了吗，还是正常就会过几天要重新登陆吗？

提前感谢！！

**Comment by liuguangrui123** [comment]
这个问题也卡我好几天了 不清楚具体原因

**Comment by JankinHou** [comment]
> 这个问题也卡我好几天了 不清楚具体原因

有得到解决吗
