### ISSUE TITLE
AssertionError [ERR_ASSERTION]: 1204 == 0

### ISSUE THREAD

**Issue by acheong08** [wechaty/wechaty#2460]
## 1. Versions

> What is your wechaty version?

Answer: 1.20.2

> Which puppet are you using for wechaty? (puppeteer/padlocal/service...)

Answer: puppeteer

> What is your wechaty-puppet-XXX（padchat/puppeteer/） version?

Answer: 13.5.1

> What is your node version? (run `node --version`)

Answer: v16.17.0

> What os are you using

Answer: Ubuntu 22.04.1 LTS x86_64

## 2. Describe the bug

```
AssertionError [ERR_ASSERTION]: 1204 == 0
```

## 3. To Reproduce

1. Run https://github.com/fuergaosi233/wechat-chatgpt
2. Scan QR code
3. Send message

## 4. Expected behavior

Send message without errors

## 5. Actual behavior
```
AssertionError [ERR_ASSERTION]: 1204 == 0
    at Object.equal (/home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechat4u/src/util/global.js:53:14)
    at /home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechat4u/src/core.js:477:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageSendText (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechaty-puppet-wechat4u/src/puppet-wechat4u.ts:765:5)
    at async WechatifiedUserClass.say (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechaty/src/user-modules/contact.ts:338:19)
    at async ChatGPTBot.trySay (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/chatgpt.ts:268:7)
    at async ChatGPTBot.onPrivateMessage (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/chatgpt.ts:310:5)
    at async ChatGPTBot.onMessage (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/chatgpt.ts:335:16)
    at async WechatyImpl.<anonymous> (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/main.ts:32:9) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1204,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '发送文本信息失败'
}
```

## 6. Full Output Logs

> Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

22:49:11 SILL PuppetMessageMixin messagePayload(2103737506276419979) cache SET
22:49:11 SILL PuppetMessageMixin messagePayload(4390671523421041540) cache SET
22:49:11 VERB Message static load(2103737506276419979)
22:49:11 VERB Message constructor(2103737506276419979) for class WechatifiedMessageImpl
22:49:11 VERB Message ready()
22:49:11 VERB PuppetMessageMixin messagePayload(2103737506276419979)
22:49:11 VERB Message static load(4390671523421041540)
22:49:11 VERB Message constructor(4390671523421041540) for class WechatifiedMessageImpl
22:49:11 VERB Message ready()
22:49:11 VERB PuppetMessageMixin messagePayload(4390671523421041540)
22:49:11 SILL Contact find({"id":"@b209bfbd0d713e5842484547e8280dd5b885865faf1d54c61092732cad335d01"})
22:49:11 SILL PuppetLoginMixin get currentUserId()
22:49:11 SILL Contact ready() @ Puppet<PuppetWechat4u>(wechat-assistant) with id="@b209bfbd0d713e5842484547e8280dd5b885865faf1d54c61092732cad335d01"
22:49:11 SILL Contact ready() isReady() true
22:49:11 SILL Contact find({"id":"@b209bfbd0d713e5842484547e8280dd5b885865faf1d54c61092732cad335d01"})
22:49:11 SILL PuppetLoginMixin get currentUserId()
22:49:11 SILL Contact ready() @ Puppet<PuppetWechat4u>(wechat-assistant) with id="@b209bfbd0d713e5842484547e8280dd5b885865faf1d54c61092732cad335d01"
22:49:11 SILL Contact ready() isReady() true
22:49:11 SILL Contact find({"id":"@b209bfbd0d713e5842484547e8280dd5b885865faf1d54c61092732cad335d01"})
22:49:11 SILL PuppetLoginMixin get currentUserId()
22:49:11 SILL Contact ready() @ Puppet<PuppetWechat4u>(wechat-assistant) with id="@b209bfbd0d713e5842484547e8280dd5b885865faf1d54c61092732cad335d01"
22:49:11 SILL Contact ready() isReady() true
22:49:11 SILL Contact find({"id":"@b209bfbd0d713e5842484547e8280dd5b885865faf1d54c61092732cad335d01"})
22:49:11 SILL PuppetLoginMixin get currentUserId()
22:49:11 SILL Contact ready() @ Puppet<PuppetWechat4u>(wechat-assistant) with id="@b209bfbd0d713e5842484547e8280dd5b885865faf1d54c61092732cad335d01"
22:49:11 SILL Contact ready() isReady() true
22:49:11 SILL PuppetLoginMixin get currentUserId()
Message: Message#Text[🗣Contact<Antonio>]        !ask hello
22:49:11 SILL PuppetLoginMixin get currentUserId()
22:49:11 VERB ContactSelf name()
🎯 Triggered ChatGPT: !ask hello
22:49:12 SILL PuppetLoginMixin get currentUserId()
22:49:12 SILL PuppetLoginMixin get currentUserId()
Message: Message#Unknown[🗣Contact<Antonio>]
22:49:12 SILL PuppetLoginMixin get currentUserId()
22:49:12 VERB ContactSelf name()
22:49:12 SILL PuppetLoginMixin get currentUserId()
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=13/52
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=13/53
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=6/53
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=5/53
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=3/53
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=7/57
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=14/65
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=85/128
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=4/128
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=12/129
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=5/130
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=109/161
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=4/162
22:49:18 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=13/164
22:49:21 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=50/164
22:49:21 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=50/164
22:49:24 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=50/164
22:49:24 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=13/164
22:49:24 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=50/164
22:49:25 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=50/164
22:49:25 SILL PuppetWechat4u initHookEvents() wechat4u.on(contacts-updated) new/total contacts.length=17/164
Hello! I'm Assistant, a large language model trained by OpenAI. Is there anything I can help you with? I'm here to provide information and answer questions to the best of my ability. Just let me know if you have any questions.
22:49:33 VERB Contact say(Hello! I'm Assistant, a large language model trained by OpenAI. Is there anything I can help you with? I'm here to provide information and answer questions to the best of my ability. Just let me know if you have any questions.)
22:49:33 VERB PuppetWechat4u messageSend(@b209bfbd0d713e5842484547e8280dd5b885865faf1d54c61092732cad335d01, Hello! I'm Assistant, a large language model trained by OpenAI. Is there anything I can help you with? I'm here to provide information and answer questions to the best of my ability. Just let me know if you have any questions.)
AssertionError [ERR_ASSERTION]: 1204 == 0
    at Object.equal (/home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechat4u/src/util/global.js:53:14)
    at /home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechat4u/src/core.js:477:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageSendText (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechaty-puppet-wechat4u/src/puppet-wechat4u.ts:765:5)
    at async WechatifiedUserClass.say (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechaty/src/user-modules/contact.ts:338:19)
    at async ChatGPTBot.trySay (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/chatgpt.ts:268:7)
    at async ChatGPTBot.onPrivateMessage (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/chatgpt.ts:310:5)
    at async ChatGPTBot.onMessage (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/chatgpt.ts:335:16)
    at async WechatyImpl.<anonymous> (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/main.ts:32:9) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1204,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '发送文本信息失败'
}
22:49:39 SILL PuppetWechat4u monkeyPatchHook(wechat4u, syncCheck, func) funcNew()
22:49:39 SILL PuppetWechat4u monkeyPatch() monkeyPatchHook() wechat4u.syncCheck()
22:50:06 SILL PuppetWechat4u monkeyPatchHook(wechat4u, syncCheck, func) funcNew()
22:50:06 SILL PuppetWechat4u monkeyPatch() monkeyPatchHook() wechat4u.syncCheck()
```

</details>

## 7. Additional context

Real name authenticated via passport

**Comment by sooboy** [comment]
```
uncaughtException AssertionError [ERR_ASSERTION]: 1204 == 0
    at Object.equal (/root/work/demo/wechaty-demo/node_modules/wechat4u/src/util/global.js:53:14)
    at /root/work/demo/wechaty-demo/node_modules/wechat4u/src/core.js:477:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageSendText (/root/work/demo/wechaty-demo/node_modules/wechaty-puppet-wechat4u/src/puppet-wechat4u.ts:765:5)
    at async WechatifiedUserClass.say (/root/work/demo/wechaty-demo/node_modules/wechaty/src/user-modules/contact.ts:338:19)
    at async WechatyImpl.onMessage (/root/work/demo/wechaty-demo/index.ts:31:9) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1204,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '发送文本信息失败'
}
```
同样的错误

**Comment by acheong08** [comment]
This happens when you try to send a message to yourself. My solution was to send it to filehelper instead

**Comment by minminou** [comment]
> This happens when you try to send a message to yourself. My solution was to send it to filehelper instead

I still have this error even if I send to filehelper. 
This WeChat account was also authenticated via passport, not sure if this is the issue?
