### ISSUE TITLE
 message:登录失败

### ISSUE THREAD

**Issue by sk142857** [wechaty/wechaty#2485]
[3] https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FAfFgLK03DQ%3D%3D
Scan QR Code above to log in: 
07:23:47 WARN PuppetWeChatBridge onDialog() page.on(dialog) type:type() {
        return this._type;
    } message:登录失败。
Bot error: GError: from(`object`): [object Object]
    at Function.from (file:///wechaty/node_modules/gerror/dist/esm/src/gerror/gerror.js:87:19)
    at PuppetWeChat.<anonymous> (file:///wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:147:55)
    at PuppetWeChat.emit (node:events:390:28)
    at PuppetWeChat.emit (node:domain:475:12)
    at PuppetWeChat.emit (file:///wechaty/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:101:22)
    at Bridge.<anonymous> (file:///wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:169:45)
    at Bridge.emit (node:events:390:28)
    at Bridge.emit (node:domain:475:12)
    at Bridge.onDialog (file:///wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:128:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'GError: from(`object`): [object Object]\n' +
    '    at Function.from (file:///wechaty/node_modules/gerror/dist/esm/src/gerror/gerror.js:87:19)\n' +
    '    at PuppetWeChat.<anonymous> (file:///wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:147:55)\n' +
    '    at PuppetWeChat.emit (node:events:390:28)\n' +
    '    at PuppetWeChat.emit (node:domain:475:12)\n' +
    '    at PuppetWeChat.emit (file:///wechaty/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:101:22)\n' +
    '    at Bridge.<anonymous> (file:///wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/puppet-wechat.js:169:45)\n' +
    '    at Bridge.emit (node:events:390:28)\n' +
    '    at Bridge.emit (node:domain:475:12)\n' +
    '    at Bridge.onDialog (file:///wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/bridge.js:128:14)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}
07:23:47 VERB PuppetWeChatBridge onLoad() page.url=https://wx.qq.com/?target=t
07:23:47 VERB PuppetWeChatBridge readyAngular()
07:23:47 VERB PuppetWeChatBridge inject()
07:23:47 VERB PuppetWeChatBridge ding(ding() OK!)
07:23:47 VERB PuppetWeChatBridge clickSwitchAccount()
07:23:48 VERB PuppetWeChatEvent onScan({code: 0, url: https://login.weixin.qq.com/qrcode/IfbDJJtaYg==})
07:23:48 VERB StateSwitch <WechatyReady> inactive(true) <- (true)

**Comment by wxchenpro** [comment]
在尝试这个框架，遇到相同的问题

```
#!/bin/bash

export WECHATY_LOG="debug"
export WECHATY_PUPPET="wechaty-puppet-wechat"
export WECHATY_PUPPET_SERVER_PORT="7700"
export WECHATY_TOKEN="xxxxxxxxxxxxxxx"

docker run -ti \
    --name wechaty_puppet_service_token_gateway \
    --rm \
    -e WECHATY_LOG \
    -e WECHATY_PUPPET \
    -e WECHATY_PUPPET_SERVER_PORT \
    -e WECHATY_TOKEN \
    -e WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER=true \
    -e WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true \
    -p "$WECHATY_PUPPET_SERVER_PORT:$WECHATY_PUPPET_SERVER_PORT" \
    wechaty/wechaty:latest

```

**Comment by isbiong100** [comment]
请问解决了吗
