### ISSUE TITLE
request has been cancelled for reason: SERVER_ERROR: 4 DEADLINE_EXCEEDED: Deadline exceeded,出一直现超时

### ISSUE THREAD

**Issue by Ceferr** [wechaty/wechaty#2499]
12:33:44 ERR [PadLocalClient] error while syncing after longlink connected: VError: [tid:c84c1cea] request has been cancelled for reason: CLIENT_ERROR: [tid:c84c1cea] Exception while handling wechat request: long link send request timeout
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at Request.error (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:347:10)
    at Request.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/wechaty/node_modules/padlocal-client-ts/dist/Request.js:6:65)

12:47:28 ERR [PadLocalClient] error while syncing onpush: VError: [tid:1638475f] request has been cancelled for reason: SERVER_ERROR: 4 DEADLINE_EXCEEDED: Deadline exceeded
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at ClientDuplexStreamImpl.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (events.js:400:28)
    at ClientDuplexStreamImpl.emit (domain.js:470:12)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:670:18)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
12:47:30 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"heartbeat@padlocal"})
12:47:36 ERR Config ###########################
12:47:36 ERR Config unhandledRejection: VError: longlink socket connect timeout
    at Timeout.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:365:25)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) [object Promise]
12:47:36 ERR Config ###########################
12:47:36 ERR Config process.on(unhandledRejection) promise.catch(longlink socket connect timeout)
Config IOError [VError]: longlink socket connect timeout
    at Timeout.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:365:25)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  jse_shortmsg: 'longlink socket connect timeout',
  jse_info: {}
}

在centos docker上部署一会就出现超时的情况，有人遇到过吗

**Comment by zhajingwen** [comment]
我也遇到类似的错误；但是不会导致进程挂掉，不是致命性的

```
01:53:41 VERB IoClient onMessage(Message#Text[🗣Contact<一招半式，走江湖>@👥Room<小林哥爬虫交流群>]	哥)
01:53:52 ERR [PadLocalClient] error while syncing onpush: VError: [tid:388f6228] request has been cancelled for reason: CLIENT_ERROR: [tid:388f6228] Exception while handling wechat request: long link send request timeout
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at Request.error (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:347:10)
    at Request.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/wechaty/node_modules/padlocal-client-ts/dist/Request.js:6:65)
(base) [root@10-30-0-153 bgspier]# docker logs -n 10 4424b9fd6a70
01:53:41 VERB Puppet messagePayload(8557978250146350996)
01:53:41 VERB Room ready()
01:53:41 VERB Puppet selfId()
01:53:41 VERB IoClient onMessage(Message#Text[🗣Contact<一招半式，走江湖>@👥Room<小林哥爬虫交流群>]	哥)
01:53:52 ERR [PadLocalClient] error while syncing onpush: VError: [tid:388f6228] request has been cancelled for reason: CLIENT_ERROR: [tid:388f6228] Exception while handling wechat request: long link send request timeout
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at Request.error (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:347:10)
    at Request.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/wechaty/node_modules/padlocal-client-ts/dist/Request.js:6:65)
```
