### ISSUE TITLE
SERVER_ERROR | wechat request io error 

### ISSUE THREAD

**Issue by Astlight** [wechaty/wechaty#2513]
用docker启的wechaty:latest,用的wechaty-puppet-padlocal,  扫码登录后一直【08:19:45 INFO [PuppetPadlocal] start login with type: AutoLogin】这个状态， 但是用python-wechaty 去连接时， 会一直报以下错误。 是docker问题还是python-wechaty问题？

2023-04-12 16:17:54 08:17:54 ERR Config process.on(unhandledRejection) promise.catch([tid:c42a016b] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:c42a016b] wechat request io error)
2023-04-12 16:17:54 Config SubRequestCancelError [VError]: [tid:c42a016b] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:c42a016b] wechat request io error
2023-04-12 16:17:54     at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
2023-04-12 16:17:54     at ClientDuplexStreamImpl.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
2023-04-12 16:17:54     at ClientDuplexStreamImpl.emit (node:events:527:28)
2023-04-12 16:17:54     at ClientDuplexStreamImpl.emit (node:domain:475:12)
2023-04-12 16:17:54     at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:689:18)
2023-04-12 16:17:54     at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
2023-04-12 16:17:54     at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
2023-04-12 16:17:54     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
2023-04-12 16:17:54   jse_shortmsg: '[tid:c42a016b] request has been cancelled for reason: SERVER_ERROR',
2023-04-12 16:17:54   jse_cause: Error: 2 UNKNOWN: [tid:c42a016b] wechat request io error
2023-04-12 16:17:54       at Object.callErrorFromStatus (/wechaty/node_modules/@grpc/grpc-js/src/call.ts:81:24)
2023-04-12 16:17:54       at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:689:32)
2023-04-12 16:17:54       at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
2023-04-12 16:17:54       at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
2023-04-12 16:17:54       at processTicksAndRejections (node:internal/process/task_queues:78:11) {
2023-04-12 16:17:54     code: 2,
2023-04-12 16:17:54     details: '[tid:c42a016b] wechat request io error',
2023-04-12 16:17:54     metadata: Metadata { internalRepr: [Map], options: {} }
2023-04-12 16:17:54   },
2023-04-12 16:17:54   jse_info: {},
2023-04-12 16:17:54   reason: 1,
2023-04-12 16:17:54   cause: [Function: ve_cause]
2023-04-12 16:17:54 }

**Comment by chenag** [comment]
你好，请问一下你这个问题解决了吗？

**Comment by Lyq0055** [comment]
请问解决了吗，我也碰到这个问题了

**Comment by chenag** [comment]
你的也是在windows下面安装的docker，然后启动报错是padlocal-client连接不上吗？

**Comment by chenag** [comment]
> 请问解决了吗，我也碰到这个问题了
你的也是在windows下面安装的docker，然后启动报错是padlocal-client连接不上吗？

**Comment by chenag** [comment]
> 请问解决了吗，我也碰到这个问题了

你的也是在windows下面安装的docker，然后启动报错是padlocal-client连接不上吗？

**Comment by hayate-hsu** [comment]
我也遇到这个问题，这段时间非常不稳定。
我用的是 wechaty：0.65，这个和是否是python-wechaty没关系的。不知道啥时候解决这类问题

**Comment by chenag** [comment]
> 我也遇到这个问题，这段时间非常不稳定。 我用的是 wechaty：0.65，这个和是否是python-wechaty没关系的。不知道啥时候解决这类问题

我感觉不是稳定的问题，可能和ip有关系，我们在尝试修改docker的网络模式启动试试

**Comment by chenag** [comment]
> 我也遇到这个问题，这段时间非常不稳定。 我用的是 wechaty：0.65，这个和是否是python-wechaty没关系的。不知道啥时候解决这类问题

我们用的也是0.65这个版本，主要是padlocal-client启动的时候连接不上。
