### ISSUE TITLE
AssertionError [ERR_ASSERTION]: 3 == 0

### ISSUE THREAD

**Issue by baobao323** [wechaty/wechaty#2589]
运行一段时间后报错然后退出
AssertionError [ERR_ASSERTION]: 3 == 0
    at Object.equal (/volume1/homes/botuser/node_modules/wechat4u/lib/util/global.js:69:24)
    at /volume1/homes/botuser/node_modules/wechat4u/lib/core.js:263:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 3 == 0\n' +
    '    at Object.equal (/volume1/homes/botuser/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /volume1/homes/botuser/node_modules/wechat4u/lib/core.js:263:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
GError: 连续3次同步失败，5s后尝试重启
    at /volume1/homes/botuser/node_modules/wechat4u/lib/wechat.js:129:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'Error: 连续3次同步失败，5s后尝试重启\n' +
    '    at /volume1/homes/botuser/node_modules/wechat4u/lib/wechat.js:129:22\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
uncaughtException Error: must logout first before login again!
    at PuppetWechat4u.login (file:///volume1/homes/botuser/node_modules/wechaty-puppet/dist/esm/src/mixins/login-mixin.js:81:23)
    at Wechat.<anonymous> (file:///volume1/homes/botuser/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:289:24)
    at Wechat.emit (node:events:513:28)
    at /volume1/homes/botuser/node_modules/wechat4u/lib/wechat.js:202:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by UI-ceiling** [comment]
![image](https://github.com/wechaty/wechaty/assets/87213312/38217393-4efb-43ac-9d17-ca68c72bb2dd)

我无法正常运行

**Comment by cn-ryan** [comment]
同样的错误

**Comment by LokerL** [comment]
同样的错误

**Comment by 532777032** [comment]
这篇https://mp.weixin.qq.com/s/vTVYk52xHvld_s3Vm72L8A
其实你看第三点`解决提示axiosError的问题（其实也是wechaty超时重连的问题  ` 这个我也顺便解决了超时的问题。
