### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by moushicheng** [wechaty/wechaty#2601]
```
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (C:\Users\Administrator\Desktop\wechat-bot\node_modules\wechat4u\lib\util\global.js:69:24)
    at C:\Users\Administrator\Desktop\wechat-bot\node_modules\wechat4u\lib\core.js:227:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (C:\\Users\\Administrator\\Desktop\\wechat-bot\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at C:\\Users\\Administrator\\Desktop\\wechat-bot\\node_modules\\wechat4u\\lib\\core.js:227:24\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}
process exits :0
```
新号无法登录，旧号就能登录，新号报错这个

**Comment by danni-cool** [comment]
新号check三部曲《实名了吗》，《绑手机号了吗》，《绑银行卡了吗》

**Comment by moushicheng** [comment]
> 新号check三部曲《实名了吗》，《绑手机号了吗》，《绑银行卡了吗》

谢谢你！我去试试

**Comment by moushicheng** [comment]
> 新号check三部曲《实名了吗》，《绑手机号了吗》，《绑银行卡了吗》

确实是的，已经解决了，感恩

**Comment by hrz191128** [comment]
遇到了相同的问题，谢谢
