### ISSUE TITLE
Exception while handling wechat request

### ISSUE THREAD

**Issue by chandling** [wechaty/wechaty#2604]
## 0. Report Issue Guide

09:26:04 ERR [Request] [tid:8440525e], padlocal grpc request failed: 3, error: IOError: [tid:8440525e] Exception while handling wechat request: long link send request timeout
09:26:04 ERR [PadLocalClient] error while syncing onpush: VError: [tid:8440525e] request has been cancelled for reason: CLIENT_ERROR: [tid:8440525e] Exception while handling wechat request: long link send request timeout
    at Request._failAllPendingRequest (/home/hxkj/wecat/node_modules/padlocal-client-ts/src/Request.ts:338:15)
    at Request.error (/home/hxkj/wecat/node_modules/padlocal-client-ts/src/Request.ts:351:10)
    at Request.<anonymous> (/home/hxkj/wecat/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/home/hxkj/wecat/node_modules/padlocal-client-ts/dist/Request.js:6:65)

**Comment by chandling** [comment]
16:23:51 ERR [Request] [tid:38948829], padlocal grpc request failed: 1, error: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded
16:23:51 ERR [PadLocalClient] error while syncing onpush: VError: [tid:38948829] request has been cancelled for reason: SERVER_ERROR: 4 DEADLINE_EXCEEDED: Deadline exceeded
    at Request._failAllPendingRequest (/home/hxkj/wecat/node_modules/padlocal-client-ts/src/Request.ts:338:15)
    at ClientDuplexStreamImpl.<anonymous> (/home/hxkj/wecat/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (node:events:513:28)
    at ClientDuplexStreamImpl.emit (node:domain:489:12)
    at Object.onReceiveStatus (/home/hxkj/wecat/node_modules/@grpc/grpc-js/src/client.ts:701:18)
    at Object.onReceiveStatus (/home/hxkj/wecat/node_modules/@grpc/grpc-js/src/client-interceptors.ts:417:48)
    at /home/hxkj/wecat/node_modules/@grpc/grpc-js/src/resolving-call.ts:111:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:538:9)

**Comment by chandling** [comment]
看出现的频率应该是读取图片的地方有问题

**Comment by chandling** [comment]
每过一段时间就会开始报Exception while handling wechat request: long link send request timeout，然后就连续报好几条，

**Comment by chandling** [comment]
Error: [tid:0fbbfc71] [468ms] download file failed:{"host":{"host":"140.249.239.154","port":80},"payload":"qwAAAyJOIPnvjfAAAAAAAAAAAAAAAAADCQAAAAN2ZXIAAAABMQAAAAl3ZWl4aW5udW0AAAAKNDAzNTgzMzg0OQAAAANzZXEAAAADMzM4AAAADWNsaWVudHZlcnNpb24AAAAJNDAyNjU0NzU0AAAADGNsaWVudG9zdHlwZQAAAAxpUGFkIGlPUzE0LjIAAAAHYXV0aGtleQAAAEAwPgIBAQQ3MDUCAQECAQECBPCN7/kCAQACAQACBDKpPzsCAy9bDQIEM2iTdwIEM34MeQIEZZe+cAIEp4qqsQQAAAAAB25ldHR5cGUAAAABMQAAAAxhY2NlcHRkdXBhY2sAAAABMQAAAAZyc2F2ZXIAAAABMQAAAAhyc2F2YWx1ZQAAAIA1pRAqSRClqFjVtqr01YdYJH5Y4mQ3jeFH/OgnFVfI5pjwtOT9kUAYGMzXQ7VrjCXWsyGInqdeNWhhHbKSuyCszmxq9ZCmX7rj8+OyshyDCrZxjrviSa3BbdzMsxR0yjVL3J7rc1X+x0pL6/oBTsrF4xXSFv45ia3aSKGRRScf4gAAAAhmaWxldHlwZQAAAAE1AAAACnd4Y2hhdHR5cGUAAAABMAAAAAZmaWxlaWQAAACoMzA1MjAyMDEwMDA0NGIzMDQ5MDIwMTAwMDIwNDBkYWZiMGFjMDIwMzJkZjZjZDAyMDQzMDFhZDgzYTAyMDQ2NTQ4YTY1MjA0MjQzNTM0NjU2MzYxMzMzOTM0MmQzNjM3MzM2NjJkMzQzNjMzMzQyZDYxMzUzNjY2MmQ2MTM3MzMzNTYxMzY2MzM1Mzk2NjMxNjIwMjA0MDUyNDAwMDcwMjAxMDAwNDAwAAAAC2xhc3RyZXRjb2RlAAAAATAAAAAFaXBzZXEAAAABMAAAAA1jbGktcXVpYy1mbGFnAAAAATAAAAAJd3htc2dmbGFnAAAAAAAAAAt3eGF1dG9zdGFydAAAAAEwAAAADWRvd25waWNmb3JtYXQAAAABMQAAAAZvZmZzZXQAAAABMAAAAAtsYXJnZXN2aWRlbwAAAAEwAAAACnNvdXJjZWZsYWcAAAABMA==","unpackaeskey":"2Xa0X7p8orQyHHhrTUDT7Q=="}, retcode: -5103017
    at Object.<anonymous> (/home/hxkj/wecat/node_modules/padlocal-client-ts/src/utils/FileUtils.ts:71:11)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hxkj/wecat/node_modules/padlocal-client-ts/dist/utils/FileUtils.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by kala888** [comment]
> 每过一段时间就会开始报Exception while handling wechat request: long link send request timeout，然后就连续报好几条，

一样情况，这时候会假死
