### ISSUE TITLE
关于exec task timeout

### ISSUE THREAD

**Issue by kuaidiniaogpt** [wechaty/wechaty#2612]
我的代码：
const msgId = message.id
const room = message.room() // 房间对象
await room.sync()   //提示此行报错
情况：
隔一段时间就
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: 13 INTERNAL: exec task timeout, uniqueQueueId: 
    at callErrorFromStatus (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\call.js:31:19)
    at Object.onReceiveStatus (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\client.js:192:76)
    at Object.onReceiveStatus (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:360:141)
    at Object.onReceiveStatus (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181)
    at G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\resolving-call.js:99:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\client.js:160:32)
    at ServiceClientImpl.roomPayload (G:\ml\workpro-getting-started-latest-features\node_modules\@grpc\grpc-js\build\src\make-client.js:105:19)
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at bound  (node:internal/util:428:12)
    at PuppetService.roomRawPayload (file:///G:/ml/workpro-getting-started-latest-features/node_modules/@juzi/wechaty-puppet-service/dist/esm/src/client/puppet-service.js:1159:44)
    at async PuppetService.roomPayload (file:///G:/ml/workpro-getting-started-latest-features/node_modules/@juzi/wechaty-puppet/dist/esm/src/mixins/room-mixin.js:146:32)
    at async WechatifiedUserClass.ready (file:///G:/ml/workpro-getting-started-latest-features/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:262:24)
    at async WechatifiedUserClass.sync (file:///G:/ml/workpro-getting-started-latest-features/node_modules/@juzi/wechaty/dist/esm/src/user-modules/room.js:247:9)
    at async WechatyImpl.<anonymous> (file:///G:/ml/workpro-getting-started-latest-features/index.js:132:3) {
  code: 13,
  details: 'exec task timeout, uniqueQueueId: ',
  metadata: Metadata {
    internalRepr: Map(3) {
      'content-type' => [ 'application/grpc+proto' ],
      'date' => [ 'Tue, 05 Dec 2023 02:08:34 GMT' ],
      'authorization' => [ 'Wechaty undefined' ]
    },
    options: {}
  }
}
node版本：20.9.0
wechaty:
"@juzi/wechaty": "^1.0.76",
"@juzi/wechaty-puppet": "^1.0.68",
"@juzi/wechaty-puppet-service": "^1.0.81",

**Comment by djfkue** [comment]
我也是遇到基本上一样的问题。
