### ISSUE TITLE
'can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server

### ISSUE THREAD

**Issue by zhang-prog** [wechaty/wechaty#2618]
## can't fetch endpoint from chatie server

已经使用一年了，突然有一天启动时报错，目前已经一周链接不上了，请问怎么解决？有没有更稳定的链接方式，例如之前有token被你们转为私有服务？

```sh
2023-12-12 12:50:02,965 - Wechaty - INFO - init_puppet_event_bridge() <<wechaty_puppet_service.puppet.PuppetService object at 0x7fd7b7dca8d0>>
2023-12-12 12:50:02,965 - Wechaty - INFO - initPuppetEventBridge() puppet.on(dong) (listenerCount:1) registering...
2023-12-12 12:50:02,965 - Wechaty - INFO - initPuppetEventBridge() puppet.on(error) (listenerCount:1) registering...
2023-12-12 12:50:02,965 - Wechaty - INFO - initPuppetEventBridge() puppet.on(heart-beat) (listenerCount:1) registering...
2023-12-12 12:50:02,965 - Wechaty - INFO - initPuppetEventBridge() puppet.on(ready) (listenerCount:1) registering...
2023-12-12 12:50:02,965 - Wechaty - INFO - receive <reset> event <%s>
2023-12-12 12:50:02,966 - Wechaty - INFO - initPuppetEventBridge() puppet.on(reset) (listenerCount:0) registering...
2023-12-12 12:50:02,966 - Wechaty - INFO - initPuppetEventBridge() puppet.on(friendship) (listenerCount:1) registering...
2023-12-12 12:50:02,966 - Wechaty - INFO - initPuppetEventBridge() puppet.on(login) (listenerCount:1) registering...
2023-12-12 12:50:02,966 - Wechaty - INFO - initPuppetEventBridge() puppet.on(logout) (listenerCount:1) registering...
2023-12-12 12:50:02,966 - Wechaty - INFO - initPuppetEventBridge() puppet.on(message) (listenerCount:1) registering...
2023-12-12 12:50:02,966 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-invite) (listenerCount:1) registering...
2023-12-12 12:50:02,966 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-join) (listenerCount:1) registering...
2023-12-12 12:50:02,966 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-leave) (listenerCount:1) registering...
2023-12-12 12:50:02,966 - Wechaty - INFO - initPuppetEventBridge() puppet.on(room-topic) (listenerCount:1) registering...
2023-12-12 12:50:02,966 - Wechaty - INFO - initPuppetEventBridge() puppet.on(scan) (listenerCount:1) registering...
2023-12-12 12:50:02,966 - Wechaty - INFO - starting puppet ...
2023-12-12 12:50:02,966 - PuppetService - INFO - init puppet ...
2023-12-12 12:50:02,966 - PuppetService - INFO - fetching endpoint from chatie-server: https://api.chatie.io/v0/hosties/puppet_paimon_xxxxx-xxxx-xxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "/home/grdata/miniconda3/envs/grdata/lib/python3.7/site-packages/wechaty/wechaty.py", line 445, in start
    await self.puppet.start()
  File "/home/grdata/miniconda3/envs/grdata/lib/python3.7/site-packages/wechaty_puppet_service/puppet.py", line 911, in start
    self._init_puppet()
  File "/home/grdata/miniconda3/envs/grdata/lib/python3.7/site-packages/wechaty_puppet_service/puppet.py", line 877, in _init_puppet
    'can"t fetch endpoint from chatie server. '
wechaty_puppet.exceptions.WechatyPuppetGrpcError: WechatyPuppetGrpcError('can"t fetch endpoint from chatie server. You can try it later, or make sure that your pc can connect to heroku server ', None, None)
```

**Comment by zhang-prog** [comment]
使用 wechaty-puppet-service 替代已经被弃用的 wechaty-puppet-hostie，怎么去替代，有详细步骤吗

**Comment by zhang-prog** [comment]
这些解决方案对我不起作用

**Comment by huan** [comment]
@dosubot Thanks for pinging me.

@zhang-prog Please provide all the information required from the Issue Template because without those information, nobody knows nothing.

**Comment by kasuo6933** [comment]
@zhang-prog 我跟你遇到了同样的问题，请你的问题解决了吗？

**Comment by kasuo6933** [comment]
@dosu-bot  
我也是python版本的，在环境变量除了指定了token之外，还添加了
os.environ['WECHATY_PUPPET_SERVICE_AUTHORITY'] = 'token-service-discovery-test.juzibot.com'

我遇到了和他一样的问题，我按照你的建议设置了WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_CLIENT=true之后程序可以运行起来，然后出现扫面二维码和如下信息：
2024-08-06 00:57:19,278 - Wechaty - INFO - or you can scan qrcode from: https://wechaty.js.org/qrcode/https://wx.work.weixin.qq.com/cgi-bin/crtx_auth?key=37E6B02C2F01CFC06EA989D66686120D&wx=1
2024-08-06 00:57:19,278 - Wechaty - ERROR - internal error <>
我扫码之后就出现错误退出。
'status'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001EC6C5C3550>
Traceback (most recent call last):
  File "C:\Users\Ricky\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Ricky\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Ricky\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\Ricky\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

进程已结束，退出代码为 0

请问改如何解决。
