### ISSUE TITLE
调用room.say()时，何如进行异常捕获，掉线时有打印异常信息，但无法捕获

### ISSUE THREAD

**Issue by 269000710** [wechaty/wechaty#2629]
uncaughtException AssertionError [ERR_ASSERTION]: 1101 == 0
    at Object.equal (D:\Code\yizun-2023\nodeJs\hubeiCtRobot\node_modules\wechat4u\lib\util\global.js:69:24)
    at D:\Code\yizun-2023\nodeJs\hubeiCtRobot\node_modules\wechat4u\lib\core.js:537:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageSendText (file:///D:/Code/yizun-2023/nodeJs/hubeiCtRobot/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:612:9)
    at async WechatifiedUserClass.say (file:///D:/Code/yizun-2023/nodeJs/hubeiCtRobot/node_modules/wechaty/dist/esm/src/user-modules/room.js:368:21) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1101,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '发送文本信息失败'
}
![image](https://github.com/wechaty/wechaty/assets/33623806/1bddfc46-cc72-4cc4-be3d-4264399bf370)

**Comment by 269000710** [comment]
已经退出登录了，这里打印了异常信息，但是无法捕获，没有走进catch里边
