### ISSUE TITLE
是否可以在回复的消息中@某个人

### ISSUE THREAD

**Issue by sgshy1995** [wechaty/wechaty#2646]
是否可以在回复的消息中@某个人

**Comment by sgshy1995** [comment]
@dosu-bot 我按照你的代码`await m.say('Hello!', members[0])`，或者`await m.say('Hello!', m.talker())`，都没有效果，并不能@到指定的人。

**Comment by sgshy1995** [comment]
@dosu-bot 按照你的代码，可以@到他，但貌似只是写了一段文字而已，微信本身并没有识别到@他。是否你的@方法实现有问题？

**Comment by MarkShawn2020** [comment]
> @dosu-bot 按照你的代码，可以@到他，但貌似只是写了一段文字而已，微信本身并没有识别到@他。是否你的@方法实现有问题？

- 用 room.say 它可以支持第2...n个参数（对象）
- 用message.say则不可以
- 用 conversation.say 可以兼容以上二者

**Comment by aqpmzngldh** [comment]
> > @dosu-bot 按照你的代码，可以@到他，但貌似只是写了一段文字而已，微信本身并没有识别到@他。是否你的@方法实现有问题？
> 
> * 用 room.say 它可以支持第2...n个参数（对象）
> * 用message.say则不可以
> * 用 conversation.say 可以兼容以上二者

Caught exception: Error: query must provide at least one key. current query is empty.
uncaughtException GError: query must provide at least one key. current query is empty.
at PuppetWechat4u.contactQueryFilterFactory (file:///www/wwwroot/wxq/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:117:23)
at PuppetWechat4u.contactSearch (file:///www/wwwroot/wxq/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:64:41)
at async Function.findAll (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/user-modules/contact.js:129:35)
at async Function.find (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/user-modules/contact.js:84:29)
at async Promise.all (index 0)
at async PuppetWechat4u. (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:273:56) {
code: 2,
details: 'Error: query must provide at least one key. current query is empty.\n' +
' at PuppetWechat4u.contactQueryFilterFactory (file:///www/wwwroot/wxq/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:117:23)\n' +
' at PuppetWechat4u.contactSearch (file:///www/wwwroot/wxq/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:64:41)\n' +
' at async Function.findAll (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/user-modules/contact.js:129:35)\n' +
' at async Function.find (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/user-modules/contact.js:84:29)\n' +
' at async Promise.all (index 0)\n' +
' at async PuppetWechat4u. (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:273:56)'
}
