### ISSUE TITLE
这两天机器人一直登录几分钟，下马掉线，这是什么问题

### ISSUE THREAD

**Issue by lovecodeyou** [wechaty/wechaty#2653]
uncaughtException GError: 状态同步超过286.082s未响应，5s后尝试重启
    at Wechat.checkPolling (/www/project/chatgpt-wechaty/node_modules/wechat4u/lib/wechat.js:298:19)
    at Timeout._onTimeout (/www/project/chatgpt-wechaty/node_modules/wechat4u/lib/wechat.js:319:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: 'Error: 状态同步超过286.082s未响应，5s后尝试重启\n' +
    '    at Wechat.checkPolling (/www/project/chatgpt-wechaty/node_modules/wechat4u/lib/wechat.js:298:19)\n' +
    '    at Timeout._onTimeout (/www/project/chatgpt-wechaty/node_modules/wechat4u/lib/wechat.js:319:25)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'

**Comment by imyuanli** [comment]
我也遇见这个问题了，机器人如果一直没人艾特的话，过一会就会自动断联

**Comment by sisuad** [comment]
+1

**Comment by byteHulk** [comment]
+1

**Comment by ameyokomori** [comment]
今天重新装了下package，也变成这样了

**Comment by jinzhaochaliang** [comment]
Has it been solved?
