### ISSUE TITLE
有时候在某些情况下，比如场景一：用户进群提醒这块会报错，等一些其他情况下也会报这个错

### ISSUE THREAD

**Issue by aqpmzngldh** [wechaty/wechaty#2679]
Caught exception: Error: query must provide at least one key. current query is empty.
uncaughtException GError: query must provide at least one key. current query is empty.
    at PuppetWechat4u.contactQueryFilterFactory (file:///www/wwwroot/wxq/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:117:23)
    at PuppetWechat4u.contactSearch (file:///www/wwwroot/wxq/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:64:41)
    at async Function.findAll (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/user-modules/contact.js:129:35)
    at async Function.find (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/user-modules/contact.js:84:29)
    at async Promise.all (index 0)
    at async PuppetWechat4u.<anonymous> (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:273:56) {
  code: 2,
  details: 'Error: query must provide at least one key. current query is empty.\n' +
    '    at PuppetWechat4u.contactQueryFilterFactory (file:///www/wwwroot/wxq/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:117:23)\n' +
    '    at PuppetWechat4u.contactSearch (file:///www/wwwroot/wxq/node_modules/wechaty-puppet/dist/esm/src/mixins/contact-mixin.js:64:41)\n' +
    '    at async Function.findAll (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/user-modules/contact.js:129:35)\n' +
    '    at async Function.find (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/user-modules/contact.js:84:29)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async PuppetWechat4u.<anonymous> (file:///www/wwwroot/wxq/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:273:56)'
}

**Comment by yuji8023** [comment]
👀

**Comment by zhanghehe** [comment]
this issue is not solved
