### ISSUE TITLE
reset heartbeat  error

### ISSUE THREAD

**Issue by DW1992** [wechaty/wechaty#2685]
14:51:36 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
node:events:491
      throw er; // Unhandled 'error' event
      ^

/home/myshare/shilim/shilim-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65
      this.puppet.emit('error', new Error(
                                ^

Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
    at Watchdog.reset (/home/myshare/shilim/shilim-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:513:28)
    at Watchdog.emit (node:domain:489:12)
    at Timeout._onTimeout (/home/myshare/shilim/shilim-bot/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Emitted 'error' event on WechatyImpl instance at:
      return super.emit('error', gerror)
                   ^

Error
    at WechatyImpl.emit (/home/myshare/shilim/shilim-bot/node_modules/wechaty/src/wechaty-mixins/gerror-mixin.ts:60:20)
    at PuppetWeChat.<anonymous> (/home/myshare/shilim/shilim-bot/node_modules/wechaty/src/wechaty-mixins/puppet-mixin.ts:212:20)
    at PuppetWeChat.emit (node:events:513:28)
    at PuppetWeChat.emit (node:domain:489:12)
    at PuppetWeChat.emit (/home/myshare/shilim/shilim-bot/node_modules/wechaty-puppet/src/puppet/puppet-skeleton.ts:142:18)
    at Watchdog.reset (/home/myshare/shilim/shilim-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:19)
    at Watchdog.emit (node:events:513:28)
    [... lines matching original stack trace ...]
    at processTimers (node:internal/timers:502:7) {
  code: 2,
  details: '/home/myshare/shilim/shilim-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65\n' +
    "      this.puppet.emit('error', new Error(\n" +
    '                                ^\n' +
    '\n' +
    'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (/home/myshare/shilim/shilim-bot/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:513:28)\n' +
    '    at Watchdog.emit (node:domain:489:12)\n' +
    '    at Timeout._onTimeout (/home/myshare/shilim/shilim-bot/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:559:17)\n' +
    '    at processTimers (node:internal/timers:502:7)'
}

**Comment by liangzhicheng0423** [comment]
请问这个问题解决了吗？我也遇到了相同的问题
