### ISSUE TITLE
Accept friendrequest catch `o.isBrandContact` error

### ISSUE THREAD

**Issue by lijiarui** [wechaty/wechaty#272]
When the bot accept a friendrequest, it can catch the following error sometimes, but I cannot find the reason.
### log

```
WARN PuppetWebBrowser execute() exception: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver i, WebDriverError: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64)
    at Object.checkLegacyResponse (/bot/node_modules/selenium-webdriver/lib/error.js:517:15)
    at parseHttpResponse (/bot/node_modules/selenium-webdriver/lib/http.js:516:11)
    at doSend.then.response (/bot/node_modules/selenium-webdriver/lib/http.js:432:13)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
WARN PuppetWebBridge execute() exception: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64)
WARN PuppetWebBridge proxyWechaty() exception: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64)
ERR PuppetWebBridge send() exception: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64)
ERR PuppetWeb send() exception: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64)
ERR Wechaty send() exception: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64)
ERR Config ###########################
ERR Config unhandledRejection: WebDriverError: unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64) [object Promise]
ERR Config ###########################
ERR Config unhandledRejection::catch(unknown error: o.isBrandContact is not a function
  (Session info: chrome=56.0.2924.76)
  (Driver info: chromedriver=2.25 (5a911c1ac99b36efadff2041357740080cc27220),platform=Linux 3.10.0-514.2.2.el7.x86_64 x86_64))
(node:21) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

**Comment by zixia** [comment]
Duplicated with #81 

Provide a reproducible code snip is needed.
