### ISSUE TITLE
 经常中断 uncaughtException GError [AxiosError]: timeout of 60000ms exceeded

### ISSUE THREAD

**Issue by allforone** [wechaty/wechaty#2720]
"wechaty-plugin-contrib": "^1.11.1",
    "wechaty-puppet-oicq": "^1.10.2",
    "wechaty-puppet-walnut": "^1.11.6",
    "wechaty-puppet-wechat": "^1.18.4",
    "wechaty-puppet-wechat4u": "~1.14.14",
    "wechaty-puppet-whatsapp": "^1.19.16"
    
    版本如上，有人遇到过么

uncaughtException GError [AxiosError]: timeout of 60000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/home/all/wexin_node/node_modules/axios/dist/node/axios.cjs:3143:16)
    at RedirectableRequest.emit (node:events:518:28)
    at Timeout.<anonymous> (/home/all/wexin_node/node_modules/follow-redirects/index.js:210:12)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
    at Axios.request (/home/all/wexin_node/node_modules/axios/dist/node/axios.cjs:4224:41) {
  code: 2,
  details: 'AxiosError: timeout of 60000ms exceeded\n' +
    '    at RedirectableRequest.handleRequestTimeout (/home/all/wexin_node/node_modules/axios/dist/node/axios.cjs:3143:16)\n' +
    '    at RedirectableRequest.emit (node:events:518:28)\n' +
    '    at Timeout.<anonymous> (/home/all/wexin_node/node_modules/follow-redirects/index.js:210:12)\n' +
    '    at listOnTimeout (node:internal/timers:573:17)\n' +
    '    at process.processTimers (node:internal/timers:514:7)\n' +
    '    at Axios.request (/home/all/wexin_node/node_modules/axios/dist/node/axios.cjs:4224:41)'

**Comment by qiyaozu** [comment]
我也遇到了

**Comment by 233312-ship-it** [comment]
请问解决了吗

**Comment by waynezhao12** [comment]
我回滚旧版解决了，wechaty相关的包就别升级了

**Comment by qiyaozu** [comment]
> 我回滚旧版解决了，wechaty相关的包就别升级了

兄弟回滚到哪个版本了？

**Comment by waynezhao12** [comment]
> > 我回滚旧版解决了，wechaty相关的包就别升级了
> 
> 兄弟回滚到哪个版本了？

哦我想起来了，我是把openai回滚到了3.2.1，之前升到4.42就会报错

**Comment by cjhgit** [comment]
> > > 我回滚旧版解决了，wechaty相关的包就别升级了
> > 
> > 
> > 兄弟回滚到哪个版本了？
> 
> 哦我想起来了，我是把openai回滚到了3.2.1，之前升到4.42就会报错

wechaty 1.20.2 经常报这个错误，请问你的 wechaty 是什么版本的？

**Comment by a614349007** [comment]
同问，我现在用wechaty 1.20.2也是经常报错这个错误，请问下您那边是回滚到什么版本的？
