### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by Whuhxh** [wechaty/wechaty#273]
1.Run npm run doctor or wechaty run doctor(for docker user), paste output here

node -v: 6.9.1
npm -v: 3.10.8

  #### Wechaty Doctor

  1. Wechaty version: #git[7faecd6 0.7.32]
  2. uname -r: 3.10.0-327.10.1.el7.x86_64
  3. Docker: false
  4. Node version: v6.9.1

2.Expected behavior

When start bot with calling Contact.load(id) to load a contact, but the contact id is some "undefined" value, the bot should deal with id of "undefined" situation.

3.Actual behavior

ERR Room contactGetter(@@c4f424080c5f480442dfb0dd5af062b70443edf95c9d1b87c1e15ab1b212fe24) exception: Cannot read property 'Symbol(Symbol.iterator)' of undefined
ERR Message ready() exception: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
at Room. (/bot/node_modules/wechaty/dist/src/room.js:52:32)
at Generator.next ()
at /bot/node_modules/wechaty/dist/src/room.js:7:71
at __awaiter (/bot/node_modules/wechaty/dist/src/room.js:3:12)
at Room.readyAllMembers (/bot/node_modules/wechaty/dist/src/room.js:51:16)
at Room. (/bot/node_modules/wechaty/dist/src/room.js:88:28)
at Generator.next ()
at fulfilled (/bot/node_modules/wechaty/dist/src/room.js:4:58)
at process._tickDomainCallback (internal/process/next_tick.js:129:7)
ERR PuppetWebEvent onServerMessage() exception: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
at Room. (/bot/node_modules/wechaty/dist/src/room.js:52:32)
at Generator.next ()
at /bot/node_modules/wechaty/dist/src/room.js:7:71
at __awaiter (/bot/node_modules/wechaty/dist/src/room.js:3:12)
at Room.readyAllMembers (/bot/node_modules/wechaty/dist/src/room.js:51:16)
at Room. (/bot/node_modules/wechaty/dist/src/room.js:88:28)
at Generator.next ()
at fulfilled (/bot/node_modules/wechaty/dist/src/room.js:4:58)
at process._tickDomainCallback (internal/process/next_tick.js:129:7)
ERR Config ###########################
ERR Config unhandledRejection: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined [object Promise]
ERR Config ###########################
ERR Config unhandledRejection::catch(Cannot read property 'Symbol(Symbol.iterator)' of undefined)
(node:27) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
ERR Room contactGetter(@@c4f424080c5f480442dfb0dd5af062b70443edf95c9d1b87c1e15ab1b212fe24) exception: Cannot read property 'Symbol(Symbol.iterator)' of undefined
ERR Message ready() exception: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
at Room. (/bot/node_modules/wechaty/dist/src/room.js:52:32)
at Generator.next ()
at /bot/node_modules/wechaty/dist/src/room.js:7:71
at __awaiter (/bot/node_modules/wechaty/dist/src/room.js:3:12)
at Room.readyAllMembers (/bot/node_modules/wechaty/dist/src/room.js:51:16)
at Room. (/bot/node_modules/wechaty/dist/src/room.js:88:28)
at Generator.next ()
at fulfilled (/bot/node_modules/wechaty/dist/src/room.js:4:58)
at process._tickDomainCallback (internal/process/next_tick.js:129:7)
ERR PuppetWebEvent onServerMessage() exception: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
at Room. (/bot/node_modules/wechaty/dist/src/room.js:52:32)
at Generator.next ()
at /bot/node_modules/wechaty/dist/src/room.js:7:71
at __awaiter (/bot/node_modules/wechaty/dist/src/room.js:3:12)
at Room.readyAllMembers (/bot/node_modules/wechaty/dist/src/room.js:51:16)
at Room. (/bot/node_modules/wechaty/dist/src/room.js:88:28)
at Generator.next ()
at fulfilled (/bot/node_modules/wechaty/dist/src/room.js:4:58)
at process._tickDomainCallback (internal/process/next_tick.js:129:7)
ERR Config ###########################
ERR Config unhandledRejection: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined [object Promise]
ERR Config ###########################
ERR Config unhandledRejection::catch(Cannot read property 'Symbol(Symbol.iterator)' of undefined)
(node:27) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 6)

@zixia, I think this is a bug when I first start the bot, you may need consider the "undefined" situation of load of a contact by the contact id.

Is that mean I need to check the id the contact pass to me is illegal？

**Comment by zixia** [comment]
### Need More Information

Sorry, you did not follow the **ISSUE Template**, and there's not enough information about your problem.

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you are following the ISSUE Template, answer all the question, and the more important: **provide the steps to reproduce the problem**.

**Comment by zixia** [comment]
Thanks for providing the detail information, that let me identified the reason of your issue.

This exception is not related to the `Contact.load(id)`. It is besides in the `Room. readyAllMembers(memberList: RoomRawMember[])`, which is introduced by @lijiarui at here:
https://github.com/wechaty/wechaty/commit/87f94d3ec441d15b138bc51df5c8f20b5f788802#diff-a260093009080ad4951308e3d5ea54fdR99

The reason lead to this bug is wechat needs some time to load all the member list of a room, before that, the `memberList` is `undefined`.

The easiest solution is to add checking to the paramter instead of use it directly.

**Comment by zixia** [comment]
This issue should not raise exception anymore with the latest code.

However, the real reason which caused this problem is still not resolved: when we get a room, it may take some time to full load memberList. Should deal with this situation either in the Wechaty Framework or by the developer themselves.
