### ISSUE TITLE
你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面

### ISSUE THREAD

**Issue by A-Kuan** [wechaty/wechaty#2730]
padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:e1a993f3] wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面。
23:23:08 ERR start client failed: VError: [tid:e1a993f3] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:e1a993f3] wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面。
    at Request._failAllPendingRequest (/Users/wenshihuang/WeChatProjects/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:338:15)
    at ClientDuplexStreamImpl.<anonymous> (/Users/wenshihuang/WeChatProjects/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (node:events:519:28)
    at ClientDuplexStreamImpl.emit (node:domain:488:12)
    at Object.onReceiveStatus (/Users/wenshihuang/WeChatProjects/wechaty-puppet-padlocal-demo/node_modules/@grpc/grpc-js/src/client.ts:706:18)
    at Object.onReceiveStatus (/Users/wenshihuang/WeChatProjects/wechaty-puppet-padlocal-demo/node_modules/@grpc/grpc-js/src/client-interceptors.ts:419:48)
    at /Users/wenshihuang/WeChatProjects/wechaty-puppet-padlocal-demo/node_modules/@grpc/grpc-js/src/resolving-call.ts:163:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11) 
23:23:09 INFO [PuppetPadlocal] start login with type: QrLogin
23:23:10 INFO [PadLocalDemo] onScan: Waiting(2)

什么时候可以修复啊,还修吗?

**Comment by Devo919** [comment]
可以用下这个免费的框架  
https://github.com/Devo919/Gewechat
