### ISSUE TITLE
自动同意入群报错，提示不支持

### ISSUE THREAD

**Issue by 18075717849** [wechaty/wechaty#2737]
Error handling room invitation: GError: Wechaty Puppet Unsupported API Error. Learn More At https://github.com/wechaty/wechaty-puppet/wiki/Compatibility
    at WechatyImpl.<anonymous> (file:///D:/java/getting-started/server.js:247:26)
    at WechatyImpl.emit (node:events:517:28)
    at WechatyImpl.emit (file:///D:/java/getting-started/node_modules/wechaty/dist/esm/src/wechaty-mixins/gerror-mixin.js:31:30)
    at PuppetWechat4u.<anonymous> (file:///D:/java/getting-started/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:262:34)
    at PuppetWechat4u.emit (node:events:517:28)
    at PuppetWechat4u.emit (file:///D:/java/getting-started/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:84:26)
    at Wechat.<anonymous> (file:///D:/java/getting-started/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:365:26) {
  code: 2,
  details: 'Error: Wechaty Puppet Unsupported API Error. Learn More At https://github.com/wechaty/wechaty-puppet/wiki/Compatibility\n' +
    '    at Module.throwUnsupportedError (file:///D:/java/getting-started/node_modules/wechaty-puppet/dist/esm/src/throw-unsupported-error.js:3:11)\n' +
    '    at PuppetWechat4u.roomInvitationAccept (file:///D:/java/getting-started/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:673:23)\n' +
    '    at WechatifiedUserClass.accept (file:///D:/java/getting-started/node_modules/wechaty/dist/esm/src/user-modules/room-invitation.js:66:39)\n' +
    '    at WechatyImpl.<anonymous> (file:///D:/java/getting-started/server.js:247:26)\n' +
    '    at WechatyImpl.emit (node:events:517:28)\n' +
    '    at WechatyImpl.emit (file:///D:/java/getting-started/node_modules/wechaty/dist/esm/src/wechaty-mixins/gerror-mixin.js:31:30)\n' +
    '    at PuppetWechat4u.<anonymous> (file:///D:/java/getting-started/node_modules/wechaty/dist/esm/src/wechaty-mixins/puppet-mixin.js:262:34)\n' +
    '    at PuppetWechat4u.emit (node:events:517:28)\n' +
    '    at PuppetWechat4u.emit (file:///D:/java/getting-started/node_modules/wechaty-puppet/dist/esm/src/puppet/puppet-skeleton.js:84:26)\n' +
    '    at Wechat.<anonymous> (file:///D:/java/getting-started/node_modules/wechaty-puppet-wechat4u/dist/esm/src/puppet-wechat4u.js:365:26)'
}

**Comment by 18075717849** [comment]
8月来发现不支持了

**Comment by 18075717849** [comment]
bot.on('room-invite', async roomInvitation => {
  try {
    console.log("roomInvitation",roomInvitation)
    await roomInvitation.accept()
    console.log("同意")
  } catch (error) {
    console.error('Error handling room invitation:', error);
  }
});
