### ISSUE TITLE
[ci] there is no WechatyBro in browser(yet), Error: there is no WechatyBro in browser(yet)

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#333]
https://travis-ci.org/Chatie/wechaty/jobs/212333835#L1962

```shell
00:55:41 ERR TestPuppetWeb retryPromise() waitDing() finally FAIL: there is no WechatyBro in browser(yet)
  ✖ test › puppet-web › watchdog › timer exception: there is no WechatyBro in browser(yet), Error: there is no WechatyBro in browser(yet)
    at Bridge.<anonymous> (/home/travis/build/Chatie/wechaty/src/puppet-web/bridge.ts:391:19)
    at next (native)
    at fulfilled (/home/travis/build/Chatie/wechaty/dist/src/puppet-web/bridge.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)

  test › puppet-web › watchdog › timer
  /home/travis/build/Chatie/wechaty/src/puppet-web/bridge.ts:391
   390:       if (noWechaty) {                                               
   391:         const e = new Error('there is no WechatyBro in browser(yet)')
   392:         // this.puppet.browser.dead(e)                               
  exception: there is no WechatyBro in browser(yet), Error: there is no WechatyBro in browser(yet)
      at Bridge.<anonymous> (/home/travis/build/Chatie/wechaty/src/puppet-web/bridge.ts:391:19)
      at next (native)
      at fulfilled (/home/travis/build/Chatie/wechaty/dist/src/puppet-web/bridge.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:103:7)
  Bridge.<anonymous> (src/puppet-web/bridge.ts:391:19)
  fulfilled (dist/src/puppet-web/bridge.js:4:58)
  rejected (dist/test/puppet-web/watchdog.spec.js:17:40)
```

**Comment by zixia** [comment]
Long time no see...

**Comment by UnsignedInt8** [comment]
I have the same problem. To reproduce it, you just need to deploy a bot on an overseas VPS, and wait two days.

**Comment by huan** [comment]
Glad to hear from you after two years after this issue first filed!

**Comment by timqian** [comment]
Confirmed @UnsignedInt8 's description. Maybe this is a restriction of web wechat?

**Comment by UnsignedInt8** [comment]
> Confirmed @UnsignedInt8 's description. Maybe this is a restriction of web wechat?

I think so.

**Comment by helloint** [comment]
looks like I got the same issue and I can always reproduce.
```
01:54:27 WARN PuppetWeChatBridge proxyWechaty() noWechaty exception: Error: there is no WechatyBro in browser(yet)
01:54:27 ERR PuppetWeChatBridge roomList() exception: there is no WechatyBro in browser(yet)
file:///Users/helloint/workspace/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:773
        const e = new Error('there is no WechatyBro in browser(yet)')
                  ^
GError: there is no WechatyBro in browser(yet)
    at Bridge.proxyWechaty (file:///Users/helloint/workspace/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:773:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bridge.roomList (file:///Users/helloint/workspace/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:448:14)
    at async PuppetWeChat.roomList (file:///Users/helloint/workspace/getting-started/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:793:20)
    at async PuppetWeChat.roomSearch (file:///Users/helloint/workspace/getting-started/node_modules/wechaty-puppet/src/mixins/room-mixin.ts:88:39)
    at async Function.findAll (file:///Users/helloint/workspace/getting-started/node_modules/wechaty/src/user-modules/room.ts:149:26)
    at async Function.find (file:///Users/helloint/workspace/getting-started/node_modules/wechaty/src/user-modules/room.ts:217:22)
    at async file:///Users/helloint/workspace/getting-started/index.ts:185:27 {
  code: 2,
  details: 'Error: there is no WechatyBro in browser(yet)\n' +
    '    at Bridge.proxyWechaty (file:///Users/helloint/workspace/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:773:19)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async Bridge.roomList (file:///Users/helloint/workspace/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:448:14)\n' +
    '    at async PuppetWeChat.roomList (file:///Users/helloint/workspace/getting-started/node_modules/wechaty-puppet-wechat/src/puppet-wechat.ts:793:20)\n' +
    '    at async PuppetWeChat.roomSearch (file:///Users/helloint/workspace/getting-started/node_modules/wechaty-puppet/src/mixins/room-mixin.ts:88:39)\n' +
    '    at async Function.findAll (file:///Users/helloint/workspace/getting-started/node_modules/wechaty/src/user-modules/room.ts:149:26)\n' +
    '    at async Function.find (file:///Users/helloint/workspace/getting-started/node_modules/wechaty/src/user-modules/room.ts:217:22)\n' +
    '    at async file:///Users/helloint/workspace/getting-started/index.ts:185:27'
}

```
