### ISSUE TITLE
Wechaty account logout unexpectedly

### ISSUE THREAD

**Issue by Samurais** [wechaty/wechaty#37]
# Description

Since account login successfully, wechaty run in Ubuntu Server, but after several hours, the account logout unexpectedly.

## Trace

```

^[[31m[2016-10-06 22:19:26.753] [ERROR] console - ^[[39mERR PuppetWebServer initEventsFromClient() client on error: TypeError: Cannot read property 'bridge' of undefined
    at new MediaMessage (/root/git/chatbot-mvp/philly-wechat/node_modules/wechaty/src/message-media.js:18:33)
    at PuppetWeb.onServerMessage (/root/git/chatbot-mvp/philly-wechat/node_modules/wechaty/src/puppet-web/event.js:365:11)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Socket.client.on.data (/root/git/chatbot-mvp/philly-wechat/node_modules/wechaty/src/puppet-web/server.js:149:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Socket.onevent (/root/git/chatbot-mvp/philly-wechat/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/root/git/chatbot-mvp/philly-wechat/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/root/git/chatbot-mvp/philly-wechat/node_modules/socket.io/lib/client.js:193:14)
^[[32m[2016-10-06 22:19:26.755] [INFO] console - ^[[39mINFO Bot 小白 logouted
^[[32m[2016-10-06 22:20:12.745] [INFO] console - ^[[39mINFO Bot error: [object Object]
^[[33m[2016-10-06 22:20:12.893] [WARN] console - ^[[39mWARN PuppetWebEvent onBrowserDead() will not init browser because browser.targetState(close) !== open
```

![image](https://cloud.githubusercontent.com/assets/3538629/19175318/2a9328f6-8c68-11e6-99bb-b8ebe99b4408.png)

Is it a bug? Or what is the solution to keep it steady? 
One solution is auto restart when getting crash.

**Comment by zixia** [comment]
this problem is fixed yesterday. 

u can pull the latest code to hav a try.

and please be careful because master branch is in heavy developing this week.

I will tag  a stable version later.

**Comment by zixia** [comment]
fixed by this commit:
https://github.com/wechaty/wechaty/commit/c589150e4bf42e66cb1f1690fffb89652ec9977c

**Comment by Samurais** [comment]
verified. problem is fixed.
