### ISSUE TITLE
demo 无法运行

### ISSUE THREAD

**Issue by Maopy** [wechaty/wechaty#49]
按照文档进行了如下操作：
git clone https://github.com/wechaty/wechaty.git
cd wechaty
npm install
npm run demo

报了如下错误

```
INFO Wechaty v#git[5cb8afd bug fix] initializing...
ERR PuppetWebBrowser open() exception: unknown error: Chrome version must be >= 52.0.2743.0
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
WARN PuppetWebBrowser dead() because unknown error: Chrome version must be >= 52.0.2743.0
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
ERR PuppetWebBrowser init() exception: unknown error: Chrome version must be >= 52.0.2743.0
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
ERR PuppetWeb initBrowser() exception: unknown error: Chrome version must be >= 52.0.2743.0
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
ERR PuppetWeb init() exception: WebDriverError: unknown error: Chrome version must be >= 52.0.2743.0
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
    at WebDriverError (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/lib/http.js:398:13)
    at doSend.then.response (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/lib/http.js:330:11)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:366:24)
    at Driver (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/chrome.js:716:38)
    at Builder.build (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/index.js:554:16)
    at Browser.getChromeDriver (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:197:18)
    at Browser.initDriver (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:151:28)
    at Browser.<anonymous> (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:77:18)
    at next (native)
    at /Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:7:65
    at __awaiter (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:3:12)
    at Browser.init (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:53:16)
From: Task: WebDriver.navigate().to(https://wx.qq.com/zh_CN/htmledition/v2/images/webwxgeticon.jpg)
    at Driver.schedule (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at Navigation.to (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:1042:25)
    at Driver.get (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:832:28)
    at Promise (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:121:19)
    at Browser.open (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:118:12)
    at Browser.<anonymous> (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:80:18)
    at next (native)
    at fulfilled (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
    at Function.Module.runMain (module.js:606:11)
From: Task: WebDriver.manage().timeouts().setScriptTimeout(10000)
    at Driver.schedule (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:414:17)
    at Timeouts._scheduleCommand (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:1402:25)
    at Timeouts.setScriptTimeout (/Users/Maopy/www/repo/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:1385:17)
    at Browser.initDriver (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:160:12)
    at Browser.<anonymous> (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:77:18)
    at next (native)
    at /Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:7:65
    at __awaiter (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:3:12)
    at Browser.init (/Users/Maopy/www/repo/wechaty/src/puppet-web/browser.ts:53:16)
    at PuppetWeb.<anonymous> (/Users/Maopy/www/repo/wechaty/src/puppet-web/puppet-web.ts:197:21)
WARN PuppetWeb quit() without a bridge
WARN PuppetWebBrowser quit() exception: There was an uncaught error in the control flow: WebDriverError: unknown error: Chrome version must be >= 52.0.2743.0
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
WARN PuppetWebBrowser driver.quit() exception: There was an uncaught error in the control flow: WebDriverError: unknown error: Chrome version must be >= 52.0.2743.0
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
WARN PuppetWebBrowser quit() exception: unknown error: Chrome version must be >= 52.0.2743.0
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
WARN PuppetWebBrowser driver.quit() exception: unknown error: Chrome version must be >= 52.0.2743.0
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
ERR Wechaty init() exception: unknown error: Chrome version must be >= 52.0.2743.0
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
ERR Bot init() fail: WebDriverError: unknown error: Chrome version must be >= 52.0.2743.0
  (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.12.0 x86_64)
WARN PuppetWeb quit() without a bridge
WARN PuppetWeb quit() without a browser
```

而我的chrome 版本是 53.0.2785.116 (64-bit) Mac版本

**Comment by zixia** [comment]
hi @Maopy , 

u had resolve this issue, could u tell me why this error occoured, in order to help others in the furture?
