### ISSUE TITLE
基础运行报错.....我都有点不好意思问了.....汗....

### ISSUE THREAD

**Issue by issmile** [wechaty/wechaty#82]
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
npm run dev

### Expected behavior
运行起例子,Chrome启动了3次就停在那里了,什么情况

### Actual behavior
E:\weixin\wechaty>npm run dev

> weixinbot@1.0.0 dev E:\weixin\wechaty
> babel-node ./src/mybot.js

INFO Wechaty v0.5.9 initializing...
[4544:11064:1108/213200:ERROR:mf_helpers.cc(12)] Error in dxva_video_decode_acce
lerator_win.cc on line 345
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() drive
r.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver getChromeDriver() with retry: 1
[5708:16264:1108/213209:ERROR:mf_helpers.cc(12)] Error in dxva_video_decode_acce
lerator_win.cc on line 345
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() drive
r.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver getChromeDriver() with retry: 2
[5000:17748:1108/213219:ERROR:mf_helpers.cc(12)] Error in dxva_video_decode_acce
lerator_win.cc on line 345
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() drive
r.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver
WARN PuppetWebBrowserDriver getChromeDriver() with retry: 3
[22076:7492:1108/213229:ERROR:mf_helpers.cc(12)] Error in dxva_video_decode_acce
lerator_win.cc on line 345
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver valid() driver.getSession() exception: valid() drive
r.getSession() timeout(halt?)
WARN PuppetWebBrowserDriver getChromeDriver() got invalid driver
ERR PuppetWebBrowserDriver getChromeDriver() exception: Error: getChromeDriver()
 got invalid driver
    at BrowserDriver.<anonymous> (E:\weixin\wechaty\node_modules\.0.5.9@wechaty\
src\puppet-web\browser-driver.ts:145:17)
    at next (native)
    at fulfilled (E:\weixin\wechaty\node_modules\.0.5.9@wechaty\dist\src\puppet-
web\browser-driver.js:4:58)
    at run (E:\weixin\wechaty\node_modules\.2.4.1@core-js\modules\es6.promise.js
:87:22)
    at E:\weixin\wechaty\node_modules\.2.4.1@core-js\modules\es6.promise.js:100:
28
    at flush (E:\weixin\wechaty\node_modules\.2.4.1@core-js\modules\_microtask.j
s:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9), retry:
 4
ERR PuppetWebBrowser init() exception: getChromeDriver() got invalid driver
WARN PuppetWebBrowser quit() exception: Cannot read property 'close' of undefine
d
WARN PuppetWebBrowser driver.quit() exception: Cannot read property 'close' of u
ndefined
ERR PuppetWeb initBrowser() exception: getChromeDriver() got invalid driver
ERR PuppetWeb init() exception: Error: getChromeDriver() got invalid driver
    at BrowserDriver.<anonymous> (E:\weixin\wechaty\node_modules\.0.5.9@wechaty\
src\puppet-web\browser-driver.ts:145:17)
    at next (native)
    at fulfilled (E:\weixin\wechaty\node_modules\.0.5.9@wechaty\dist\src\puppet-
web\browser-driver.js:4:58)
    at run (E:\weixin\wechaty\node_modules\.2.4.1@core-js\modules\es6.promise.js
:87:22)
    at E:\weixin\wechaty\node_modules\.2.4.1@core-js\modules\es6.promise.js:100:
28
    at flush (E:\weixin\wechaty\node_modules\.2.4.1@core-js\modules\_microtask.j
s:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
ERR Wechaty init() exception: getChromeDriver() got invalid driver

**Comment by zixia** [comment]
please Run `npm run doctor`, paste output here.

**Comment by issmile** [comment]
额,我不会doctor,不会doctor 就跑不起来吗

**Comment by issmile** [comment]
node 版本需要大于等于7.00?才能跑?

**Comment by zixia** [comment]
Sort of.

At least u need node v6.9 because Selenium WebDriver requires node v6.9.0 or above to install.

**Comment by issmile** [comment]
OK I'm going to learn doctor

**Comment by zixia** [comment]
`doctor` is just an npm run script.

just run `npm run doctor` will get the output for you.

**Comment by zixia** [comment]
please test with the latest master. if still has problem,  submit a new issue  with all the require sections full filled.

have a good weekend!
