### ISSUE TITLE
docker is not stable, sometimes it got error, and sometimes it works well.

### ISSUE THREAD

**Issue by JasLin** [wechaty/wechaty#83]
docker is not so stable, sometimes it got error, and sometimes it works well.

sometimes it got errors with:

```
execute proxyWechaty(init) error: 503, init() without a ready angular env
````

and sometimes got errors with:

```
WARN PuppetWebBrowserDriver init() this.driver.quit() soft exception: NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
    at session_.flow_.promise (/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:855:16)
    at SimpleScheduler.promise (/wechaty/node_modules/selenium-webdriver/lib/promise.js:2128:12)
    at promise.finally (/wechaty/node_modules/selenium-webdriver/lib/webdriver.js:854:34)
    at promise.then.error (/wechaty/node_modules/selenium-webdriver/lib/promise.js:1574:12)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

```

```but in the  host computer , it always works all right. ```

### Actual behavior

```
  docker run -it --rm -v "$(pwd)":/bot zixia/wechaty:0.5.9 ding.ts
 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.wechaty.io
  ____                            _   _             
 / ___|___  _ __  _ __   ___  ___| |_(_)_ __   __ _ 
| |   / _ \| '_ \| '_ \ / _ \/ __| __| | '_ \ / _` |
| |__| (_) | | | | | | |  __/ (__| |_| | | | | (_| |
 \____\___/|_| |_|_| |_|\___|\___|\__|_|_| |_|\__, |
                                              |___/ 
  ____ _           _   ____        _       
 / ___| |__   __ _| |_| __ )  ___ | |_ ___ 
| |   | '_ \ / _` | __|  _ \ / _ \| __/ __|
| |___| | | | (_| | |_| |_) | (_) | |_\__ \
 \____|_| |_|\__,_|\__|____/ \___/ \__|___/
                                           

Starting Wechaty ... v0.5.9

Working directory: /bot
Install dependencies modules ...
yarn install v0.16.1
success Already up-to-date.
Done in 0.06s.
npm WARN wechaty-docker-test@1.0.0 No description
npm WARN wechaty-docker-test@1.0.0 No repository field.
Executing ts-node ding.ts

| __        __        _           _
| \ \      / /__  ___| |__   __ _| |_ _   _
|  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | |
|   \ V  V /  __/ (__| | | | (_| | |_| |_| |
|    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, |
|                                     |___/

=============== Powered by Wechaty ===============
-------- https://github.com/zixia/wechaty --------

I'm a bot, my super power is talk in Wechat.

If you send me a 'ding', I will reply you a 'dong'!
__________________________________________________

Hope you like it, and you are very welcome to
upgrade me for more super powers!

Please wait... I'm trying to login in...


INFO Wechaty v0.5.9 initializing...
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)
ERR PuppetWeb initBridge() exception: execute proxyWechaty(init) error: 503, init() without a ready angular env
ERR PuppetWeb init() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.<anonymous> (/wechaty/src/puppet-web/bridge.ts:71:15)
    at Generator.next (<anonymous>)
    at fulfilled (/wechaty/dist/src/puppet-web/bridge.js:4:58)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
INFO Bot error: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
WARN PuppetWebWatchdog onFeed() is disabled because target state is `dead` or state is inprocess
WARN PuppetWebBrowser execute() exception: unknown error: Cannot read property 'loginout' of undefined
  (Session info: chrome=53.0.2785.92)
 , WebDriverError: unknown error: Cannot read property 'loginout' of undefined
  (Session info: chrome=53.0.2785.92)
  (Driver info: chromedriver=2.22 (5e2d5494d735a71aa5c2e7ef9bf5ce96945e92e9),platform=Linux 4.4.0-45-generic x86_64)
    at Object.checkLegacyResponse (/wechaty/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/wechaty/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/wechaty/node_modules/selenium-webdriver/lib/http.js:440:13)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
WARN PuppetWebBridge execute() exception: unknown error: Cannot read property 'loginout' of undefined
  (Session info: chrome=53.0.2785.92)
  (Driver info: chromedriver=2.22 (5e2d5494d735a71aa5c2e7ef9bf5ce96945e92e9),platform=Linux 4.4.0-45-generic x86_64)
WARN PuppetWebBridge proxyWechaty() exception: unknown error: Cannot read property 'loginout' of undefined
  (Session info: chrome=53.0.2785.92)
  (Driver info: chromedriver=2.22 (5e2d5494d735a71aa5c2e7ef9bf5ce96945e92e9),platform=Linux 4.4.0-45-generic x86_64)
WARN PuppetWebBridge quit() exception: unknown error: Cannot read property 'loginout' of undefined
  (Session info: chrome=53.0.2785.92)
  (Driver info: chromedriver=2.22 (5e2d5494d735a71aa5c2e7ef9bf5ce96945e92e9),platform=Linux 4.4.0-45-generic x86_64)
ERR Wechaty init() exception: execute proxyWechaty(init) error: 503, init() without a ready angular env
ERR Bot init() fail: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
  ____  _   _  ____   ____  _____ ____   ___  ____ _____  
 | __ )| | | |/ ___| |  _ \| ____|  _ \ / _ \|  _ \_   _| 
 |  _ \| | | | |  _  | |_) |  _| | |_) | | | | |_) || |   
 | |_) | |_| | |_| | |  _ <| |___|  __/| |_| |  _ < | |   
 |____/ \___/ \____| |_| \_\_____|_|    \___/|_| \_\|_|   
                                                          
Press ENTER to continue ... 


### 1. source code of ding.ts

/**
 *
 * Wechaty - Wechat for Bot
 *
 * Connecting ChatBots
 * https://github.com/wechaty/wechaty
 *
 */

/* tslint:disable:variable-name */
const QrcodeTerminal = require('qrcode-terminal')

import {
  Wechaty
  , Config
  , log
} from 'wechaty'

const welcome = `
| __        __        _           _
| \\ \\      / /__  ___| |__   __ _| |_ _   _
|  \\ \\ /\\ / / _ \\/ __| '_ \\ / _\` | __| | | |
|   \\ V  V /  __/ (__| | | | (_| | |_| |_| |
|    \\_/\\_/ \\___|\\___|_| |_|\\__,_|\\__|\\__, |
|                                     |___/

=============== Powered by Wechaty ===============
-------- https://github.com/zixia/wechaty --------

I'm a bot, my super power is talk in Wechat.

If you send me a 'ding', I will reply you a 'dong'!
__________________________________________________

Hope you like it, and you are very welcome to
upgrade me for more super powers!

Please wait... I'm trying to login in...

`

console.log(welcome)
const bot = Wechaty.instance({ profile: Config.DEFAULT_PROFILE })

bot
.on('login'	  , user => log.info('Bot', `${user.name()} logined`))
.on('logout'	, user => log.info('Bot', `${user.name()} logouted`))
.on('error'   , e => log.info('Bot', 'error: %s', e))
.on('scan', (url, code) => {
  if (!/201|200/.test(String(code))) {
    let loginUrl = url.replace(/\/qrcode\//, '/l/')
    QrcodeTerminal.generate(loginUrl)
  }
  console.log(`${url}\n[${code}] Scan QR Code in above url to login: `)
})
.on('message', m => {
  try {
    const room = m.room()
    console.log((room ? '[' + room.topic() + ']' : '')
                + '<' + m.from().name() + '>'
                + ':' + m.toStringDigest()
    )

    if (/^(ding|ping|bing)$/i.test(m.content()) && !m.self()) {
      m.say('dong')
      log.info('Bot', 'REPLY: dong')
    }
  } catch (e) {
    log.error('Bot', 'on(message) exception: %s' , e)
  }
})

bot.init()
.catch(e => {
  log.error('Bot', 'init() fail: %s', e)
  bot.quit()
  process.exit(-1)
})

function logToFile(data) {
  require('fs').appendFile('message.log', data + '\n\n#############################\n\n', err => {
    if (err) { log.error('LogToFile: %s', err) }
  })
}
if (typeof logToFile === 'fasdfsd') {
  console.log('disable linting warning')
}


### 2. directory structor of /bot

total 20
-rw-r--r-- 1 root root  340 Nov  9 04:25 demo.wechaty.json
-rw-rw-r-- 1 1000 1000 2216 Nov  9 03:42 ding.ts
drwxr-xr-x 5 root root 4096 Nov  9 04:45 node_modules
-rw-rw-r-- 1 1000 1000  273 Nov  9 03:43 package.json
-rw-r--r-- 1 root root  257 Nov  9 03:44 yarn.lock

### 3. package.json

{
  "name": "wechaty-docker-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "qrcode-terminal": "^0.11.0"
  }
}

### 4. directory structor inside /bot/node_modules

@types	qrcode-terminal

### 5. wechaty doctor


#### Wechaty Doctor

1. Wechaty version: 0.5.9
2. Linux x64 version 4.4.0-45-generic memory 3177/15725 MB
3. Docker: true
4. Node version: v7.0.0


  ____        _               _ _             ___ ____ ____  _   _ _____  
 / ___| _   _| |__  _ __ ___ (_) |_    __ _  |_ _/ ___/ ___|| | | | ____| 
 \___ \| | | | '_ \| '_ ` _ \| | __|  / _` |  | |\___ \___ \| | | |  _|   
  ___) | |_| | |_) | | | | | | | |_  | (_| |  | | ___) |__) | |_| | |___  
 |____/ \__,_|_.__/|_| |_| |_|_|\__|  \__,_| |___|____/____/ \___/|_____| 
                                                                          
_____________________________________________________________
####### please paste all the above diagnose messages #######

Wechaty Issue https://github.com/wechaty/wechaty/issues

Press ENTER to continue ... 

 __        __        _           _          
 \ \      / /__  ___| |__   __ _| |_ _   _  
  \ \ /\ / / _ \/ __| '_ \ / _` | __| | | | 
   \ V  V /  __/ (__| | | | (_| | |_| |_| | 
    \_/\_/ \___|\___|_| |_|\__,_|\__|\__, | 
                                     |___/  
____________________________________________________
            https://www.wechaty.io
  _____      _ _     ____  ____ ____   
 | ____|_  _(_) |_  |___ \| ___| ___|  
 |  _| \ \/ / | __|   __) |___ \___ \  
 | |___ >  <| | |_   / __/ ___) |__) | 
 |_____/_/\_\_|\__| |_____|____/____/  
                                       
```

**Comment by zixia** [comment]
1. `soft exception`

  This is not harmful, for it's only a debug info. I'll change it from `warn` to a `verbose` later.

2. `execute proxyWechaty(init) error: 503, init() without a ready angular env`

  This message will appear when PuppetWeb can not find Angular inside the browser. Normally, after open https://wx.qq.com, the browser will render by angularjs, which will hook by PuppetWeb.

If `error: 503`, that means after retry serval times, the browser still not ready for angular. Normally this error will disappear by restart Wechaty Docker Runtime again, and I had not met this error message much.(sometimes)

How often will this message appear to you?

I suggest you have a check of your docker server network connectivity, and please feel free to let me know if `error: 503` still with you.

**Comment by JasLin** [comment]
it's often, it fails  with 5 times of 10 trying

sometimes it got this warning

```
INFO Wechaty v0.5.9 initializing...
WARN PuppetWebBrowserCookie addCookies() exception: invalid cookie domain: invalid domain:".wx2.qq.com"
  (Session info: chrome=53.0.2785.92)
  (Driver info: chromedriver=2.22 (5e2d5494d735a71aa5c2e7ef9bf5ce96945e92e9),platform=Linux 4.4.0-45-generic x86_64)
ERR PuppetWebBrowserCookie load() add() exception: invalid cookie domain: invalid domain:".wx2.qq.com"
  (Session info: chrome=53.0.2785.92)
  (Driver info: chromedriver=2.22 (5e2d5494d735a71aa5c2e7ef9bf5ce96945e92e9),platform=Linux 4.4.0-45-generic x86_64)
WARN PuppetWebBrowserDriver valid() driver.getSession() timeout(halt?)

```

yes, i guess it was cause by the network situation , i will run ```docker exec -it wechaty``` into the container,  and check the network.

**Comment by zixia** [comment]
The `addCookies() exception` is because https://github.com/wechaty/wechaty/issues/31#issuecomment-259344932

It is not very harmful because it only will cause your profile session fail between restart.

I will check & fix it later.

**Comment by zixia** [comment]
@JasLin add more checking code in `entrypoint.sh` is a great idea. 

I suggest you have a look at it, there's a function named: `wechaty::diagnose()`, it will be called if the robot start fail.

PR is welcome. :)

**Comment by JasLin** [comment]
confirm it , it was the problem cause by using google DNS

```
bash-4.3# ping www.baidu.com
PING www.baidu.com (14.215.177.37): 56 data bytes
64 bytes from 14.215.177.37: seq=0 ttl=55 time=7.857 ms
64 bytes from 14.215.177.37: seq=1 ttl=55 time=8.164 ms
^C
--- www.baidu.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 7.857/8.010/8.164 ms
bash-4.3# ping wx2.qq.com
ping: bad address 'wx2.qq.com'
bash-4.3# ping wx.qq.com
ping: bad address 'wx.qq.com'
bash-4.3# cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

nameserver 8.8.8.8
nameserver 8.8.4.4
bash-4.3# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:11:00:03  
          inet addr:172.17.0.3  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:acff:fe11:3%32729/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:599 errors:0 dropped:0 overruns:0 frame:0
          TX packets:509 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:586146 (572.4 KiB)  TX bytes:47453 (46.3 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1%32729/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1291 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1291 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:239769 (234.1 KiB)  TX bytes:239769 (234.1 KiB)

bash-4.3# 

```

**Comment by zixia** [comment]
ah, sorry for that. all my VPS is not inside China, so never notice that.

**Comment by JasLin** [comment]
can not agree more:)

**Comment by JasLin** [comment]
114.114.114.114 is one of the best choice inside  china:)

**Comment by zixia** [comment]
It seems that `/etc/resolv.conf` will be rewritten each time the docker container start.

So I put the code in `entrypoint.sh`, with two Open DNS Servers: 114.114.114.114 and 114.114.115.115

**Comment by sleedata** [comment]
@JasLin and @zixia , it's true. I experience this as well. So i need to stop docker instance and restart a second time. Then the issues go away..

**Comment by zixia** [comment]
@sleedata can you exec inside docker, and confirm this is caused by DNS?

run `cat /etc/resolv.conf` & `ping wx.qq.com` & `ping wx2.qq.com` is enough.

**Comment by JasLin** [comment]
@zixia have tested the latest docker, it's more stable than before. 

```
bash-4.3# cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 114.114.114.114
nameserver 114.114.115.115
```

**Comment by zixia** [comment]
@sleedata as you said, you are live in Canada. so I guess your issue is not related to google DNS?

could you help me to have a network test inside your container for the first time start?

**Comment by zixia** [comment]
dockers seems no problem now. 

please feel free to reopen this issue if there's other problem with docker.
